# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M100',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4657', models.IntegerField(default=1)),
                ('f4658', models.CharField(max_length=200)),
                ('f4659', models.TextField()),
                ('f4660', models.TextField()),
                ('f4661', models.CharField(max_length=200)),
                ('f4662', models.CharField(max_length=200)),
                ('f4663', models.CharField(max_length=200)),
                ('f4664', models.CharField(max_length=200)),
                ('f4665', models.CharField(max_length=200)),
                ('f4666', models.IntegerField(default=1)),
                ('f4667', models.TextField()),
                ('f4668', models.TextField()),
                ('f4669', models.CharField(max_length=200)),
                ('f4670', models.CharField(max_length=200)),
                ('f4671', models.TextField()),
                ('f4672', models.CharField(max_length=200)),
                ('f4673', models.TextField()),
                ('f4674', models.CharField(max_length=200)),
                ('f4675', models.CharField(max_length=200)),
                ('f4676', models.IntegerField(default=1)),
                ('f4677', models.CharField(max_length=200)),
                ('f4678', models.CharField(max_length=200)),
                ('f4679', models.TextField()),
                ('f4680', models.TextField()),
                ('f4681', models.CharField(max_length=200)),
                ('f4682', models.IntegerField(default=1)),
                ('f4683', models.TextField()),
                ('f4684', models.TextField()),
                ('f4685', models.IntegerField(default=1)),
                ('f4686', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M91',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4242', models.IntegerField(default=1)),
                ('f4243', models.TextField()),
                ('f4244', models.TextField()),
                ('f4245', models.CharField(max_length=200)),
                ('f4246', models.TextField()),
                ('f4247', models.TextField()),
                ('f4248', models.CharField(max_length=200)),
                ('f4249', models.IntegerField(default=1)),
                ('f4250', models.CharField(max_length=200)),
                ('f4251', models.TextField()),
                ('f4252', models.CharField(max_length=200)),
                ('f4253', models.CharField(max_length=200)),
                ('f4254', models.IntegerField(default=1)),
                ('f4255', models.CharField(max_length=200)),
                ('f4256', models.TextField()),
                ('f4257', models.TextField()),
                ('f4258', models.IntegerField(default=1)),
                ('f4259', models.TextField()),
                ('f4260', models.CharField(max_length=200)),
                ('f4261', models.TextField()),
                ('f4262', models.TextField()),
                ('f4263', models.IntegerField(default=1)),
                ('f4264', models.CharField(max_length=200)),
                ('f4265', models.TextField()),
                ('f4266', models.CharField(max_length=200)),
                ('f4267', models.CharField(max_length=200)),
                ('f4268', models.CharField(max_length=200)),
                ('f4269', models.TextField()),
                ('f4270', models.CharField(max_length=200)),
                ('f4271', models.IntegerField(default=1)),
                ('f4272', models.TextField()),
                ('f4273', models.IntegerField(default=1)),
                ('f4274', models.TextField()),
                ('f4275', models.TextField()),
                ('f4276', models.TextField()),
                ('f4277', models.IntegerField(default=1)),
                ('f4278', models.TextField()),
                ('f4279', models.CharField(max_length=200)),
                ('f4280', models.CharField(max_length=200)),
                ('f4281', models.IntegerField(default=1)),
                ('f4282', models.IntegerField(default=1)),
                ('f4283', models.TextField()),
                ('f4284', models.TextField()),
                ('f4285', models.CharField(max_length=200)),
                ('f4286', models.IntegerField(default=1)),
                ('f4287', models.IntegerField(default=1)),
                ('f4288', models.CharField(max_length=200)),
                ('f4289', models.TextField()),
                ('f4290', models.TextField()),
                ('f4291', models.TextField()),
                ('f4292', models.IntegerField(default=1)),
                ('f4293', models.IntegerField(default=1)),
                ('f4294', models.CharField(max_length=200)),
                ('f4295', models.CharField(max_length=200)),
                ('f4296', models.CharField(max_length=200)),
                ('f4297', models.IntegerField(default=1)),
                ('f4298', models.IntegerField(default=1)),
                ('f4299', models.IntegerField(default=1)),
                ('f4300', models.TextField()),
                ('f4301', models.IntegerField(default=1)),
                ('f4302', models.TextField()),
                ('f4303', models.CharField(max_length=200)),
                ('f4304', models.TextField()),
                ('f4305', models.CharField(max_length=200)),
                ('f4306', models.CharField(max_length=200)),
                ('f4307', models.TextField()),
                ('f4308', models.TextField()),
                ('f4309', models.IntegerField(default=1)),
                ('f4310', models.CharField(max_length=200)),
                ('f4311', models.TextField()),
                ('f4312', models.TextField()),
                ('f4313', models.CharField(max_length=200)),
                ('f4314', models.IntegerField(default=1)),
                ('f4315', models.TextField()),
                ('f4316', models.CharField(max_length=200)),
                ('f4317', models.CharField(max_length=200)),
                ('f4318', models.TextField()),
                ('f4319', models.CharField(max_length=200)),
                ('f4320', models.CharField(max_length=200)),
                ('f4321', models.TextField()),
                ('f4322', models.TextField()),
                ('f4323', models.CharField(max_length=200)),
                ('f4324', models.TextField()),
                ('f4325', models.IntegerField(default=1)),
                ('f4326', models.IntegerField(default=1)),
                ('f4327', models.CharField(max_length=200)),
                ('f4328', models.CharField(max_length=200)),
                ('f4329', models.IntegerField(default=1)),
                ('f4330', models.TextField()),
                ('f4331', models.IntegerField(default=1)),
                ('f4332', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M92',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4333', models.IntegerField(default=1)),
                ('f4334', models.CharField(max_length=200)),
                ('f4335', models.TextField()),
                ('f4336', models.CharField(max_length=200)),
                ('f4337', models.TextField()),
                ('f4338', models.IntegerField(default=1)),
                ('f4339', models.IntegerField(default=1)),
                ('f4340', models.IntegerField(default=1)),
                ('f4341', models.TextField()),
                ('f4342', models.IntegerField(default=1)),
                ('f4343', models.CharField(max_length=200)),
                ('f4344', models.TextField()),
                ('f4345', models.CharField(max_length=200)),
                ('f4346', models.CharField(max_length=200)),
                ('f4347', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M93',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4348', models.TextField()),
                ('f4349', models.CharField(max_length=200)),
                ('f4350', models.CharField(max_length=200)),
                ('f4351', models.TextField()),
                ('f4352', models.IntegerField(default=1)),
                ('f4353', models.TextField()),
                ('f4354', models.IntegerField(default=1)),
                ('f4355', models.CharField(max_length=200)),
                ('f4356', models.IntegerField(default=1)),
                ('f4357', models.CharField(max_length=200)),
                ('f4358', models.TextField()),
                ('f4359', models.TextField()),
                ('f4360', models.TextField()),
                ('f4361', models.TextField()),
                ('f4362', models.TextField()),
                ('f4363', models.IntegerField(default=1)),
                ('f4364', models.CharField(max_length=200)),
                ('f4365', models.IntegerField(default=1)),
                ('f4366', models.CharField(max_length=200)),
                ('f4367', models.TextField()),
                ('f4368', models.CharField(max_length=200)),
                ('f4369', models.CharField(max_length=200)),
                ('f4370', models.TextField()),
                ('f4371', models.TextField()),
                ('f4372', models.TextField()),
                ('f4373', models.TextField()),
                ('f4374', models.IntegerField(default=1)),
                ('f4375', models.IntegerField(default=1)),
                ('f4376', models.TextField()),
                ('f4377', models.CharField(max_length=200)),
                ('f4378', models.TextField()),
                ('f4379', models.CharField(max_length=200)),
                ('f4380', models.CharField(max_length=200)),
                ('f4381', models.IntegerField(default=1)),
                ('f4382', models.IntegerField(default=1)),
                ('f4383', models.CharField(max_length=200)),
                ('f4384', models.TextField()),
                ('f4385', models.IntegerField(default=1)),
                ('f4386', models.IntegerField(default=1)),
                ('f4387', models.TextField()),
                ('f4388', models.TextField()),
                ('f4389', models.CharField(max_length=200)),
                ('f4390', models.CharField(max_length=200)),
                ('f4391', models.IntegerField(default=1)),
                ('f4392', models.IntegerField(default=1)),
                ('f4393', models.CharField(max_length=200)),
                ('f4394', models.IntegerField(default=1)),
                ('f4395', models.TextField()),
                ('f4396', models.IntegerField(default=1)),
                ('f4397', models.TextField()),
                ('f4398', models.CharField(max_length=200)),
                ('f4399', models.CharField(max_length=200)),
                ('f4400', models.TextField()),
                ('f4401', models.TextField()),
                ('f4402', models.IntegerField(default=1)),
                ('f4403', models.CharField(max_length=200)),
                ('f4404', models.IntegerField(default=1)),
                ('f4405', models.TextField()),
                ('f4406', models.IntegerField(default=1)),
                ('f4407', models.CharField(max_length=200)),
                ('f4408', models.IntegerField(default=1)),
                ('f4409', models.IntegerField(default=1)),
                ('f4410', models.TextField()),
                ('f4411', models.CharField(max_length=200)),
                ('f4412', models.TextField()),
                ('f4413', models.TextField()),
                ('f4414', models.TextField()),
                ('f4415', models.CharField(max_length=200)),
                ('f4416', models.TextField()),
                ('f4417', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M94',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4418', models.TextField()),
                ('f4419', models.TextField()),
                ('f4420', models.CharField(max_length=200)),
                ('f4421', models.TextField()),
                ('f4422', models.TextField()),
                ('f4423', models.IntegerField(default=1)),
                ('f4424', models.CharField(max_length=200)),
                ('f4425', models.CharField(max_length=200)),
                ('f4426', models.CharField(max_length=200)),
                ('f4427', models.TextField()),
                ('f4428', models.TextField()),
                ('f4429', models.IntegerField(default=1)),
                ('f4430', models.CharField(max_length=200)),
                ('f4431', models.IntegerField(default=1)),
                ('f4432', models.IntegerField(default=1)),
                ('f4433', models.IntegerField(default=1)),
                ('f4434', models.CharField(max_length=200)),
                ('f4435', models.CharField(max_length=200)),
                ('f4436', models.IntegerField(default=1)),
                ('f4437', models.IntegerField(default=1)),
                ('f4438', models.CharField(max_length=200)),
                ('f4439', models.IntegerField(default=1)),
                ('f4440', models.TextField()),
                ('f4441', models.TextField()),
                ('f4442', models.IntegerField(default=1)),
                ('f4443', models.CharField(max_length=200)),
                ('f4444', models.CharField(max_length=200)),
                ('f4445', models.CharField(max_length=200)),
                ('f4446', models.CharField(max_length=200)),
                ('f4447', models.CharField(max_length=200)),
                ('f4448', models.IntegerField(default=1)),
                ('f4449', models.IntegerField(default=1)),
                ('f4450', models.CharField(max_length=200)),
                ('f4451', models.IntegerField(default=1)),
                ('f4452', models.IntegerField(default=1)),
                ('f4453', models.IntegerField(default=1)),
                ('f4454', models.IntegerField(default=1)),
                ('f4455', models.TextField()),
                ('f4456', models.IntegerField(default=1)),
                ('f4457', models.IntegerField(default=1)),
                ('f4458', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M95',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4459', models.TextField()),
                ('f4460', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M96',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4461', models.IntegerField(default=1)),
                ('f4462', models.CharField(max_length=200)),
                ('f4463', models.IntegerField(default=1)),
                ('f4464', models.CharField(max_length=200)),
                ('f4465', models.TextField()),
                ('f4466', models.CharField(max_length=200)),
                ('f4467', models.CharField(max_length=200)),
                ('f4468', models.TextField()),
                ('f4469', models.CharField(max_length=200)),
                ('f4470', models.IntegerField(default=1)),
                ('f4471', models.CharField(max_length=200)),
                ('f4472', models.TextField()),
                ('f4473', models.IntegerField(default=1)),
                ('f4474', models.CharField(max_length=200)),
                ('f4475', models.IntegerField(default=1)),
                ('f4476', models.TextField()),
                ('f4477', models.CharField(max_length=200)),
                ('f4478', models.IntegerField(default=1)),
                ('f4479', models.IntegerField(default=1)),
                ('f4480', models.TextField()),
                ('f4481', models.CharField(max_length=200)),
                ('f4482', models.TextField()),
                ('f4483', models.IntegerField(default=1)),
                ('f4484', models.TextField()),
                ('f4485', models.IntegerField(default=1)),
                ('f4486', models.TextField()),
                ('f4487', models.TextField()),
                ('f4488', models.CharField(max_length=200)),
                ('f4489', models.IntegerField(default=1)),
                ('f4490', models.CharField(max_length=200)),
                ('f4491', models.TextField()),
                ('f4492', models.CharField(max_length=200)),
                ('f4493', models.CharField(max_length=200)),
                ('f4494', models.TextField()),
                ('f4495', models.CharField(max_length=200)),
                ('f4496', models.TextField()),
                ('f4497', models.CharField(max_length=200)),
                ('f4498', models.CharField(max_length=200)),
                ('f4499', models.IntegerField(default=1)),
                ('f4500', models.TextField()),
                ('f4501', models.TextField()),
                ('f4502', models.IntegerField(default=1)),
                ('f4503', models.TextField()),
                ('f4504', models.TextField()),
                ('f4505', models.TextField()),
                ('f4506', models.TextField()),
                ('f4507', models.IntegerField(default=1)),
                ('f4508', models.CharField(max_length=200)),
                ('f4509', models.TextField()),
                ('f4510', models.TextField()),
                ('f4511', models.CharField(max_length=200)),
                ('f4512', models.IntegerField(default=1)),
                ('f4513', models.CharField(max_length=200)),
                ('f4514', models.TextField()),
                ('f4515', models.TextField()),
                ('f4516', models.IntegerField(default=1)),
                ('f4517', models.CharField(max_length=200)),
                ('f4518', models.TextField()),
                ('f4519', models.IntegerField(default=1)),
                ('f4520', models.IntegerField(default=1)),
                ('f4521', models.IntegerField(default=1)),
                ('f4522', models.IntegerField(default=1)),
                ('f4523', models.CharField(max_length=200)),
                ('f4524', models.CharField(max_length=200)),
                ('f4525', models.TextField()),
                ('f4526', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M97',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4527', models.IntegerField(default=1)),
                ('f4528', models.TextField()),
                ('f4529', models.IntegerField(default=1)),
                ('f4530', models.TextField()),
                ('f4531', models.TextField()),
                ('f4532', models.TextField()),
                ('f4533', models.TextField()),
                ('f4534', models.CharField(max_length=200)),
                ('f4535', models.CharField(max_length=200)),
                ('f4536', models.IntegerField(default=1)),
                ('f4537', models.TextField()),
                ('f4538', models.TextField()),
                ('f4539', models.CharField(max_length=200)),
                ('f4540', models.TextField()),
                ('f4541', models.CharField(max_length=200)),
                ('f4542', models.TextField()),
                ('f4543', models.TextField()),
                ('f4544', models.IntegerField(default=1)),
                ('f4545', models.CharField(max_length=200)),
                ('f4546', models.IntegerField(default=1)),
                ('f4547', models.TextField()),
                ('f4548', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M98',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4549', models.IntegerField(default=1)),
                ('f4550', models.IntegerField(default=1)),
                ('f4551', models.CharField(max_length=200)),
                ('f4552', models.IntegerField(default=1)),
                ('f4553', models.IntegerField(default=1)),
                ('f4554', models.TextField()),
                ('f4555', models.TextField()),
                ('f4556', models.CharField(max_length=200)),
                ('f4557', models.IntegerField(default=1)),
                ('f4558', models.IntegerField(default=1)),
                ('f4559', models.CharField(max_length=200)),
                ('f4560', models.IntegerField(default=1)),
                ('f4561', models.TextField()),
                ('f4562', models.CharField(max_length=200)),
                ('f4563', models.TextField()),
                ('f4564', models.TextField()),
                ('f4565', models.CharField(max_length=200)),
                ('f4566', models.IntegerField(default=1)),
                ('f4567', models.TextField()),
                ('f4568', models.IntegerField(default=1)),
                ('f4569', models.TextField()),
                ('f4570', models.TextField()),
                ('f4571', models.TextField()),
                ('f4572', models.IntegerField(default=1)),
                ('f4573', models.TextField()),
                ('f4574', models.CharField(max_length=200)),
                ('f4575', models.IntegerField(default=1)),
                ('f4576', models.CharField(max_length=200)),
                ('f4577', models.TextField()),
                ('f4578', models.IntegerField(default=1)),
                ('f4579', models.IntegerField(default=1)),
                ('f4580', models.TextField()),
                ('f4581', models.TextField()),
                ('f4582', models.TextField()),
                ('f4583', models.TextField()),
                ('f4584', models.TextField()),
                ('f4585', models.CharField(max_length=200)),
                ('f4586', models.CharField(max_length=200)),
                ('f4587', models.TextField()),
                ('f4588', models.CharField(max_length=200)),
                ('f4589', models.TextField()),
                ('f4590', models.TextField()),
                ('f4591', models.TextField()),
                ('f4592', models.TextField()),
                ('f4593', models.IntegerField(default=1)),
                ('f4594', models.IntegerField(default=1)),
                ('f4595', models.CharField(max_length=200)),
                ('f4596', models.TextField()),
                ('f4597', models.TextField()),
                ('f4598', models.TextField()),
                ('f4599', models.TextField()),
                ('f4600', models.IntegerField(default=1)),
                ('f4601', models.TextField()),
                ('f4602', models.CharField(max_length=200)),
                ('f4603', models.IntegerField(default=1)),
                ('f4604', models.IntegerField(default=1)),
                ('f4605', models.IntegerField(default=1)),
                ('f4606', models.CharField(max_length=200)),
                ('f4607', models.TextField()),
                ('f4608', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M99',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4609', models.CharField(max_length=200)),
                ('f4610', models.TextField()),
                ('f4611', models.TextField()),
                ('f4612', models.IntegerField(default=1)),
                ('f4613', models.IntegerField(default=1)),
                ('f4614', models.CharField(max_length=200)),
                ('f4615', models.CharField(max_length=200)),
                ('f4616', models.TextField()),
                ('f4617', models.TextField()),
                ('f4618', models.IntegerField(default=1)),
                ('f4619', models.CharField(max_length=200)),
                ('f4620', models.IntegerField(default=1)),
                ('f4621', models.CharField(max_length=200)),
                ('f4622', models.TextField()),
                ('f4623', models.IntegerField(default=1)),
                ('f4624', models.TextField()),
                ('f4625', models.TextField()),
                ('f4626', models.IntegerField(default=1)),
                ('f4627', models.CharField(max_length=200)),
                ('f4628', models.TextField()),
                ('f4629', models.TextField()),
                ('f4630', models.IntegerField(default=1)),
                ('f4631', models.CharField(max_length=200)),
                ('f4632', models.CharField(max_length=200)),
                ('f4633', models.IntegerField(default=1)),
                ('f4634', models.TextField()),
                ('f4635', models.TextField()),
                ('f4636', models.TextField()),
                ('f4637', models.TextField()),
                ('f4638', models.TextField()),
                ('f4639', models.TextField()),
                ('f4640', models.CharField(max_length=200)),
                ('f4641', models.CharField(max_length=200)),
                ('f4642', models.TextField()),
                ('f4643', models.TextField()),
                ('f4644', models.CharField(max_length=200)),
                ('f4645', models.TextField()),
                ('f4646', models.TextField()),
                ('f4647', models.CharField(max_length=200)),
                ('f4648', models.CharField(max_length=200)),
                ('f4649', models.CharField(max_length=200)),
                ('f4650', models.CharField(max_length=200)),
                ('f4651', models.TextField()),
                ('f4652', models.TextField()),
                ('f4653', models.IntegerField(default=1)),
                ('f4654', models.TextField()),
                ('f4655', models.TextField()),
                ('f4656', models.CharField(max_length=200)),
            ],
        ),
    ]
