# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M111',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5135', models.IntegerField(default=1)),
                ('f5136', models.IntegerField(default=1)),
                ('f5137', models.IntegerField(default=1)),
                ('f5138', models.CharField(max_length=200)),
                ('f5139', models.CharField(max_length=200)),
                ('f5140', models.TextField()),
                ('f5141', models.TextField()),
                ('f5142', models.TextField()),
                ('f5143', models.TextField()),
                ('f5144', models.TextField()),
                ('f5145', models.TextField()),
                ('f5146', models.IntegerField(default=1)),
                ('f5147', models.TextField()),
                ('f5148', models.TextField()),
                ('f5149', models.IntegerField(default=1)),
                ('f5150', models.IntegerField(default=1)),
                ('f5151', models.CharField(max_length=200)),
                ('f5152', models.CharField(max_length=200)),
                ('f5153', models.IntegerField(default=1)),
                ('f5154', models.CharField(max_length=200)),
                ('f5155', models.CharField(max_length=200)),
                ('f5156', models.CharField(max_length=200)),
                ('f5157', models.TextField()),
                ('f5158', models.TextField()),
                ('f5159', models.TextField()),
                ('f5160', models.CharField(max_length=200)),
                ('f5161', models.CharField(max_length=200)),
                ('f5162', models.IntegerField(default=1)),
                ('f5163', models.TextField()),
                ('f5164', models.IntegerField(default=1)),
                ('f5165', models.CharField(max_length=200)),
                ('f5166', models.TextField()),
                ('f5167', models.TextField()),
                ('f5168', models.TextField()),
                ('f5169', models.TextField()),
                ('f5170', models.TextField()),
                ('f5171', models.TextField()),
                ('f5172', models.CharField(max_length=200)),
                ('f5173', models.TextField()),
                ('f5174', models.CharField(max_length=200)),
                ('f5175', models.TextField()),
                ('f5176', models.CharField(max_length=200)),
                ('f5177', models.TextField()),
                ('f5178', models.TextField()),
                ('f5179', models.IntegerField(default=1)),
                ('f5180', models.IntegerField(default=1)),
                ('f5181', models.CharField(max_length=200)),
                ('f5182', models.TextField()),
                ('f5183', models.TextField()),
                ('f5184', models.TextField()),
                ('f5185', models.TextField()),
                ('f5186', models.TextField()),
                ('f5187', models.CharField(max_length=200)),
                ('f5188', models.IntegerField(default=1)),
                ('f5189', models.CharField(max_length=200)),
                ('f5190', models.CharField(max_length=200)),
                ('f5191', models.CharField(max_length=200)),
                ('f5192', models.CharField(max_length=200)),
                ('f5193', models.CharField(max_length=200)),
                ('f5194', models.IntegerField(default=1)),
                ('f5195', models.TextField()),
                ('f5196', models.TextField()),
                ('f5197', models.TextField()),
                ('f5198', models.CharField(max_length=200)),
                ('f5199', models.TextField()),
                ('f5200', models.TextField()),
                ('f5201', models.IntegerField(default=1)),
                ('f5202', models.CharField(max_length=200)),
                ('f5203', models.TextField()),
                ('f5204', models.CharField(max_length=200)),
                ('f5205', models.CharField(max_length=200)),
                ('f5206', models.CharField(max_length=200)),
                ('f5207', models.CharField(max_length=200)),
                ('f5208', models.IntegerField(default=1)),
                ('f5209', models.TextField()),
                ('f5210', models.TextField()),
                ('f5211', models.IntegerField(default=1)),
                ('f5212', models.TextField()),
                ('f5213', models.TextField()),
                ('f5214', models.CharField(max_length=200)),
                ('f5215', models.IntegerField(default=1)),
                ('f5216', models.TextField()),
                ('f5217', models.CharField(max_length=200)),
                ('f5218', models.CharField(max_length=200)),
                ('f5219', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M112',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5220', models.CharField(max_length=200)),
                ('f5221', models.TextField()),
                ('f5222', models.TextField()),
                ('f5223', models.IntegerField(default=1)),
                ('f5224', models.IntegerField(default=1)),
                ('f5225', models.TextField()),
                ('f5226', models.CharField(max_length=200)),
                ('f5227', models.CharField(max_length=200)),
                ('f5228', models.IntegerField(default=1)),
                ('f5229', models.CharField(max_length=200)),
                ('f5230', models.TextField()),
                ('f5231', models.IntegerField(default=1)),
                ('f5232', models.TextField()),
                ('f5233', models.TextField()),
                ('f5234', models.CharField(max_length=200)),
                ('f5235', models.TextField()),
                ('f5236', models.IntegerField(default=1)),
                ('f5237', models.TextField()),
                ('f5238', models.CharField(max_length=200)),
                ('f5239', models.TextField()),
                ('f5240', models.IntegerField(default=1)),
                ('f5241', models.IntegerField(default=1)),
                ('f5242', models.IntegerField(default=1)),
                ('f5243', models.TextField()),
                ('f5244', models.TextField()),
                ('f5245', models.TextField()),
                ('f5246', models.CharField(max_length=200)),
                ('f5247', models.IntegerField(default=1)),
                ('f5248', models.CharField(max_length=200)),
                ('f5249', models.TextField()),
                ('f5250', models.CharField(max_length=200)),
                ('f5251', models.IntegerField(default=1)),
                ('f5252', models.TextField()),
                ('f5253', models.IntegerField(default=1)),
                ('f5254', models.TextField()),
                ('f5255', models.TextField()),
                ('f5256', models.TextField()),
                ('f5257', models.IntegerField(default=1)),
                ('f5258', models.CharField(max_length=200)),
                ('f5259', models.CharField(max_length=200)),
                ('f5260', models.CharField(max_length=200)),
                ('f5261', models.CharField(max_length=200)),
                ('f5262', models.TextField()),
                ('f5263', models.TextField()),
                ('f5264', models.TextField()),
                ('f5265', models.CharField(max_length=200)),
                ('f5266', models.TextField()),
                ('f5267', models.TextField()),
                ('f5268', models.IntegerField(default=1)),
                ('f5269', models.IntegerField(default=1)),
                ('f5270', models.TextField()),
                ('f5271', models.CharField(max_length=200)),
                ('f5272', models.IntegerField(default=1)),
                ('f5273', models.CharField(max_length=200)),
                ('f5274', models.CharField(max_length=200)),
                ('f5275', models.TextField()),
                ('f5276', models.TextField()),
                ('f5277', models.CharField(max_length=200)),
                ('f5278', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M113',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5279', models.TextField()),
                ('f5280', models.IntegerField(default=1)),
                ('f5281', models.IntegerField(default=1)),
                ('f5282', models.CharField(max_length=200)),
                ('f5283', models.IntegerField(default=1)),
                ('f5284', models.TextField()),
                ('f5285', models.IntegerField(default=1)),
                ('f5286', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M114',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5287', models.IntegerField(default=1)),
                ('f5288', models.IntegerField(default=1)),
                ('f5289', models.IntegerField(default=1)),
                ('f5290', models.IntegerField(default=1)),
                ('f5291', models.TextField()),
                ('f5292', models.TextField()),
                ('f5293', models.IntegerField(default=1)),
                ('f5294', models.TextField()),
                ('f5295', models.CharField(max_length=200)),
                ('f5296', models.IntegerField(default=1)),
                ('f5297', models.CharField(max_length=200)),
                ('f5298', models.CharField(max_length=200)),
                ('f5299', models.TextField()),
                ('f5300', models.TextField()),
                ('f5301', models.TextField()),
                ('f5302', models.TextField()),
                ('f5303', models.TextField()),
                ('f5304', models.IntegerField(default=1)),
                ('f5305', models.IntegerField(default=1)),
                ('f5306', models.IntegerField(default=1)),
                ('f5307', models.CharField(max_length=200)),
                ('f5308', models.TextField()),
                ('f5309', models.TextField()),
                ('f5310', models.CharField(max_length=200)),
                ('f5311', models.IntegerField(default=1)),
                ('f5312', models.TextField()),
                ('f5313', models.CharField(max_length=200)),
                ('f5314', models.TextField()),
                ('f5315', models.CharField(max_length=200)),
                ('f5316', models.CharField(max_length=200)),
                ('f5317', models.CharField(max_length=200)),
                ('f5318', models.CharField(max_length=200)),
                ('f5319', models.CharField(max_length=200)),
                ('f5320', models.CharField(max_length=200)),
                ('f5321', models.TextField()),
                ('f5322', models.IntegerField(default=1)),
                ('f5323', models.TextField()),
                ('f5324', models.TextField()),
                ('f5325', models.CharField(max_length=200)),
                ('f5326', models.CharField(max_length=200)),
                ('f5327', models.CharField(max_length=200)),
                ('f5328', models.CharField(max_length=200)),
                ('f5329', models.IntegerField(default=1)),
                ('f5330', models.IntegerField(default=1)),
                ('f5331', models.IntegerField(default=1)),
                ('f5332', models.CharField(max_length=200)),
                ('f5333', models.TextField()),
                ('f5334', models.IntegerField(default=1)),
                ('f5335', models.TextField()),
                ('f5336', models.TextField()),
                ('f5337', models.CharField(max_length=200)),
                ('f5338', models.TextField()),
                ('f5339', models.IntegerField(default=1)),
                ('f5340', models.IntegerField(default=1)),
                ('f5341', models.IntegerField(default=1)),
                ('f5342', models.CharField(max_length=200)),
                ('f5343', models.IntegerField(default=1)),
                ('f5344', models.CharField(max_length=200)),
                ('f5345', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M115',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5346', models.IntegerField(default=1)),
                ('f5347', models.IntegerField(default=1)),
                ('f5348', models.CharField(max_length=200)),
                ('f5349', models.CharField(max_length=200)),
                ('f5350', models.TextField()),
                ('f5351', models.TextField()),
                ('f5352', models.CharField(max_length=200)),
                ('f5353', models.TextField()),
                ('f5354', models.IntegerField(default=1)),
                ('f5355', models.TextField()),
                ('f5356', models.IntegerField(default=1)),
                ('f5357', models.IntegerField(default=1)),
                ('f5358', models.CharField(max_length=200)),
                ('f5359', models.CharField(max_length=200)),
                ('f5360', models.CharField(max_length=200)),
                ('f5361', models.TextField()),
                ('f5362', models.TextField()),
                ('f5363', models.TextField()),
                ('f5364', models.TextField()),
                ('f5365', models.TextField()),
                ('f5366', models.TextField()),
                ('f5367', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M116',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5368', models.CharField(max_length=200)),
                ('f5369', models.CharField(max_length=200)),
                ('f5370', models.TextField()),
                ('f5371', models.IntegerField(default=1)),
                ('f5372', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M117',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5373', models.CharField(max_length=200)),
                ('f5374', models.TextField()),
                ('f5375', models.CharField(max_length=200)),
                ('f5376', models.TextField()),
                ('f5377', models.IntegerField(default=1)),
                ('f5378', models.TextField()),
                ('f5379', models.TextField()),
                ('f5380', models.TextField()),
                ('f5381', models.TextField()),
                ('f5382', models.TextField()),
                ('f5383', models.IntegerField(default=1)),
                ('f5384', models.TextField()),
                ('f5385', models.TextField()),
                ('f5386', models.CharField(max_length=200)),
                ('f5387', models.IntegerField(default=1)),
                ('f5388', models.TextField()),
                ('f5389', models.IntegerField(default=1)),
                ('f5390', models.CharField(max_length=200)),
                ('f5391', models.CharField(max_length=200)),
                ('f5392', models.CharField(max_length=200)),
                ('f5393', models.TextField()),
                ('f5394', models.IntegerField(default=1)),
                ('f5395', models.IntegerField(default=1)),
                ('f5396', models.TextField()),
                ('f5397', models.CharField(max_length=200)),
                ('f5398', models.CharField(max_length=200)),
                ('f5399', models.CharField(max_length=200)),
                ('f5400', models.TextField()),
                ('f5401', models.CharField(max_length=200)),
                ('f5402', models.CharField(max_length=200)),
                ('f5403', models.IntegerField(default=1)),
                ('f5404', models.CharField(max_length=200)),
                ('f5405', models.IntegerField(default=1)),
                ('f5406', models.CharField(max_length=200)),
                ('f5407', models.TextField()),
                ('f5408', models.TextField()),
                ('f5409', models.TextField()),
                ('f5410', models.TextField()),
                ('f5411', models.CharField(max_length=200)),
                ('f5412', models.TextField()),
                ('f5413', models.IntegerField(default=1)),
                ('f5414', models.CharField(max_length=200)),
                ('f5415', models.CharField(max_length=200)),
                ('f5416', models.TextField()),
                ('f5417', models.TextField()),
                ('f5418', models.CharField(max_length=200)),
                ('f5419', models.TextField()),
                ('f5420', models.CharField(max_length=200)),
                ('f5421', models.IntegerField(default=1)),
                ('f5422', models.CharField(max_length=200)),
                ('f5423', models.IntegerField(default=1)),
                ('f5424', models.CharField(max_length=200)),
                ('f5425', models.IntegerField(default=1)),
                ('f5426', models.TextField()),
                ('f5427', models.IntegerField(default=1)),
                ('f5428', models.IntegerField(default=1)),
                ('f5429', models.TextField()),
                ('f5430', models.IntegerField(default=1)),
                ('f5431', models.CharField(max_length=200)),
                ('f5432', models.IntegerField(default=1)),
                ('f5433', models.IntegerField(default=1)),
                ('f5434', models.TextField()),
                ('f5435', models.IntegerField(default=1)),
                ('f5436', models.IntegerField(default=1)),
                ('f5437', models.TextField()),
                ('f5438', models.CharField(max_length=200)),
                ('f5439', models.CharField(max_length=200)),
                ('f5440', models.TextField()),
                ('f5441', models.IntegerField(default=1)),
                ('f5442', models.IntegerField(default=1)),
                ('f5443', models.CharField(max_length=200)),
                ('f5444', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M118',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5445', models.TextField()),
                ('f5446', models.CharField(max_length=200)),
                ('f5447', models.TextField()),
                ('f5448', models.CharField(max_length=200)),
                ('f5449', models.CharField(max_length=200)),
                ('f5450', models.CharField(max_length=200)),
                ('f5451', models.TextField()),
                ('f5452', models.CharField(max_length=200)),
                ('f5453', models.TextField()),
                ('f5454', models.TextField()),
                ('f5455', models.IntegerField(default=1)),
                ('f5456', models.IntegerField(default=1)),
                ('f5457', models.IntegerField(default=1)),
                ('f5458', models.CharField(max_length=200)),
                ('f5459', models.TextField()),
                ('f5460', models.CharField(max_length=200)),
                ('f5461', models.CharField(max_length=200)),
                ('f5462', models.CharField(max_length=200)),
                ('f5463', models.CharField(max_length=200)),
                ('f5464', models.TextField()),
                ('f5465', models.IntegerField(default=1)),
                ('f5466', models.IntegerField(default=1)),
                ('f5467', models.CharField(max_length=200)),
                ('f5468', models.IntegerField(default=1)),
                ('f5469', models.CharField(max_length=200)),
                ('f5470', models.IntegerField(default=1)),
                ('f5471', models.CharField(max_length=200)),
                ('f5472', models.TextField()),
                ('f5473', models.TextField()),
                ('f5474', models.IntegerField(default=1)),
                ('f5475', models.CharField(max_length=200)),
                ('f5476', models.IntegerField(default=1)),
                ('f5477', models.TextField()),
                ('f5478', models.TextField()),
                ('f5479', models.CharField(max_length=200)),
                ('f5480', models.TextField()),
                ('f5481', models.CharField(max_length=200)),
                ('f5482', models.IntegerField(default=1)),
                ('f5483', models.CharField(max_length=200)),
                ('f5484', models.TextField()),
                ('f5485', models.CharField(max_length=200)),
                ('f5486', models.TextField()),
                ('f5487', models.IntegerField(default=1)),
                ('f5488', models.TextField()),
                ('f5489', models.CharField(max_length=200)),
                ('f5490', models.IntegerField(default=1)),
                ('f5491', models.TextField()),
                ('f5492', models.CharField(max_length=200)),
                ('f5493', models.IntegerField(default=1)),
                ('f5494', models.CharField(max_length=200)),
                ('f5495', models.IntegerField(default=1)),
                ('f5496', models.TextField()),
                ('f5497', models.TextField()),
                ('f5498', models.CharField(max_length=200)),
                ('f5499', models.CharField(max_length=200)),
                ('f5500', models.CharField(max_length=200)),
                ('f5501', models.TextField()),
                ('f5502', models.TextField()),
                ('f5503', models.IntegerField(default=1)),
                ('f5504', models.IntegerField(default=1)),
                ('f5505', models.CharField(max_length=200)),
                ('f5506', models.TextField()),
                ('f5507', models.CharField(max_length=200)),
                ('f5508', models.TextField()),
                ('f5509', models.CharField(max_length=200)),
                ('f5510', models.CharField(max_length=200)),
                ('f5511', models.TextField()),
                ('f5512', models.IntegerField(default=1)),
                ('f5513', models.TextField()),
                ('f5514', models.TextField()),
                ('f5515', models.TextField()),
                ('f5516', models.TextField()),
                ('f5517', models.TextField()),
                ('f5518', models.IntegerField(default=1)),
                ('f5519', models.TextField()),
                ('f5520', models.IntegerField(default=1)),
                ('f5521', models.TextField()),
                ('f5522', models.TextField()),
                ('f5523', models.TextField()),
                ('f5524', models.CharField(max_length=200)),
                ('f5525', models.CharField(max_length=200)),
                ('f5526', models.TextField()),
                ('f5527', models.IntegerField(default=1)),
                ('f5528', models.IntegerField(default=1)),
                ('f5529', models.IntegerField(default=1)),
                ('f5530', models.CharField(max_length=200)),
                ('f5531', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M119',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5532', models.CharField(max_length=200)),
                ('f5533', models.TextField()),
                ('f5534', models.CharField(max_length=200)),
                ('f5535', models.TextField()),
                ('f5536', models.CharField(max_length=200)),
                ('f5537', models.IntegerField(default=1)),
                ('f5538', models.CharField(max_length=200)),
                ('f5539', models.CharField(max_length=200)),
                ('f5540', models.CharField(max_length=200)),
                ('f5541', models.TextField()),
                ('f5542', models.CharField(max_length=200)),
                ('f5543', models.TextField()),
                ('f5544', models.TextField()),
                ('f5545', models.IntegerField(default=1)),
                ('f5546', models.TextField()),
                ('f5547', models.CharField(max_length=200)),
                ('f5548', models.CharField(max_length=200)),
                ('f5549', models.TextField()),
                ('f5550', models.IntegerField(default=1)),
                ('f5551', models.IntegerField(default=1)),
                ('f5552', models.IntegerField(default=1)),
                ('f5553', models.IntegerField(default=1)),
                ('f5554', models.CharField(max_length=200)),
                ('f5555', models.TextField()),
                ('f5556', models.IntegerField(default=1)),
                ('f5557', models.CharField(max_length=200)),
                ('f5558', models.CharField(max_length=200)),
                ('f5559', models.IntegerField(default=1)),
                ('f5560', models.CharField(max_length=200)),
                ('f5561', models.TextField()),
                ('f5562', models.IntegerField(default=1)),
                ('f5563', models.CharField(max_length=200)),
                ('f5564', models.TextField()),
                ('f5565', models.CharField(max_length=200)),
                ('f5566', models.TextField()),
                ('f5567', models.CharField(max_length=200)),
                ('f5568', models.CharField(max_length=200)),
                ('f5569', models.TextField()),
                ('f5570', models.CharField(max_length=200)),
                ('f5571', models.IntegerField(default=1)),
                ('f5572', models.IntegerField(default=1)),
                ('f5573', models.TextField()),
                ('f5574', models.TextField()),
                ('f5575', models.IntegerField(default=1)),
                ('f5576', models.CharField(max_length=200)),
                ('f5577', models.IntegerField(default=1)),
                ('f5578', models.TextField()),
                ('f5579', models.IntegerField(default=1)),
                ('f5580', models.IntegerField(default=1)),
                ('f5581', models.TextField()),
                ('f5582', models.TextField()),
                ('f5583', models.CharField(max_length=200)),
                ('f5584', models.CharField(max_length=200)),
                ('f5585', models.IntegerField(default=1)),
                ('f5586', models.TextField()),
                ('f5587', models.TextField()),
                ('f5588', models.CharField(max_length=200)),
                ('f5589', models.IntegerField(default=1)),
                ('f5590', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M120',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5591', models.TextField()),
                ('f5592', models.CharField(max_length=200)),
                ('f5593', models.CharField(max_length=200)),
                ('f5594', models.CharField(max_length=200)),
                ('f5595', models.TextField()),
                ('f5596', models.TextField()),
                ('f5597', models.TextField()),
                ('f5598', models.TextField()),
                ('f5599', models.CharField(max_length=200)),
                ('f5600', models.CharField(max_length=200)),
                ('f5601', models.IntegerField(default=1)),
                ('f5602', models.IntegerField(default=1)),
                ('f5603', models.IntegerField(default=1)),
                ('f5604', models.TextField()),
                ('f5605', models.TextField()),
                ('f5606', models.TextField()),
                ('f5607', models.TextField()),
                ('f5608', models.TextField()),
                ('f5609', models.TextField()),
                ('f5610', models.IntegerField(default=1)),
                ('f5611', models.IntegerField(default=1)),
                ('f5612', models.TextField()),
                ('f5613', models.CharField(max_length=200)),
                ('f5614', models.IntegerField(default=1)),
                ('f5615', models.TextField()),
                ('f5616', models.IntegerField(default=1)),
                ('f5617', models.TextField()),
                ('f5618', models.TextField()),
                ('f5619', models.CharField(max_length=200)),
                ('f5620', models.CharField(max_length=200)),
                ('f5621', models.TextField()),
                ('f5622', models.CharField(max_length=200)),
                ('f5623', models.IntegerField(default=1)),
                ('f5624', models.TextField()),
                ('f5625', models.TextField()),
                ('f5626', models.TextField()),
                ('f5627', models.IntegerField(default=1)),
                ('f5628', models.TextField()),
                ('f5629', models.CharField(max_length=200)),
                ('f5630', models.CharField(max_length=200)),
                ('f5631', models.TextField()),
                ('f5632', models.CharField(max_length=200)),
                ('f5633', models.IntegerField(default=1)),
                ('f5634', models.CharField(max_length=200)),
                ('f5635', models.TextField()),
                ('f5636', models.CharField(max_length=200)),
                ('f5637', models.IntegerField(default=1)),
                ('f5638', models.CharField(max_length=200)),
                ('f5639', models.TextField()),
                ('f5640', models.TextField()),
                ('f5641', models.TextField()),
                ('f5642', models.IntegerField(default=1)),
                ('f5643', models.CharField(max_length=200)),
                ('f5644', models.IntegerField(default=1)),
                ('f5645', models.TextField()),
                ('f5646', models.CharField(max_length=200)),
                ('f5647', models.CharField(max_length=200)),
                ('f5648', models.TextField()),
                ('f5649', models.IntegerField(default=1)),
                ('f5650', models.CharField(max_length=200)),
                ('f5651', models.CharField(max_length=200)),
                ('f5652', models.IntegerField(default=1)),
                ('f5653', models.CharField(max_length=200)),
                ('f5654', models.CharField(max_length=200)),
                ('f5655', models.IntegerField(default=1)),
                ('f5656', models.TextField()),
                ('f5657', models.TextField()),
                ('f5658', models.TextField()),
                ('f5659', models.TextField()),
                ('f5660', models.CharField(max_length=200)),
                ('f5661', models.TextField()),
                ('f5662', models.TextField()),
                ('f5663', models.CharField(max_length=200)),
                ('f5664', models.IntegerField(default=1)),
                ('f5665', models.TextField()),
                ('f5666', models.CharField(max_length=200)),
                ('f5667', models.IntegerField(default=1)),
                ('f5668', models.TextField()),
                ('f5669', models.IntegerField(default=1)),
                ('f5670', models.IntegerField(default=1)),
                ('f5671', models.IntegerField(default=1)),
                ('f5672', models.IntegerField(default=1)),
                ('f5673', models.IntegerField(default=1)),
                ('f5674', models.CharField(max_length=200)),
                ('f5675', models.IntegerField(default=1)),
                ('f5676', models.TextField()),
                ('f5677', models.CharField(max_length=200)),
                ('f5678', models.IntegerField(default=1)),
                ('f5679', models.CharField(max_length=200)),
                ('f5680', models.TextField()),
                ('f5681', models.IntegerField(default=1)),
                ('f5682', models.IntegerField(default=1)),
                ('f5683', models.CharField(max_length=200)),
                ('f5684', models.TextField()),
                ('f5685', models.TextField()),
                ('f5686', models.CharField(max_length=200)),
                ('f5687', models.TextField()),
                ('f5688', models.IntegerField(default=1)),
            ],
        ),
    ]
