# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M101',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4687', models.IntegerField(default=1)),
                ('f4688', models.IntegerField(default=1)),
                ('f4689', models.TextField()),
                ('f4690', models.IntegerField(default=1)),
                ('f4691', models.CharField(max_length=200)),
                ('f4692', models.TextField()),
                ('f4693', models.TextField()),
                ('f4694', models.CharField(max_length=200)),
                ('f4695', models.CharField(max_length=200)),
                ('f4696', models.TextField()),
                ('f4697', models.CharField(max_length=200)),
                ('f4698', models.CharField(max_length=200)),
                ('f4699', models.TextField()),
                ('f4700', models.TextField()),
                ('f4701', models.CharField(max_length=200)),
                ('f4702', models.CharField(max_length=200)),
                ('f4703', models.TextField()),
                ('f4704', models.TextField()),
                ('f4705', models.CharField(max_length=200)),
                ('f4706', models.IntegerField(default=1)),
                ('f4707', models.TextField()),
                ('f4708', models.IntegerField(default=1)),
                ('f4709', models.IntegerField(default=1)),
                ('f4710', models.TextField()),
                ('f4711', models.IntegerField(default=1)),
                ('f4712', models.TextField()),
                ('f4713', models.IntegerField(default=1)),
                ('f4714', models.CharField(max_length=200)),
                ('f4715', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M102',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4716', models.TextField()),
                ('f4717', models.IntegerField(default=1)),
                ('f4718', models.CharField(max_length=200)),
                ('f4719', models.TextField()),
                ('f4720', models.IntegerField(default=1)),
                ('f4721', models.CharField(max_length=200)),
                ('f4722', models.CharField(max_length=200)),
                ('f4723', models.TextField()),
                ('f4724', models.IntegerField(default=1)),
                ('f4725', models.CharField(max_length=200)),
                ('f4726', models.CharField(max_length=200)),
                ('f4727', models.IntegerField(default=1)),
                ('f4728', models.TextField()),
                ('f4729', models.IntegerField(default=1)),
                ('f4730', models.TextField()),
                ('f4731', models.TextField()),
                ('f4732', models.CharField(max_length=200)),
                ('f4733', models.CharField(max_length=200)),
                ('f4734', models.CharField(max_length=200)),
                ('f4735', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M103',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4736', models.IntegerField(default=1)),
                ('f4737', models.TextField()),
                ('f4738', models.TextField()),
                ('f4739', models.TextField()),
                ('f4740', models.IntegerField(default=1)),
                ('f4741', models.CharField(max_length=200)),
                ('f4742', models.CharField(max_length=200)),
                ('f4743', models.IntegerField(default=1)),
                ('f4744', models.IntegerField(default=1)),
                ('f4745', models.IntegerField(default=1)),
                ('f4746', models.IntegerField(default=1)),
                ('f4747', models.IntegerField(default=1)),
                ('f4748', models.TextField()),
                ('f4749', models.IntegerField(default=1)),
                ('f4750', models.CharField(max_length=200)),
                ('f4751', models.IntegerField(default=1)),
                ('f4752', models.CharField(max_length=200)),
                ('f4753', models.TextField()),
                ('f4754', models.TextField()),
                ('f4755', models.IntegerField(default=1)),
                ('f4756', models.IntegerField(default=1)),
                ('f4757', models.IntegerField(default=1)),
                ('f4758', models.TextField()),
                ('f4759', models.TextField()),
                ('f4760', models.IntegerField(default=1)),
                ('f4761', models.TextField()),
                ('f4762', models.CharField(max_length=200)),
                ('f4763', models.IntegerField(default=1)),
                ('f4764', models.CharField(max_length=200)),
                ('f4765', models.CharField(max_length=200)),
                ('f4766', models.IntegerField(default=1)),
                ('f4767', models.IntegerField(default=1)),
                ('f4768', models.IntegerField(default=1)),
                ('f4769', models.IntegerField(default=1)),
                ('f4770', models.CharField(max_length=200)),
                ('f4771', models.CharField(max_length=200)),
                ('f4772', models.CharField(max_length=200)),
                ('f4773', models.TextField()),
                ('f4774', models.CharField(max_length=200)),
                ('f4775', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M104',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4776', models.TextField()),
                ('f4777', models.CharField(max_length=200)),
                ('f4778', models.CharField(max_length=200)),
                ('f4779', models.IntegerField(default=1)),
                ('f4780', models.TextField()),
                ('f4781', models.TextField()),
                ('f4782', models.IntegerField(default=1)),
                ('f4783', models.CharField(max_length=200)),
                ('f4784', models.TextField()),
                ('f4785', models.TextField()),
                ('f4786', models.IntegerField(default=1)),
                ('f4787', models.TextField()),
                ('f4788', models.TextField()),
                ('f4789', models.TextField()),
                ('f4790', models.IntegerField(default=1)),
                ('f4791', models.IntegerField(default=1)),
                ('f4792', models.CharField(max_length=200)),
                ('f4793', models.CharField(max_length=200)),
                ('f4794', models.CharField(max_length=200)),
                ('f4795', models.CharField(max_length=200)),
                ('f4796', models.TextField()),
                ('f4797', models.TextField()),
                ('f4798', models.IntegerField(default=1)),
                ('f4799', models.IntegerField(default=1)),
                ('f4800', models.CharField(max_length=200)),
                ('f4801', models.IntegerField(default=1)),
                ('f4802', models.CharField(max_length=200)),
                ('f4803', models.TextField()),
                ('f4804', models.CharField(max_length=200)),
                ('f4805', models.TextField()),
                ('f4806', models.IntegerField(default=1)),
                ('f4807', models.CharField(max_length=200)),
                ('f4808', models.IntegerField(default=1)),
                ('f4809', models.IntegerField(default=1)),
                ('f4810', models.CharField(max_length=200)),
                ('f4811', models.IntegerField(default=1)),
                ('f4812', models.IntegerField(default=1)),
                ('f4813', models.TextField()),
                ('f4814', models.CharField(max_length=200)),
                ('f4815', models.IntegerField(default=1)),
                ('f4816', models.TextField()),
                ('f4817', models.IntegerField(default=1)),
                ('f4818', models.TextField()),
                ('f4819', models.CharField(max_length=200)),
                ('f4820', models.IntegerField(default=1)),
                ('f4821', models.CharField(max_length=200)),
                ('f4822', models.IntegerField(default=1)),
                ('f4823', models.IntegerField(default=1)),
                ('f4824', models.TextField()),
                ('f4825', models.CharField(max_length=200)),
                ('f4826', models.CharField(max_length=200)),
                ('f4827', models.TextField()),
                ('f4828', models.IntegerField(default=1)),
                ('f4829', models.CharField(max_length=200)),
                ('f4830', models.CharField(max_length=200)),
                ('f4831', models.CharField(max_length=200)),
                ('f4832', models.IntegerField(default=1)),
                ('f4833', models.TextField()),
                ('f4834', models.TextField()),
                ('f4835', models.TextField()),
                ('f4836', models.CharField(max_length=200)),
                ('f4837', models.IntegerField(default=1)),
                ('f4838', models.TextField()),
                ('f4839', models.TextField()),
                ('f4840', models.CharField(max_length=200)),
                ('f4841', models.TextField()),
                ('f4842', models.CharField(max_length=200)),
                ('f4843', models.TextField()),
                ('f4844', models.CharField(max_length=200)),
                ('f4845', models.CharField(max_length=200)),
                ('f4846', models.CharField(max_length=200)),
                ('f4847', models.CharField(max_length=200)),
                ('f4848', models.TextField()),
                ('f4849', models.TextField()),
                ('f4850', models.IntegerField(default=1)),
                ('f4851', models.IntegerField(default=1)),
                ('f4852', models.TextField()),
                ('f4853', models.IntegerField(default=1)),
                ('f4854', models.TextField()),
                ('f4855', models.CharField(max_length=200)),
                ('f4856', models.CharField(max_length=200)),
                ('f4857', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M105',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4858', models.IntegerField(default=1)),
                ('f4859', models.CharField(max_length=200)),
                ('f4860', models.TextField()),
                ('f4861', models.TextField()),
                ('f4862', models.TextField()),
                ('f4863', models.CharField(max_length=200)),
                ('f4864', models.CharField(max_length=200)),
                ('f4865', models.TextField()),
                ('f4866', models.CharField(max_length=200)),
                ('f4867', models.CharField(max_length=200)),
                ('f4868', models.TextField()),
                ('f4869', models.TextField()),
                ('f4870', models.TextField()),
                ('f4871', models.CharField(max_length=200)),
                ('f4872', models.TextField()),
                ('f4873', models.IntegerField(default=1)),
                ('f4874', models.IntegerField(default=1)),
                ('f4875', models.IntegerField(default=1)),
                ('f4876', models.TextField()),
                ('f4877', models.CharField(max_length=200)),
                ('f4878', models.IntegerField(default=1)),
                ('f4879', models.TextField()),
                ('f4880', models.TextField()),
                ('f4881', models.TextField()),
                ('f4882', models.TextField()),
                ('f4883', models.TextField()),
                ('f4884', models.TextField()),
                ('f4885', models.TextField()),
                ('f4886', models.CharField(max_length=200)),
                ('f4887', models.IntegerField(default=1)),
                ('f4888', models.TextField()),
                ('f4889', models.CharField(max_length=200)),
                ('f4890', models.CharField(max_length=200)),
                ('f4891', models.CharField(max_length=200)),
                ('f4892', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M106',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4893', models.IntegerField(default=1)),
                ('f4894', models.CharField(max_length=200)),
                ('f4895', models.TextField()),
                ('f4896', models.IntegerField(default=1)),
                ('f4897', models.IntegerField(default=1)),
                ('f4898', models.CharField(max_length=200)),
                ('f4899', models.IntegerField(default=1)),
                ('f4900', models.CharField(max_length=200)),
                ('f4901', models.IntegerField(default=1)),
                ('f4902', models.TextField()),
                ('f4903', models.IntegerField(default=1)),
                ('f4904', models.TextField()),
                ('f4905', models.IntegerField(default=1)),
                ('f4906', models.TextField()),
                ('f4907', models.TextField()),
                ('f4908', models.CharField(max_length=200)),
                ('f4909', models.IntegerField(default=1)),
                ('f4910', models.CharField(max_length=200)),
                ('f4911', models.CharField(max_length=200)),
                ('f4912', models.CharField(max_length=200)),
                ('f4913', models.IntegerField(default=1)),
                ('f4914', models.TextField()),
                ('f4915', models.CharField(max_length=200)),
                ('f4916', models.TextField()),
                ('f4917', models.TextField()),
                ('f4918', models.TextField()),
                ('f4919', models.TextField()),
                ('f4920', models.IntegerField(default=1)),
                ('f4921', models.CharField(max_length=200)),
                ('f4922', models.CharField(max_length=200)),
                ('f4923', models.IntegerField(default=1)),
                ('f4924', models.TextField()),
                ('f4925', models.TextField()),
                ('f4926', models.TextField()),
                ('f4927', models.IntegerField(default=1)),
                ('f4928', models.IntegerField(default=1)),
                ('f4929', models.CharField(max_length=200)),
                ('f4930', models.TextField()),
                ('f4931', models.IntegerField(default=1)),
                ('f4932', models.IntegerField(default=1)),
                ('f4933', models.TextField()),
                ('f4934', models.TextField()),
                ('f4935', models.IntegerField(default=1)),
                ('f4936', models.IntegerField(default=1)),
                ('f4937', models.TextField()),
                ('f4938', models.IntegerField(default=1)),
                ('f4939', models.IntegerField(default=1)),
                ('f4940', models.TextField()),
                ('f4941', models.TextField()),
                ('f4942', models.TextField()),
                ('f4943', models.IntegerField(default=1)),
                ('f4944', models.CharField(max_length=200)),
                ('f4945', models.IntegerField(default=1)),
                ('f4946', models.TextField()),
                ('f4947', models.TextField()),
                ('f4948', models.TextField()),
                ('f4949', models.CharField(max_length=200)),
                ('f4950', models.CharField(max_length=200)),
                ('f4951', models.IntegerField(default=1)),
                ('f4952', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M107',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4953', models.TextField()),
                ('f4954', models.TextField()),
                ('f4955', models.IntegerField(default=1)),
                ('f4956', models.CharField(max_length=200)),
                ('f4957', models.CharField(max_length=200)),
                ('f4958', models.IntegerField(default=1)),
                ('f4959', models.CharField(max_length=200)),
                ('f4960', models.CharField(max_length=200)),
                ('f4961', models.TextField()),
                ('f4962', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M108',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4963', models.IntegerField(default=1)),
                ('f4964', models.IntegerField(default=1)),
                ('f4965', models.TextField()),
                ('f4966', models.TextField()),
                ('f4967', models.CharField(max_length=200)),
                ('f4968', models.IntegerField(default=1)),
                ('f4969', models.IntegerField(default=1)),
                ('f4970', models.CharField(max_length=200)),
                ('f4971', models.TextField()),
                ('f4972', models.IntegerField(default=1)),
                ('f4973', models.TextField()),
                ('f4974', models.TextField()),
                ('f4975', models.CharField(max_length=200)),
                ('f4976', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M109',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4977', models.TextField()),
                ('f4978', models.IntegerField(default=1)),
                ('f4979', models.IntegerField(default=1)),
                ('f4980', models.IntegerField(default=1)),
                ('f4981', models.IntegerField(default=1)),
                ('f4982', models.CharField(max_length=200)),
                ('f4983', models.CharField(max_length=200)),
                ('f4984', models.CharField(max_length=200)),
                ('f4985', models.CharField(max_length=200)),
                ('f4986', models.CharField(max_length=200)),
                ('f4987', models.CharField(max_length=200)),
                ('f4988', models.CharField(max_length=200)),
                ('f4989', models.IntegerField(default=1)),
                ('f4990', models.IntegerField(default=1)),
                ('f4991', models.CharField(max_length=200)),
                ('f4992', models.TextField()),
                ('f4993', models.TextField()),
                ('f4994', models.TextField()),
                ('f4995', models.TextField()),
                ('f4996', models.CharField(max_length=200)),
                ('f4997', models.IntegerField(default=1)),
                ('f4998', models.IntegerField(default=1)),
                ('f4999', models.IntegerField(default=1)),
                ('f5000', models.IntegerField(default=1)),
                ('f5001', models.IntegerField(default=1)),
                ('f5002', models.IntegerField(default=1)),
                ('f5003', models.IntegerField(default=1)),
                ('f5004', models.IntegerField(default=1)),
                ('f5005', models.CharField(max_length=200)),
                ('f5006', models.TextField()),
                ('f5007', models.IntegerField(default=1)),
                ('f5008', models.IntegerField(default=1)),
                ('f5009', models.TextField()),
                ('f5010', models.TextField()),
                ('f5011', models.CharField(max_length=200)),
                ('f5012', models.CharField(max_length=200)),
                ('f5013', models.TextField()),
                ('f5014', models.TextField()),
                ('f5015', models.TextField()),
                ('f5016', models.IntegerField(default=1)),
                ('f5017', models.TextField()),
                ('f5018', models.TextField()),
                ('f5019', models.IntegerField(default=1)),
                ('f5020', models.TextField()),
                ('f5021', models.TextField()),
                ('f5022', models.IntegerField(default=1)),
                ('f5023', models.IntegerField(default=1)),
                ('f5024', models.IntegerField(default=1)),
                ('f5025', models.CharField(max_length=200)),
                ('f5026', models.CharField(max_length=200)),
                ('f5027', models.CharField(max_length=200)),
                ('f5028', models.CharField(max_length=200)),
                ('f5029', models.TextField()),
                ('f5030', models.IntegerField(default=1)),
                ('f5031', models.IntegerField(default=1)),
                ('f5032', models.CharField(max_length=200)),
                ('f5033', models.CharField(max_length=200)),
                ('f5034', models.IntegerField(default=1)),
                ('f5035', models.IntegerField(default=1)),
                ('f5036', models.CharField(max_length=200)),
                ('f5037', models.IntegerField(default=1)),
                ('f5038', models.CharField(max_length=200)),
                ('f5039', models.CharField(max_length=200)),
                ('f5040', models.IntegerField(default=1)),
                ('f5041', models.CharField(max_length=200)),
                ('f5042', models.TextField()),
                ('f5043', models.CharField(max_length=200)),
                ('f5044', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M110',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5045', models.TextField()),
                ('f5046', models.TextField()),
                ('f5047', models.CharField(max_length=200)),
                ('f5048', models.TextField()),
                ('f5049', models.TextField()),
                ('f5050', models.CharField(max_length=200)),
                ('f5051', models.CharField(max_length=200)),
                ('f5052', models.IntegerField(default=1)),
                ('f5053', models.IntegerField(default=1)),
                ('f5054', models.TextField()),
                ('f5055', models.CharField(max_length=200)),
                ('f5056', models.TextField()),
                ('f5057', models.TextField()),
                ('f5058', models.IntegerField(default=1)),
                ('f5059', models.TextField()),
                ('f5060', models.IntegerField(default=1)),
                ('f5061', models.TextField()),
                ('f5062', models.CharField(max_length=200)),
                ('f5063', models.CharField(max_length=200)),
                ('f5064', models.CharField(max_length=200)),
                ('f5065', models.CharField(max_length=200)),
                ('f5066', models.IntegerField(default=1)),
                ('f5067', models.IntegerField(default=1)),
                ('f5068', models.CharField(max_length=200)),
                ('f5069', models.CharField(max_length=200)),
                ('f5070', models.IntegerField(default=1)),
                ('f5071', models.CharField(max_length=200)),
                ('f5072', models.IntegerField(default=1)),
                ('f5073', models.CharField(max_length=200)),
                ('f5074', models.TextField()),
                ('f5075', models.IntegerField(default=1)),
                ('f5076', models.TextField()),
                ('f5077', models.TextField()),
                ('f5078', models.CharField(max_length=200)),
                ('f5079', models.CharField(max_length=200)),
                ('f5080', models.CharField(max_length=200)),
                ('f5081', models.IntegerField(default=1)),
                ('f5082', models.TextField()),
                ('f5083', models.CharField(max_length=200)),
                ('f5084', models.IntegerField(default=1)),
                ('f5085', models.IntegerField(default=1)),
                ('f5086', models.CharField(max_length=200)),
                ('f5087', models.TextField()),
                ('f5088', models.TextField()),
                ('f5089', models.TextField()),
                ('f5090', models.CharField(max_length=200)),
                ('f5091', models.TextField()),
                ('f5092', models.TextField()),
                ('f5093', models.IntegerField(default=1)),
                ('f5094', models.IntegerField(default=1)),
                ('f5095', models.IntegerField(default=1)),
                ('f5096', models.TextField()),
                ('f5097', models.TextField()),
                ('f5098', models.CharField(max_length=200)),
                ('f5099', models.IntegerField(default=1)),
                ('f5100', models.CharField(max_length=200)),
                ('f5101', models.TextField()),
                ('f5102', models.IntegerField(default=1)),
                ('f5103', models.TextField()),
                ('f5104', models.TextField()),
                ('f5105', models.CharField(max_length=200)),
                ('f5106', models.CharField(max_length=200)),
                ('f5107', models.TextField()),
                ('f5108', models.TextField()),
                ('f5109', models.TextField()),
                ('f5110', models.IntegerField(default=1)),
                ('f5111', models.CharField(max_length=200)),
                ('f5112', models.IntegerField(default=1)),
                ('f5113', models.IntegerField(default=1)),
                ('f5114', models.CharField(max_length=200)),
                ('f5115', models.CharField(max_length=200)),
                ('f5116', models.TextField()),
                ('f5117', models.TextField()),
                ('f5118', models.IntegerField(default=1)),
                ('f5119', models.CharField(max_length=200)),
                ('f5120', models.IntegerField(default=1)),
                ('f5121', models.CharField(max_length=200)),
                ('f5122', models.CharField(max_length=200)),
                ('f5123', models.TextField()),
                ('f5124', models.TextField()),
                ('f5125', models.CharField(max_length=200)),
                ('f5126', models.CharField(max_length=200)),
                ('f5127', models.CharField(max_length=200)),
                ('f5128', models.CharField(max_length=200)),
                ('f5129', models.IntegerField(default=1)),
                ('f5130', models.TextField()),
                ('f5131', models.TextField()),
                ('f5132', models.CharField(max_length=200)),
                ('f5133', models.IntegerField(default=1)),
                ('f5134', models.CharField(max_length=200)),
            ],
        ),
    ]
