# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M61',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2857', models.CharField(max_length=200)),
                ('f2858', models.CharField(max_length=200)),
                ('f2859', models.CharField(max_length=200)),
                ('f2860', models.IntegerField(default=1)),
                ('f2861', models.IntegerField(default=1)),
                ('f2862', models.IntegerField(default=1)),
                ('f2863', models.TextField()),
                ('f2864', models.CharField(max_length=200)),
                ('f2865', models.CharField(max_length=200)),
                ('f2866', models.CharField(max_length=200)),
                ('f2867', models.CharField(max_length=200)),
                ('f2868', models.CharField(max_length=200)),
                ('f2869', models.IntegerField(default=1)),
                ('f2870', models.CharField(max_length=200)),
                ('f2871', models.IntegerField(default=1)),
                ('f2872', models.TextField()),
                ('f2873', models.IntegerField(default=1)),
                ('f2874', models.IntegerField(default=1)),
                ('f2875', models.CharField(max_length=200)),
                ('f2876', models.TextField()),
                ('f2877', models.CharField(max_length=200)),
                ('f2878', models.CharField(max_length=200)),
                ('f2879', models.TextField()),
                ('f2880', models.CharField(max_length=200)),
                ('f2881', models.CharField(max_length=200)),
                ('f2882', models.IntegerField(default=1)),
                ('f2883', models.TextField()),
                ('f2884', models.TextField()),
                ('f2885', models.TextField()),
                ('f2886', models.IntegerField(default=1)),
                ('f2887', models.IntegerField(default=1)),
                ('f2888', models.TextField()),
                ('f2889', models.TextField()),
                ('f2890', models.CharField(max_length=200)),
                ('f2891', models.IntegerField(default=1)),
                ('f2892', models.TextField()),
                ('f2893', models.TextField()),
                ('f2894', models.IntegerField(default=1)),
                ('f2895', models.CharField(max_length=200)),
                ('f2896', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M62',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2897', models.TextField()),
                ('f2898', models.TextField()),
                ('f2899', models.CharField(max_length=200)),
                ('f2900', models.IntegerField(default=1)),
                ('f2901', models.TextField()),
                ('f2902', models.TextField()),
                ('f2903', models.TextField()),
                ('f2904', models.TextField()),
                ('f2905', models.TextField()),
                ('f2906', models.IntegerField(default=1)),
                ('f2907', models.TextField()),
                ('f2908', models.CharField(max_length=200)),
                ('f2909', models.IntegerField(default=1)),
                ('f2910', models.CharField(max_length=200)),
                ('f2911', models.TextField()),
                ('f2912', models.CharField(max_length=200)),
                ('f2913', models.CharField(max_length=200)),
                ('f2914', models.TextField()),
                ('f2915', models.CharField(max_length=200)),
                ('f2916', models.TextField()),
                ('f2917', models.TextField()),
                ('f2918', models.IntegerField(default=1)),
                ('f2919', models.CharField(max_length=200)),
                ('f2920', models.TextField()),
                ('f2921', models.TextField()),
                ('f2922', models.IntegerField(default=1)),
                ('f2923', models.TextField()),
                ('f2924', models.IntegerField(default=1)),
                ('f2925', models.IntegerField(default=1)),
                ('f2926', models.CharField(max_length=200)),
                ('f2927', models.TextField()),
                ('f2928', models.IntegerField(default=1)),
                ('f2929', models.CharField(max_length=200)),
                ('f2930', models.IntegerField(default=1)),
                ('f2931', models.IntegerField(default=1)),
                ('f2932', models.TextField()),
                ('f2933', models.TextField()),
                ('f2934', models.IntegerField(default=1)),
                ('f2935', models.IntegerField(default=1)),
                ('f2936', models.IntegerField(default=1)),
                ('f2937', models.CharField(max_length=200)),
                ('f2938', models.TextField()),
                ('f2939', models.IntegerField(default=1)),
                ('f2940', models.TextField()),
                ('f2941', models.IntegerField(default=1)),
                ('f2942', models.IntegerField(default=1)),
                ('f2943', models.CharField(max_length=200)),
                ('f2944', models.TextField()),
                ('f2945', models.TextField()),
                ('f2946', models.TextField()),
                ('f2947', models.CharField(max_length=200)),
                ('f2948', models.TextField()),
                ('f2949', models.IntegerField(default=1)),
                ('f2950', models.IntegerField(default=1)),
                ('f2951', models.IntegerField(default=1)),
                ('f2952', models.CharField(max_length=200)),
                ('f2953', models.CharField(max_length=200)),
                ('f2954', models.TextField()),
                ('f2955', models.TextField()),
                ('f2956', models.CharField(max_length=200)),
                ('f2957', models.TextField()),
                ('f2958', models.IntegerField(default=1)),
                ('f2959', models.TextField()),
                ('f2960', models.IntegerField(default=1)),
                ('f2961', models.CharField(max_length=200)),
                ('f2962', models.CharField(max_length=200)),
                ('f2963', models.CharField(max_length=200)),
                ('f2964', models.CharField(max_length=200)),
                ('f2965', models.TextField()),
                ('f2966', models.IntegerField(default=1)),
                ('f2967', models.TextField()),
                ('f2968', models.IntegerField(default=1)),
                ('f2969', models.CharField(max_length=200)),
                ('f2970', models.CharField(max_length=200)),
                ('f2971', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M63',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2972', models.IntegerField(default=1)),
                ('f2973', models.TextField()),
                ('f2974', models.CharField(max_length=200)),
                ('f2975', models.TextField()),
                ('f2976', models.IntegerField(default=1)),
                ('f2977', models.CharField(max_length=200)),
                ('f2978', models.IntegerField(default=1)),
                ('f2979', models.CharField(max_length=200)),
                ('f2980', models.TextField()),
                ('f2981', models.TextField()),
                ('f2982', models.CharField(max_length=200)),
                ('f2983', models.CharField(max_length=200)),
                ('f2984', models.CharField(max_length=200)),
                ('f2985', models.TextField()),
                ('f2986', models.CharField(max_length=200)),
                ('f2987', models.IntegerField(default=1)),
                ('f2988', models.TextField()),
                ('f2989', models.CharField(max_length=200)),
                ('f2990', models.CharField(max_length=200)),
                ('f2991', models.TextField()),
                ('f2992', models.IntegerField(default=1)),
                ('f2993', models.CharField(max_length=200)),
                ('f2994', models.TextField()),
                ('f2995', models.TextField()),
                ('f2996', models.IntegerField(default=1)),
                ('f2997', models.IntegerField(default=1)),
                ('f2998', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M64',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2999', models.CharField(max_length=200)),
                ('f3000', models.IntegerField(default=1)),
                ('f3001', models.CharField(max_length=200)),
                ('f3002', models.IntegerField(default=1)),
                ('f3003', models.CharField(max_length=200)),
                ('f3004', models.CharField(max_length=200)),
                ('f3005', models.TextField()),
                ('f3006', models.CharField(max_length=200)),
                ('f3007', models.CharField(max_length=200)),
                ('f3008', models.CharField(max_length=200)),
                ('f3009', models.IntegerField(default=1)),
                ('f3010', models.IntegerField(default=1)),
                ('f3011', models.CharField(max_length=200)),
                ('f3012', models.TextField()),
                ('f3013', models.CharField(max_length=200)),
                ('f3014', models.TextField()),
                ('f3015', models.TextField()),
                ('f3016', models.CharField(max_length=200)),
                ('f3017', models.IntegerField(default=1)),
                ('f3018', models.CharField(max_length=200)),
                ('f3019', models.CharField(max_length=200)),
                ('f3020', models.TextField()),
                ('f3021', models.IntegerField(default=1)),
                ('f3022', models.TextField()),
                ('f3023', models.CharField(max_length=200)),
                ('f3024', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M65',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3025', models.TextField()),
                ('f3026', models.TextField()),
                ('f3027', models.CharField(max_length=200)),
                ('f3028', models.TextField()),
                ('f3029', models.TextField()),
                ('f3030', models.TextField()),
                ('f3031', models.IntegerField(default=1)),
                ('f3032', models.IntegerField(default=1)),
                ('f3033', models.IntegerField(default=1)),
                ('f3034', models.IntegerField(default=1)),
                ('f3035', models.CharField(max_length=200)),
                ('f3036', models.IntegerField(default=1)),
                ('f3037', models.TextField()),
                ('f3038', models.CharField(max_length=200)),
                ('f3039', models.TextField()),
                ('f3040', models.IntegerField(default=1)),
                ('f3041', models.IntegerField(default=1)),
                ('f3042', models.CharField(max_length=200)),
                ('f3043', models.CharField(max_length=200)),
                ('f3044', models.IntegerField(default=1)),
                ('f3045', models.CharField(max_length=200)),
                ('f3046', models.TextField()),
                ('f3047', models.TextField()),
                ('f3048', models.TextField()),
                ('f3049', models.CharField(max_length=200)),
                ('f3050', models.TextField()),
                ('f3051', models.IntegerField(default=1)),
                ('f3052', models.IntegerField(default=1)),
                ('f3053', models.CharField(max_length=200)),
                ('f3054', models.IntegerField(default=1)),
                ('f3055', models.IntegerField(default=1)),
                ('f3056', models.CharField(max_length=200)),
                ('f3057', models.CharField(max_length=200)),
                ('f3058', models.TextField()),
                ('f3059', models.TextField()),
                ('f3060', models.TextField()),
                ('f3061', models.IntegerField(default=1)),
                ('f3062', models.TextField()),
                ('f3063', models.TextField()),
                ('f3064', models.CharField(max_length=200)),
                ('f3065', models.IntegerField(default=1)),
                ('f3066', models.IntegerField(default=1)),
                ('f3067', models.CharField(max_length=200)),
                ('f3068', models.IntegerField(default=1)),
                ('f3069', models.IntegerField(default=1)),
                ('f3070', models.CharField(max_length=200)),
                ('f3071', models.IntegerField(default=1)),
                ('f3072', models.IntegerField(default=1)),
                ('f3073', models.IntegerField(default=1)),
                ('f3074', models.CharField(max_length=200)),
                ('f3075', models.IntegerField(default=1)),
                ('f3076', models.TextField()),
                ('f3077', models.CharField(max_length=200)),
                ('f3078', models.TextField()),
                ('f3079', models.TextField()),
                ('f3080', models.TextField()),
                ('f3081', models.IntegerField(default=1)),
                ('f3082', models.TextField()),
                ('f3083', models.IntegerField(default=1)),
                ('f3084', models.TextField()),
                ('f3085', models.CharField(max_length=200)),
                ('f3086', models.TextField()),
                ('f3087', models.CharField(max_length=200)),
                ('f3088', models.IntegerField(default=1)),
                ('f3089', models.IntegerField(default=1)),
                ('f3090', models.IntegerField(default=1)),
                ('f3091', models.TextField()),
                ('f3092', models.CharField(max_length=200)),
                ('f3093', models.TextField()),
                ('f3094', models.IntegerField(default=1)),
                ('f3095', models.TextField()),
                ('f3096', models.TextField()),
                ('f3097', models.CharField(max_length=200)),
                ('f3098', models.TextField()),
                ('f3099', models.IntegerField(default=1)),
                ('f3100', models.IntegerField(default=1)),
                ('f3101', models.CharField(max_length=200)),
                ('f3102', models.CharField(max_length=200)),
                ('f3103', models.IntegerField(default=1)),
                ('f3104', models.TextField()),
                ('f3105', models.CharField(max_length=200)),
                ('f3106', models.TextField()),
                ('f3107', models.IntegerField(default=1)),
                ('f3108', models.CharField(max_length=200)),
                ('f3109', models.TextField()),
                ('f3110', models.TextField()),
                ('f3111', models.IntegerField(default=1)),
                ('f3112', models.IntegerField(default=1)),
                ('f3113', models.IntegerField(default=1)),
                ('f3114', models.CharField(max_length=200)),
                ('f3115', models.IntegerField(default=1)),
                ('f3116', models.CharField(max_length=200)),
                ('f3117', models.CharField(max_length=200)),
                ('f3118', models.IntegerField(default=1)),
                ('f3119', models.TextField()),
                ('f3120', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M66',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3121', models.TextField()),
                ('f3122', models.CharField(max_length=200)),
                ('f3123', models.CharField(max_length=200)),
                ('f3124', models.TextField()),
                ('f3125', models.CharField(max_length=200)),
                ('f3126', models.IntegerField(default=1)),
                ('f3127', models.TextField()),
                ('f3128', models.TextField()),
                ('f3129', models.TextField()),
                ('f3130', models.TextField()),
                ('f3131', models.TextField()),
                ('f3132', models.TextField()),
                ('f3133', models.IntegerField(default=1)),
                ('f3134', models.TextField()),
                ('f3135', models.CharField(max_length=200)),
                ('f3136', models.CharField(max_length=200)),
                ('f3137', models.TextField()),
                ('f3138', models.CharField(max_length=200)),
                ('f3139', models.CharField(max_length=200)),
                ('f3140', models.CharField(max_length=200)),
                ('f3141', models.IntegerField(default=1)),
                ('f3142', models.CharField(max_length=200)),
                ('f3143', models.IntegerField(default=1)),
                ('f3144', models.CharField(max_length=200)),
                ('f3145', models.CharField(max_length=200)),
                ('f3146', models.CharField(max_length=200)),
                ('f3147', models.IntegerField(default=1)),
                ('f3148', models.IntegerField(default=1)),
                ('f3149', models.CharField(max_length=200)),
                ('f3150', models.CharField(max_length=200)),
                ('f3151', models.IntegerField(default=1)),
                ('f3152', models.TextField()),
                ('f3153', models.TextField()),
                ('f3154', models.TextField()),
                ('f3155', models.TextField()),
                ('f3156', models.CharField(max_length=200)),
                ('f3157', models.IntegerField(default=1)),
                ('f3158', models.CharField(max_length=200)),
                ('f3159', models.IntegerField(default=1)),
                ('f3160', models.CharField(max_length=200)),
                ('f3161', models.IntegerField(default=1)),
                ('f3162', models.CharField(max_length=200)),
                ('f3163', models.IntegerField(default=1)),
                ('f3164', models.CharField(max_length=200)),
                ('f3165', models.CharField(max_length=200)),
                ('f3166', models.IntegerField(default=1)),
                ('f3167', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M67',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3168', models.TextField()),
                ('f3169', models.IntegerField(default=1)),
                ('f3170', models.TextField()),
                ('f3171', models.CharField(max_length=200)),
                ('f3172', models.TextField()),
                ('f3173', models.IntegerField(default=1)),
                ('f3174', models.TextField()),
                ('f3175', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M68',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3176', models.TextField()),
                ('f3177', models.IntegerField(default=1)),
                ('f3178', models.TextField()),
                ('f3179', models.TextField()),
                ('f3180', models.IntegerField(default=1)),
                ('f3181', models.CharField(max_length=200)),
                ('f3182', models.IntegerField(default=1)),
                ('f3183', models.IntegerField(default=1)),
                ('f3184', models.CharField(max_length=200)),
                ('f3185', models.TextField()),
                ('f3186', models.CharField(max_length=200)),
                ('f3187', models.IntegerField(default=1)),
                ('f3188', models.CharField(max_length=200)),
                ('f3189', models.IntegerField(default=1)),
                ('f3190', models.IntegerField(default=1)),
                ('f3191', models.IntegerField(default=1)),
                ('f3192', models.CharField(max_length=200)),
                ('f3193', models.TextField()),
                ('f3194', models.IntegerField(default=1)),
                ('f3195', models.CharField(max_length=200)),
                ('f3196', models.TextField()),
                ('f3197', models.IntegerField(default=1)),
                ('f3198', models.TextField()),
                ('f3199', models.IntegerField(default=1)),
                ('f3200', models.TextField()),
                ('f3201', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M69',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3202', models.IntegerField(default=1)),
                ('f3203', models.IntegerField(default=1)),
                ('f3204', models.CharField(max_length=200)),
                ('f3205', models.IntegerField(default=1)),
                ('f3206', models.IntegerField(default=1)),
                ('f3207', models.CharField(max_length=200)),
                ('f3208', models.TextField()),
                ('f3209', models.IntegerField(default=1)),
                ('f3210', models.CharField(max_length=200)),
                ('f3211', models.IntegerField(default=1)),
                ('f3212', models.TextField()),
                ('f3213', models.CharField(max_length=200)),
                ('f3214', models.TextField()),
                ('f3215', models.IntegerField(default=1)),
                ('f3216', models.TextField()),
                ('f3217', models.CharField(max_length=200)),
                ('f3218', models.CharField(max_length=200)),
                ('f3219', models.CharField(max_length=200)),
                ('f3220', models.IntegerField(default=1)),
                ('f3221', models.CharField(max_length=200)),
                ('f3222', models.IntegerField(default=1)),
                ('f3223', models.CharField(max_length=200)),
                ('f3224', models.IntegerField(default=1)),
                ('f3225', models.TextField()),
                ('f3226', models.TextField()),
                ('f3227', models.TextField()),
                ('f3228', models.IntegerField(default=1)),
                ('f3229', models.IntegerField(default=1)),
                ('f3230', models.TextField()),
                ('f3231', models.IntegerField(default=1)),
                ('f3232', models.IntegerField(default=1)),
                ('f3233', models.CharField(max_length=200)),
                ('f3234', models.CharField(max_length=200)),
                ('f3235', models.CharField(max_length=200)),
                ('f3236', models.TextField()),
                ('f3237', models.CharField(max_length=200)),
                ('f3238', models.TextField()),
                ('f3239', models.IntegerField(default=1)),
                ('f3240', models.CharField(max_length=200)),
                ('f3241', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M70',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3242', models.TextField()),
                ('f3243', models.CharField(max_length=200)),
                ('f3244', models.IntegerField(default=1)),
                ('f3245', models.CharField(max_length=200)),
                ('f3246', models.IntegerField(default=1)),
                ('f3247', models.IntegerField(default=1)),
                ('f3248', models.CharField(max_length=200)),
                ('f3249', models.CharField(max_length=200)),
                ('f3250', models.TextField()),
                ('f3251', models.IntegerField(default=1)),
                ('f3252', models.TextField()),
                ('f3253', models.TextField()),
                ('f3254', models.CharField(max_length=200)),
                ('f3255', models.CharField(max_length=200)),
                ('f3256', models.TextField()),
                ('f3257', models.TextField()),
                ('f3258', models.TextField()),
                ('f3259', models.IntegerField(default=1)),
                ('f3260', models.CharField(max_length=200)),
                ('f3261', models.TextField()),
            ],
        ),
    ]
