# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M81',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3768', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M82',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3769', models.TextField()),
                ('f3770', models.TextField()),
                ('f3771', models.CharField(max_length=200)),
                ('f3772', models.CharField(max_length=200)),
                ('f3773', models.TextField()),
                ('f3774', models.IntegerField(default=1)),
                ('f3775', models.IntegerField(default=1)),
                ('f3776', models.TextField()),
                ('f3777', models.CharField(max_length=200)),
                ('f3778', models.IntegerField(default=1)),
                ('f3779', models.CharField(max_length=200)),
                ('f3780', models.CharField(max_length=200)),
                ('f3781', models.IntegerField(default=1)),
                ('f3782', models.IntegerField(default=1)),
                ('f3783', models.CharField(max_length=200)),
                ('f3784', models.CharField(max_length=200)),
                ('f3785', models.TextField()),
                ('f3786', models.TextField()),
                ('f3787', models.TextField()),
                ('f3788', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M83',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3789', models.IntegerField(default=1)),
                ('f3790', models.CharField(max_length=200)),
                ('f3791', models.CharField(max_length=200)),
                ('f3792', models.TextField()),
                ('f3793', models.TextField()),
                ('f3794', models.CharField(max_length=200)),
                ('f3795', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M84',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3796', models.TextField()),
                ('f3797', models.CharField(max_length=200)),
                ('f3798', models.TextField()),
                ('f3799', models.CharField(max_length=200)),
                ('f3800', models.IntegerField(default=1)),
                ('f3801', models.CharField(max_length=200)),
                ('f3802', models.CharField(max_length=200)),
                ('f3803', models.IntegerField(default=1)),
                ('f3804', models.TextField()),
                ('f3805', models.TextField()),
                ('f3806', models.IntegerField(default=1)),
                ('f3807', models.CharField(max_length=200)),
                ('f3808', models.TextField()),
                ('f3809', models.IntegerField(default=1)),
                ('f3810', models.CharField(max_length=200)),
                ('f3811', models.CharField(max_length=200)),
                ('f3812', models.CharField(max_length=200)),
                ('f3813', models.TextField()),
                ('f3814', models.IntegerField(default=1)),
                ('f3815', models.TextField()),
                ('f3816', models.CharField(max_length=200)),
                ('f3817', models.IntegerField(default=1)),
                ('f3818', models.TextField()),
                ('f3819', models.IntegerField(default=1)),
                ('f3820', models.TextField()),
                ('f3821', models.IntegerField(default=1)),
                ('f3822', models.TextField()),
                ('f3823', models.CharField(max_length=200)),
                ('f3824', models.CharField(max_length=200)),
                ('f3825', models.TextField()),
                ('f3826', models.IntegerField(default=1)),
                ('f3827', models.TextField()),
                ('f3828', models.IntegerField(default=1)),
                ('f3829', models.CharField(max_length=200)),
                ('f3830', models.TextField()),
                ('f3831', models.IntegerField(default=1)),
                ('f3832', models.TextField()),
                ('f3833', models.IntegerField(default=1)),
                ('f3834', models.IntegerField(default=1)),
                ('f3835', models.CharField(max_length=200)),
                ('f3836', models.CharField(max_length=200)),
                ('f3837', models.IntegerField(default=1)),
                ('f3838', models.CharField(max_length=200)),
                ('f3839', models.TextField()),
                ('f3840', models.TextField()),
                ('f3841', models.IntegerField(default=1)),
                ('f3842', models.IntegerField(default=1)),
                ('f3843', models.CharField(max_length=200)),
                ('f3844', models.CharField(max_length=200)),
                ('f3845', models.CharField(max_length=200)),
                ('f3846', models.CharField(max_length=200)),
                ('f3847', models.IntegerField(default=1)),
                ('f3848', models.IntegerField(default=1)),
                ('f3849', models.TextField()),
                ('f3850', models.CharField(max_length=200)),
                ('f3851', models.TextField()),
                ('f3852', models.TextField()),
                ('f3853', models.CharField(max_length=200)),
                ('f3854', models.CharField(max_length=200)),
                ('f3855', models.IntegerField(default=1)),
                ('f3856', models.CharField(max_length=200)),
                ('f3857', models.CharField(max_length=200)),
                ('f3858', models.TextField()),
                ('f3859', models.TextField()),
                ('f3860', models.CharField(max_length=200)),
                ('f3861', models.CharField(max_length=200)),
                ('f3862', models.IntegerField(default=1)),
                ('f3863', models.IntegerField(default=1)),
                ('f3864', models.IntegerField(default=1)),
                ('f3865', models.CharField(max_length=200)),
                ('f3866', models.CharField(max_length=200)),
                ('f3867', models.CharField(max_length=200)),
                ('f3868', models.TextField()),
                ('f3869', models.IntegerField(default=1)),
                ('f3870', models.TextField()),
                ('f3871', models.TextField()),
                ('f3872', models.IntegerField(default=1)),
                ('f3873', models.TextField()),
                ('f3874', models.IntegerField(default=1)),
                ('f3875', models.CharField(max_length=200)),
                ('f3876', models.IntegerField(default=1)),
                ('f3877', models.TextField()),
                ('f3878', models.TextField()),
                ('f3879', models.CharField(max_length=200)),
                ('f3880', models.IntegerField(default=1)),
                ('f3881', models.CharField(max_length=200)),
                ('f3882', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M85',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3883', models.CharField(max_length=200)),
                ('f3884', models.IntegerField(default=1)),
                ('f3885', models.TextField()),
                ('f3886', models.CharField(max_length=200)),
                ('f3887', models.CharField(max_length=200)),
                ('f3888', models.TextField()),
                ('f3889', models.TextField()),
                ('f3890', models.IntegerField(default=1)),
                ('f3891', models.TextField()),
                ('f3892', models.IntegerField(default=1)),
                ('f3893', models.TextField()),
                ('f3894', models.TextField()),
                ('f3895', models.IntegerField(default=1)),
                ('f3896', models.CharField(max_length=200)),
                ('f3897', models.CharField(max_length=200)),
                ('f3898', models.CharField(max_length=200)),
                ('f3899', models.CharField(max_length=200)),
                ('f3900', models.TextField()),
                ('f3901', models.IntegerField(default=1)),
                ('f3902', models.IntegerField(default=1)),
                ('f3903', models.IntegerField(default=1)),
                ('f3904', models.CharField(max_length=200)),
                ('f3905', models.IntegerField(default=1)),
                ('f3906', models.IntegerField(default=1)),
                ('f3907', models.CharField(max_length=200)),
                ('f3908', models.TextField()),
                ('f3909', models.CharField(max_length=200)),
                ('f3910', models.TextField()),
                ('f3911', models.TextField()),
                ('f3912', models.TextField()),
                ('f3913', models.TextField()),
                ('f3914', models.IntegerField(default=1)),
                ('f3915', models.TextField()),
                ('f3916', models.IntegerField(default=1)),
                ('f3917', models.CharField(max_length=200)),
                ('f3918', models.IntegerField(default=1)),
                ('f3919', models.IntegerField(default=1)),
                ('f3920', models.CharField(max_length=200)),
                ('f3921', models.CharField(max_length=200)),
                ('f3922', models.CharField(max_length=200)),
                ('f3923', models.CharField(max_length=200)),
                ('f3924', models.IntegerField(default=1)),
                ('f3925', models.TextField()),
                ('f3926', models.IntegerField(default=1)),
                ('f3927', models.CharField(max_length=200)),
                ('f3928', models.CharField(max_length=200)),
                ('f3929', models.CharField(max_length=200)),
                ('f3930', models.IntegerField(default=1)),
                ('f3931', models.IntegerField(default=1)),
                ('f3932', models.TextField()),
                ('f3933', models.TextField()),
                ('f3934', models.CharField(max_length=200)),
                ('f3935', models.IntegerField(default=1)),
                ('f3936', models.TextField()),
                ('f3937', models.CharField(max_length=200)),
                ('f3938', models.CharField(max_length=200)),
                ('f3939', models.TextField()),
                ('f3940', models.CharField(max_length=200)),
                ('f3941', models.CharField(max_length=200)),
                ('f3942', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M86',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f3943', models.CharField(max_length=200)),
                ('f3944', models.CharField(max_length=200)),
                ('f3945', models.CharField(max_length=200)),
                ('f3946', models.CharField(max_length=200)),
                ('f3947', models.IntegerField(default=1)),
                ('f3948', models.CharField(max_length=200)),
                ('f3949', models.IntegerField(default=1)),
                ('f3950', models.IntegerField(default=1)),
                ('f3951', models.CharField(max_length=200)),
                ('f3952', models.CharField(max_length=200)),
                ('f3953', models.TextField()),
                ('f3954', models.CharField(max_length=200)),
                ('f3955', models.TextField()),
                ('f3956', models.TextField()),
                ('f3957', models.TextField()),
                ('f3958', models.TextField()),
                ('f3959', models.TextField()),
                ('f3960', models.TextField()),
                ('f3961', models.CharField(max_length=200)),
                ('f3962', models.TextField()),
                ('f3963', models.CharField(max_length=200)),
                ('f3964', models.IntegerField(default=1)),
                ('f3965', models.TextField()),
                ('f3966', models.TextField()),
                ('f3967', models.TextField()),
                ('f3968', models.TextField()),
                ('f3969', models.TextField()),
                ('f3970', models.CharField(max_length=200)),
                ('f3971', models.CharField(max_length=200)),
                ('f3972', models.TextField()),
                ('f3973', models.IntegerField(default=1)),
                ('f3974', models.IntegerField(default=1)),
                ('f3975', models.IntegerField(default=1)),
                ('f3976', models.TextField()),
                ('f3977', models.CharField(max_length=200)),
                ('f3978', models.TextField()),
                ('f3979', models.IntegerField(default=1)),
                ('f3980', models.IntegerField(default=1)),
                ('f3981', models.CharField(max_length=200)),
                ('f3982', models.IntegerField(default=1)),
                ('f3983', models.TextField()),
                ('f3984', models.CharField(max_length=200)),
                ('f3985', models.TextField()),
                ('f3986', models.TextField()),
                ('f3987', models.CharField(max_length=200)),
                ('f3988', models.TextField()),
                ('f3989', models.IntegerField(default=1)),
                ('f3990', models.TextField()),
                ('f3991', models.TextField()),
                ('f3992', models.IntegerField(default=1)),
                ('f3993', models.TextField()),
                ('f3994', models.TextField()),
                ('f3995', models.CharField(max_length=200)),
                ('f3996', models.IntegerField(default=1)),
                ('f3997', models.CharField(max_length=200)),
                ('f3998', models.CharField(max_length=200)),
                ('f3999', models.IntegerField(default=1)),
                ('f4000', models.TextField()),
                ('f4001', models.CharField(max_length=200)),
                ('f4002', models.TextField()),
                ('f4003', models.CharField(max_length=200)),
                ('f4004', models.TextField()),
                ('f4005', models.IntegerField(default=1)),
                ('f4006', models.IntegerField(default=1)),
                ('f4007', models.CharField(max_length=200)),
                ('f4008', models.IntegerField(default=1)),
                ('f4009', models.IntegerField(default=1)),
                ('f4010', models.TextField()),
                ('f4011', models.IntegerField(default=1)),
                ('f4012', models.TextField()),
                ('f4013', models.CharField(max_length=200)),
                ('f4014', models.IntegerField(default=1)),
                ('f4015', models.CharField(max_length=200)),
                ('f4016', models.IntegerField(default=1)),
                ('f4017', models.IntegerField(default=1)),
                ('f4018', models.TextField()),
                ('f4019', models.IntegerField(default=1)),
                ('f4020', models.CharField(max_length=200)),
                ('f4021', models.CharField(max_length=200)),
                ('f4022', models.CharField(max_length=200)),
                ('f4023', models.IntegerField(default=1)),
                ('f4024', models.IntegerField(default=1)),
                ('f4025', models.IntegerField(default=1)),
                ('f4026', models.CharField(max_length=200)),
                ('f4027', models.IntegerField(default=1)),
                ('f4028', models.TextField()),
                ('f4029', models.TextField()),
                ('f4030', models.CharField(max_length=200)),
                ('f4031', models.TextField()),
                ('f4032', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M87',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4033', models.IntegerField(default=1)),
                ('f4034', models.TextField()),
                ('f4035', models.CharField(max_length=200)),
                ('f4036', models.CharField(max_length=200)),
                ('f4037', models.TextField()),
                ('f4038', models.TextField()),
                ('f4039', models.TextField()),
                ('f4040', models.CharField(max_length=200)),
                ('f4041', models.IntegerField(default=1)),
                ('f4042', models.TextField()),
                ('f4043', models.CharField(max_length=200)),
                ('f4044', models.CharField(max_length=200)),
                ('f4045', models.IntegerField(default=1)),
                ('f4046', models.IntegerField(default=1)),
                ('f4047', models.CharField(max_length=200)),
                ('f4048', models.TextField()),
                ('f4049', models.CharField(max_length=200)),
                ('f4050', models.TextField()),
                ('f4051', models.IntegerField(default=1)),
                ('f4052', models.TextField()),
                ('f4053', models.CharField(max_length=200)),
                ('f4054', models.TextField()),
                ('f4055', models.CharField(max_length=200)),
                ('f4056', models.TextField()),
                ('f4057', models.TextField()),
                ('f4058', models.TextField()),
                ('f4059', models.CharField(max_length=200)),
                ('f4060', models.IntegerField(default=1)),
                ('f4061', models.CharField(max_length=200)),
                ('f4062', models.TextField()),
                ('f4063', models.CharField(max_length=200)),
                ('f4064', models.IntegerField(default=1)),
                ('f4065', models.CharField(max_length=200)),
                ('f4066', models.CharField(max_length=200)),
                ('f4067', models.TextField()),
                ('f4068', models.CharField(max_length=200)),
                ('f4069', models.TextField()),
                ('f4070', models.CharField(max_length=200)),
                ('f4071', models.IntegerField(default=1)),
                ('f4072', models.CharField(max_length=200)),
                ('f4073', models.IntegerField(default=1)),
                ('f4074', models.TextField()),
                ('f4075', models.IntegerField(default=1)),
                ('f4076', models.CharField(max_length=200)),
                ('f4077', models.CharField(max_length=200)),
                ('f4078', models.CharField(max_length=200)),
                ('f4079', models.CharField(max_length=200)),
                ('f4080', models.CharField(max_length=200)),
                ('f4081', models.TextField()),
                ('f4082', models.CharField(max_length=200)),
                ('f4083', models.CharField(max_length=200)),
                ('f4084', models.TextField()),
                ('f4085', models.CharField(max_length=200)),
                ('f4086', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M88',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4087', models.TextField()),
                ('f4088', models.IntegerField(default=1)),
                ('f4089', models.TextField()),
                ('f4090', models.CharField(max_length=200)),
                ('f4091', models.IntegerField(default=1)),
                ('f4092', models.CharField(max_length=200)),
                ('f4093', models.CharField(max_length=200)),
                ('f4094', models.CharField(max_length=200)),
                ('f4095', models.IntegerField(default=1)),
                ('f4096', models.CharField(max_length=200)),
                ('f4097', models.CharField(max_length=200)),
                ('f4098', models.IntegerField(default=1)),
                ('f4099', models.IntegerField(default=1)),
                ('f4100', models.TextField()),
                ('f4101', models.TextField()),
                ('f4102', models.CharField(max_length=200)),
                ('f4103', models.IntegerField(default=1)),
                ('f4104', models.TextField()),
                ('f4105', models.TextField()),
                ('f4106', models.TextField()),
                ('f4107', models.CharField(max_length=200)),
                ('f4108', models.TextField()),
                ('f4109', models.IntegerField(default=1)),
                ('f4110', models.CharField(max_length=200)),
                ('f4111', models.IntegerField(default=1)),
                ('f4112', models.TextField()),
                ('f4113', models.IntegerField(default=1)),
                ('f4114', models.IntegerField(default=1)),
                ('f4115', models.TextField()),
                ('f4116', models.TextField()),
                ('f4117', models.IntegerField(default=1)),
                ('f4118', models.CharField(max_length=200)),
                ('f4119', models.TextField()),
                ('f4120', models.TextField()),
                ('f4121', models.TextField()),
                ('f4122', models.TextField()),
                ('f4123', models.IntegerField(default=1)),
                ('f4124', models.IntegerField(default=1)),
                ('f4125', models.IntegerField(default=1)),
                ('f4126', models.CharField(max_length=200)),
                ('f4127', models.TextField()),
                ('f4128', models.CharField(max_length=200)),
                ('f4129', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M89',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4130', models.IntegerField(default=1)),
                ('f4131', models.IntegerField(default=1)),
                ('f4132', models.IntegerField(default=1)),
                ('f4133', models.CharField(max_length=200)),
                ('f4134', models.IntegerField(default=1)),
                ('f4135', models.CharField(max_length=200)),
                ('f4136', models.TextField()),
                ('f4137', models.CharField(max_length=200)),
                ('f4138', models.CharField(max_length=200)),
                ('f4139', models.IntegerField(default=1)),
                ('f4140', models.TextField()),
                ('f4141', models.CharField(max_length=200)),
                ('f4142', models.TextField()),
                ('f4143', models.IntegerField(default=1)),
                ('f4144', models.TextField()),
                ('f4145', models.TextField()),
                ('f4146', models.IntegerField(default=1)),
                ('f4147', models.IntegerField(default=1)),
                ('f4148', models.IntegerField(default=1)),
                ('f4149', models.TextField()),
                ('f4150', models.IntegerField(default=1)),
                ('f4151', models.CharField(max_length=200)),
                ('f4152', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M90',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f4153', models.CharField(max_length=200)),
                ('f4154', models.CharField(max_length=200)),
                ('f4155', models.IntegerField(default=1)),
                ('f4156', models.TextField()),
                ('f4157', models.CharField(max_length=200)),
                ('f4158', models.TextField()),
                ('f4159', models.TextField()),
                ('f4160', models.TextField()),
                ('f4161', models.CharField(max_length=200)),
                ('f4162', models.TextField()),
                ('f4163', models.IntegerField(default=1)),
                ('f4164', models.TextField()),
                ('f4165', models.TextField()),
                ('f4166', models.IntegerField(default=1)),
                ('f4167', models.CharField(max_length=200)),
                ('f4168', models.IntegerField(default=1)),
                ('f4169', models.IntegerField(default=1)),
                ('f4170', models.IntegerField(default=1)),
                ('f4171', models.IntegerField(default=1)),
                ('f4172', models.TextField()),
                ('f4173', models.CharField(max_length=200)),
                ('f4174', models.CharField(max_length=200)),
                ('f4175', models.CharField(max_length=200)),
                ('f4176', models.TextField()),
                ('f4177', models.CharField(max_length=200)),
                ('f4178', models.TextField()),
                ('f4179', models.IntegerField(default=1)),
                ('f4180', models.CharField(max_length=200)),
                ('f4181', models.TextField()),
                ('f4182', models.TextField()),
                ('f4183', models.CharField(max_length=200)),
                ('f4184', models.CharField(max_length=200)),
                ('f4185', models.CharField(max_length=200)),
                ('f4186', models.CharField(max_length=200)),
                ('f4187', models.TextField()),
                ('f4188', models.TextField()),
                ('f4189', models.CharField(max_length=200)),
                ('f4190', models.CharField(max_length=200)),
                ('f4191', models.CharField(max_length=200)),
                ('f4192', models.TextField()),
                ('f4193', models.IntegerField(default=1)),
                ('f4194', models.TextField()),
                ('f4195', models.IntegerField(default=1)),
                ('f4196', models.IntegerField(default=1)),
                ('f4197', models.TextField()),
                ('f4198', models.IntegerField(default=1)),
                ('f4199', models.IntegerField(default=1)),
                ('f4200', models.CharField(max_length=200)),
                ('f4201', models.CharField(max_length=200)),
                ('f4202', models.IntegerField(default=1)),
                ('f4203', models.IntegerField(default=1)),
                ('f4204', models.CharField(max_length=200)),
                ('f4205', models.TextField()),
                ('f4206', models.TextField()),
                ('f4207', models.CharField(max_length=200)),
                ('f4208', models.IntegerField(default=1)),
                ('f4209', models.CharField(max_length=200)),
                ('f4210', models.TextField()),
                ('f4211', models.IntegerField(default=1)),
                ('f4212', models.TextField()),
                ('f4213', models.IntegerField(default=1)),
                ('f4214', models.IntegerField(default=1)),
                ('f4215', models.TextField()),
                ('f4216', models.CharField(max_length=200)),
                ('f4217', models.TextField()),
                ('f4218', models.TextField()),
                ('f4219', models.TextField()),
                ('f4220', models.CharField(max_length=200)),
                ('f4221', models.CharField(max_length=200)),
                ('f4222', models.CharField(max_length=200)),
                ('f4223', models.IntegerField(default=1)),
                ('f4224', models.IntegerField(default=1)),
                ('f4225', models.CharField(max_length=200)),
                ('f4226', models.TextField()),
                ('f4227', models.IntegerField(default=1)),
                ('f4228', models.TextField()),
                ('f4229', models.CharField(max_length=200)),
                ('f4230', models.TextField()),
                ('f4231', models.IntegerField(default=1)),
                ('f4232', models.CharField(max_length=200)),
                ('f4233', models.IntegerField(default=1)),
                ('f4234', models.CharField(max_length=200)),
                ('f4235', models.CharField(max_length=200)),
                ('f4236', models.IntegerField(default=1)),
                ('f4237', models.IntegerField(default=1)),
                ('f4238', models.IntegerField(default=1)),
                ('f4239', models.TextField()),
                ('f4240', models.TextField()),
                ('f4241', models.CharField(max_length=200)),
            ],
        ),
    ]
