# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M121',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5689', models.TextField()),
                ('f5690', models.TextField()),
                ('f5691', models.CharField(max_length=200)),
                ('f5692', models.TextField()),
                ('f5693', models.IntegerField(default=1)),
                ('f5694', models.TextField()),
                ('f5695', models.TextField()),
                ('f5696', models.IntegerField(default=1)),
                ('f5697', models.TextField()),
                ('f5698', models.TextField()),
                ('f5699', models.TextField()),
                ('f5700', models.TextField()),
                ('f5701', models.TextField()),
                ('f5702', models.IntegerField(default=1)),
                ('f5703', models.IntegerField(default=1)),
                ('f5704', models.TextField()),
                ('f5705', models.CharField(max_length=200)),
                ('f5706', models.IntegerField(default=1)),
                ('f5707', models.CharField(max_length=200)),
                ('f5708', models.IntegerField(default=1)),
                ('f5709', models.CharField(max_length=200)),
                ('f5710', models.TextField()),
                ('f5711', models.CharField(max_length=200)),
                ('f5712', models.IntegerField(default=1)),
                ('f5713', models.TextField()),
                ('f5714', models.IntegerField(default=1)),
                ('f5715', models.CharField(max_length=200)),
                ('f5716', models.IntegerField(default=1)),
                ('f5717', models.CharField(max_length=200)),
                ('f5718', models.TextField()),
                ('f5719', models.TextField()),
                ('f5720', models.CharField(max_length=200)),
                ('f5721', models.TextField()),
                ('f5722', models.CharField(max_length=200)),
                ('f5723', models.CharField(max_length=200)),
                ('f5724', models.TextField()),
                ('f5725', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M122',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5726', models.CharField(max_length=200)),
                ('f5727', models.IntegerField(default=1)),
                ('f5728', models.TextField()),
                ('f5729', models.TextField()),
                ('f5730', models.IntegerField(default=1)),
                ('f5731', models.CharField(max_length=200)),
                ('f5732', models.CharField(max_length=200)),
                ('f5733', models.IntegerField(default=1)),
                ('f5734', models.CharField(max_length=200)),
                ('f5735', models.CharField(max_length=200)),
                ('f5736', models.CharField(max_length=200)),
                ('f5737', models.CharField(max_length=200)),
                ('f5738', models.TextField()),
                ('f5739', models.IntegerField(default=1)),
                ('f5740', models.IntegerField(default=1)),
                ('f5741', models.TextField()),
                ('f5742', models.TextField()),
                ('f5743', models.TextField()),
                ('f5744', models.IntegerField(default=1)),
                ('f5745', models.IntegerField(default=1)),
                ('f5746', models.TextField()),
                ('f5747', models.TextField()),
                ('f5748', models.CharField(max_length=200)),
                ('f5749', models.TextField()),
                ('f5750', models.TextField()),
                ('f5751', models.IntegerField(default=1)),
                ('f5752', models.CharField(max_length=200)),
                ('f5753', models.IntegerField(default=1)),
                ('f5754', models.CharField(max_length=200)),
                ('f5755', models.IntegerField(default=1)),
                ('f5756', models.TextField()),
                ('f5757', models.TextField()),
                ('f5758', models.CharField(max_length=200)),
                ('f5759', models.CharField(max_length=200)),
                ('f5760', models.CharField(max_length=200)),
                ('f5761', models.IntegerField(default=1)),
                ('f5762', models.CharField(max_length=200)),
                ('f5763', models.TextField()),
                ('f5764', models.IntegerField(default=1)),
                ('f5765', models.IntegerField(default=1)),
                ('f5766', models.IntegerField(default=1)),
                ('f5767', models.IntegerField(default=1)),
                ('f5768', models.TextField()),
                ('f5769', models.CharField(max_length=200)),
                ('f5770', models.TextField()),
                ('f5771', models.TextField()),
                ('f5772', models.TextField()),
                ('f5773', models.TextField()),
                ('f5774', models.IntegerField(default=1)),
                ('f5775', models.IntegerField(default=1)),
                ('f5776', models.IntegerField(default=1)),
                ('f5777', models.TextField()),
                ('f5778', models.CharField(max_length=200)),
                ('f5779', models.IntegerField(default=1)),
                ('f5780', models.TextField()),
                ('f5781', models.TextField()),
                ('f5782', models.IntegerField(default=1)),
                ('f5783', models.IntegerField(default=1)),
                ('f5784', models.CharField(max_length=200)),
                ('f5785', models.TextField()),
                ('f5786', models.CharField(max_length=200)),
                ('f5787', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M123',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5788', models.TextField()),
                ('f5789', models.CharField(max_length=200)),
                ('f5790', models.TextField()),
                ('f5791', models.CharField(max_length=200)),
                ('f5792', models.TextField()),
                ('f5793', models.CharField(max_length=200)),
                ('f5794', models.TextField()),
                ('f5795', models.TextField()),
                ('f5796', models.CharField(max_length=200)),
                ('f5797', models.IntegerField(default=1)),
                ('f5798', models.CharField(max_length=200)),
                ('f5799', models.IntegerField(default=1)),
                ('f5800', models.TextField()),
                ('f5801', models.TextField()),
                ('f5802', models.TextField()),
                ('f5803', models.CharField(max_length=200)),
                ('f5804', models.TextField()),
                ('f5805', models.TextField()),
                ('f5806', models.TextField()),
                ('f5807', models.TextField()),
                ('f5808', models.TextField()),
                ('f5809', models.CharField(max_length=200)),
                ('f5810', models.TextField()),
                ('f5811', models.TextField()),
                ('f5812', models.CharField(max_length=200)),
                ('f5813', models.IntegerField(default=1)),
                ('f5814', models.IntegerField(default=1)),
                ('f5815', models.TextField()),
                ('f5816', models.CharField(max_length=200)),
                ('f5817', models.TextField()),
                ('f5818', models.TextField()),
                ('f5819', models.CharField(max_length=200)),
                ('f5820', models.CharField(max_length=200)),
                ('f5821', models.TextField()),
                ('f5822', models.CharField(max_length=200)),
                ('f5823', models.IntegerField(default=1)),
                ('f5824', models.TextField()),
                ('f5825', models.TextField()),
                ('f5826', models.IntegerField(default=1)),
                ('f5827', models.TextField()),
                ('f5828', models.TextField()),
                ('f5829', models.CharField(max_length=200)),
                ('f5830', models.TextField()),
                ('f5831', models.CharField(max_length=200)),
                ('f5832', models.IntegerField(default=1)),
                ('f5833', models.IntegerField(default=1)),
                ('f5834', models.TextField()),
                ('f5835', models.IntegerField(default=1)),
                ('f5836', models.CharField(max_length=200)),
                ('f5837', models.IntegerField(default=1)),
                ('f5838', models.CharField(max_length=200)),
                ('f5839', models.CharField(max_length=200)),
                ('f5840', models.IntegerField(default=1)),
                ('f5841', models.TextField()),
                ('f5842', models.IntegerField(default=1)),
                ('f5843', models.CharField(max_length=200)),
                ('f5844', models.TextField()),
                ('f5845', models.CharField(max_length=200)),
                ('f5846', models.TextField()),
                ('f5847', models.CharField(max_length=200)),
                ('f5848', models.IntegerField(default=1)),
                ('f5849', models.IntegerField(default=1)),
                ('f5850', models.IntegerField(default=1)),
                ('f5851', models.IntegerField(default=1)),
                ('f5852', models.IntegerField(default=1)),
                ('f5853', models.IntegerField(default=1)),
                ('f5854', models.CharField(max_length=200)),
                ('f5855', models.CharField(max_length=200)),
                ('f5856', models.CharField(max_length=200)),
                ('f5857', models.CharField(max_length=200)),
                ('f5858', models.TextField()),
                ('f5859', models.IntegerField(default=1)),
                ('f5860', models.IntegerField(default=1)),
                ('f5861', models.CharField(max_length=200)),
                ('f5862', models.IntegerField(default=1)),
                ('f5863', models.CharField(max_length=200)),
                ('f5864', models.CharField(max_length=200)),
                ('f5865', models.CharField(max_length=200)),
                ('f5866', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M124',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5867', models.TextField()),
                ('f5868', models.CharField(max_length=200)),
                ('f5869', models.IntegerField(default=1)),
                ('f5870', models.CharField(max_length=200)),
                ('f5871', models.TextField()),
                ('f5872', models.TextField()),
                ('f5873', models.TextField()),
                ('f5874', models.CharField(max_length=200)),
                ('f5875', models.IntegerField(default=1)),
                ('f5876', models.TextField()),
                ('f5877', models.TextField()),
                ('f5878', models.IntegerField(default=1)),
                ('f5879', models.CharField(max_length=200)),
                ('f5880', models.TextField()),
                ('f5881', models.IntegerField(default=1)),
                ('f5882', models.TextField()),
                ('f5883', models.CharField(max_length=200)),
                ('f5884', models.IntegerField(default=1)),
                ('f5885', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M125',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5886', models.TextField()),
                ('f5887', models.CharField(max_length=200)),
                ('f5888', models.IntegerField(default=1)),
                ('f5889', models.TextField()),
                ('f5890', models.TextField()),
                ('f5891', models.CharField(max_length=200)),
                ('f5892', models.CharField(max_length=200)),
                ('f5893', models.TextField()),
                ('f5894', models.CharField(max_length=200)),
                ('f5895', models.TextField()),
                ('f5896', models.TextField()),
                ('f5897', models.IntegerField(default=1)),
                ('f5898', models.CharField(max_length=200)),
                ('f5899', models.CharField(max_length=200)),
                ('f5900', models.IntegerField(default=1)),
                ('f5901', models.IntegerField(default=1)),
                ('f5902', models.IntegerField(default=1)),
                ('f5903', models.IntegerField(default=1)),
                ('f5904', models.IntegerField(default=1)),
                ('f5905', models.TextField()),
                ('f5906', models.TextField()),
                ('f5907', models.TextField()),
                ('f5908', models.CharField(max_length=200)),
                ('f5909', models.IntegerField(default=1)),
                ('f5910', models.IntegerField(default=1)),
                ('f5911', models.CharField(max_length=200)),
                ('f5912', models.CharField(max_length=200)),
                ('f5913', models.TextField()),
                ('f5914', models.TextField()),
                ('f5915', models.IntegerField(default=1)),
                ('f5916', models.TextField()),
                ('f5917', models.CharField(max_length=200)),
                ('f5918', models.IntegerField(default=1)),
                ('f5919', models.IntegerField(default=1)),
                ('f5920', models.TextField()),
                ('f5921', models.TextField()),
                ('f5922', models.IntegerField(default=1)),
                ('f5923', models.CharField(max_length=200)),
                ('f5924', models.TextField()),
                ('f5925', models.IntegerField(default=1)),
                ('f5926', models.CharField(max_length=200)),
                ('f5927', models.IntegerField(default=1)),
                ('f5928', models.TextField()),
                ('f5929', models.IntegerField(default=1)),
                ('f5930', models.IntegerField(default=1)),
                ('f5931', models.CharField(max_length=200)),
                ('f5932', models.IntegerField(default=1)),
                ('f5933', models.CharField(max_length=200)),
                ('f5934', models.CharField(max_length=200)),
                ('f5935', models.IntegerField(default=1)),
                ('f5936', models.TextField()),
                ('f5937', models.TextField()),
                ('f5938', models.CharField(max_length=200)),
                ('f5939', models.IntegerField(default=1)),
                ('f5940', models.CharField(max_length=200)),
                ('f5941', models.IntegerField(default=1)),
                ('f5942', models.IntegerField(default=1)),
                ('f5943', models.TextField()),
                ('f5944', models.CharField(max_length=200)),
                ('f5945', models.TextField()),
                ('f5946', models.TextField()),
                ('f5947', models.IntegerField(default=1)),
                ('f5948', models.TextField()),
                ('f5949', models.TextField()),
                ('f5950', models.CharField(max_length=200)),
                ('f5951', models.CharField(max_length=200)),
                ('f5952', models.CharField(max_length=200)),
                ('f5953', models.CharField(max_length=200)),
                ('f5954', models.CharField(max_length=200)),
                ('f5955', models.IntegerField(default=1)),
                ('f5956', models.CharField(max_length=200)),
                ('f5957', models.TextField()),
                ('f5958', models.CharField(max_length=200)),
                ('f5959', models.TextField()),
                ('f5960', models.CharField(max_length=200)),
                ('f5961', models.CharField(max_length=200)),
                ('f5962', models.CharField(max_length=200)),
                ('f5963', models.TextField()),
                ('f5964', models.TextField()),
                ('f5965', models.IntegerField(default=1)),
                ('f5966', models.TextField()),
                ('f5967', models.IntegerField(default=1)),
                ('f5968', models.CharField(max_length=200)),
                ('f5969', models.TextField()),
                ('f5970', models.IntegerField(default=1)),
                ('f5971', models.IntegerField(default=1)),
                ('f5972', models.CharField(max_length=200)),
                ('f5973', models.TextField()),
                ('f5974', models.TextField()),
                ('f5975', models.TextField()),
                ('f5976', models.IntegerField(default=1)),
                ('f5977', models.IntegerField(default=1)),
                ('f5978', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M126',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f5979', models.TextField()),
                ('f5980', models.IntegerField(default=1)),
                ('f5981', models.TextField()),
                ('f5982', models.TextField()),
                ('f5983', models.TextField()),
                ('f5984', models.IntegerField(default=1)),
                ('f5985', models.IntegerField(default=1)),
                ('f5986', models.TextField()),
                ('f5987', models.CharField(max_length=200)),
                ('f5988', models.IntegerField(default=1)),
                ('f5989', models.CharField(max_length=200)),
                ('f5990', models.CharField(max_length=200)),
                ('f5991', models.TextField()),
                ('f5992', models.CharField(max_length=200)),
                ('f5993', models.CharField(max_length=200)),
                ('f5994', models.TextField()),
                ('f5995', models.TextField()),
                ('f5996', models.TextField()),
                ('f5997', models.IntegerField(default=1)),
                ('f5998', models.IntegerField(default=1)),
                ('f5999', models.TextField()),
                ('f6000', models.CharField(max_length=200)),
                ('f6001', models.IntegerField(default=1)),
                ('f6002', models.TextField()),
                ('f6003', models.TextField()),
                ('f6004', models.TextField()),
                ('f6005', models.IntegerField(default=1)),
                ('f6006', models.TextField()),
                ('f6007', models.TextField()),
                ('f6008', models.TextField()),
                ('f6009', models.CharField(max_length=200)),
                ('f6010', models.TextField()),
                ('f6011', models.CharField(max_length=200)),
                ('f6012', models.CharField(max_length=200)),
                ('f6013', models.TextField()),
                ('f6014', models.IntegerField(default=1)),
                ('f6015', models.IntegerField(default=1)),
                ('f6016', models.IntegerField(default=1)),
                ('f6017', models.TextField()),
                ('f6018', models.CharField(max_length=200)),
                ('f6019', models.TextField()),
                ('f6020', models.CharField(max_length=200)),
                ('f6021', models.IntegerField(default=1)),
                ('f6022', models.IntegerField(default=1)),
                ('f6023', models.TextField()),
                ('f6024', models.TextField()),
                ('f6025', models.TextField()),
                ('f6026', models.IntegerField(default=1)),
                ('f6027', models.IntegerField(default=1)),
                ('f6028', models.CharField(max_length=200)),
                ('f6029', models.IntegerField(default=1)),
                ('f6030', models.CharField(max_length=200)),
                ('f6031', models.CharField(max_length=200)),
                ('f6032', models.CharField(max_length=200)),
                ('f6033', models.IntegerField(default=1)),
                ('f6034', models.IntegerField(default=1)),
                ('f6035', models.CharField(max_length=200)),
                ('f6036', models.CharField(max_length=200)),
                ('f6037', models.IntegerField(default=1)),
                ('f6038', models.IntegerField(default=1)),
                ('f6039', models.IntegerField(default=1)),
                ('f6040', models.TextField()),
                ('f6041', models.CharField(max_length=200)),
                ('f6042', models.CharField(max_length=200)),
                ('f6043', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M127',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f6044', models.TextField()),
                ('f6045', models.TextField()),
                ('f6046', models.CharField(max_length=200)),
                ('f6047', models.CharField(max_length=200)),
                ('f6048', models.TextField()),
                ('f6049', models.IntegerField(default=1)),
                ('f6050', models.IntegerField(default=1)),
                ('f6051', models.IntegerField(default=1)),
                ('f6052', models.TextField()),
                ('f6053', models.TextField()),
                ('f6054', models.CharField(max_length=200)),
                ('f6055', models.TextField()),
                ('f6056', models.IntegerField(default=1)),
                ('f6057', models.IntegerField(default=1)),
                ('f6058', models.TextField()),
                ('f6059', models.TextField()),
                ('f6060', models.TextField()),
                ('f6061', models.TextField()),
                ('f6062', models.TextField()),
                ('f6063', models.CharField(max_length=200)),
                ('f6064', models.IntegerField(default=1)),
                ('f6065', models.CharField(max_length=200)),
                ('f6066', models.CharField(max_length=200)),
                ('f6067', models.CharField(max_length=200)),
                ('f6068', models.TextField()),
                ('f6069', models.IntegerField(default=1)),
                ('f6070', models.TextField()),
                ('f6071', models.IntegerField(default=1)),
                ('f6072', models.IntegerField(default=1)),
                ('f6073', models.TextField()),
                ('f6074', models.TextField()),
                ('f6075', models.CharField(max_length=200)),
                ('f6076', models.TextField()),
                ('f6077', models.CharField(max_length=200)),
                ('f6078', models.TextField()),
                ('f6079', models.TextField()),
                ('f6080', models.IntegerField(default=1)),
                ('f6081', models.IntegerField(default=1)),
                ('f6082', models.TextField()),
                ('f6083', models.TextField()),
                ('f6084', models.IntegerField(default=1)),
                ('f6085', models.CharField(max_length=200)),
                ('f6086', models.TextField()),
                ('f6087', models.CharField(max_length=200)),
                ('f6088', models.CharField(max_length=200)),
                ('f6089', models.CharField(max_length=200)),
                ('f6090', models.IntegerField(default=1)),
                ('f6091', models.CharField(max_length=200)),
                ('f6092', models.CharField(max_length=200)),
                ('f6093', models.IntegerField(default=1)),
                ('f6094', models.IntegerField(default=1)),
                ('f6095', models.IntegerField(default=1)),
                ('f6096', models.CharField(max_length=200)),
                ('f6097', models.TextField()),
                ('f6098', models.IntegerField(default=1)),
                ('f6099', models.CharField(max_length=200)),
                ('f6100', models.IntegerField(default=1)),
                ('f6101', models.TextField()),
                ('f6102', models.IntegerField(default=1)),
                ('f6103', models.IntegerField(default=1)),
                ('f6104', models.CharField(max_length=200)),
                ('f6105', models.CharField(max_length=200)),
                ('f6106', models.IntegerField(default=1)),
                ('f6107', models.CharField(max_length=200)),
                ('f6108', models.IntegerField(default=1)),
                ('f6109', models.CharField(max_length=200)),
                ('f6110', models.CharField(max_length=200)),
                ('f6111', models.IntegerField(default=1)),
                ('f6112', models.IntegerField(default=1)),
                ('f6113', models.IntegerField(default=1)),
                ('f6114', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M128',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f6115', models.TextField()),
                ('f6116', models.IntegerField(default=1)),
                ('f6117', models.IntegerField(default=1)),
                ('f6118', models.IntegerField(default=1)),
                ('f6119', models.TextField()),
                ('f6120', models.CharField(max_length=200)),
                ('f6121', models.IntegerField(default=1)),
                ('f6122', models.IntegerField(default=1)),
                ('f6123', models.TextField()),
                ('f6124', models.CharField(max_length=200)),
                ('f6125', models.TextField()),
                ('f6126', models.TextField()),
                ('f6127', models.CharField(max_length=200)),
                ('f6128', models.IntegerField(default=1)),
                ('f6129', models.IntegerField(default=1)),
                ('f6130', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M129',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f6131', models.CharField(max_length=200)),
                ('f6132', models.IntegerField(default=1)),
                ('f6133', models.CharField(max_length=200)),
                ('f6134', models.IntegerField(default=1)),
                ('f6135', models.CharField(max_length=200)),
                ('f6136', models.TextField()),
                ('f6137', models.IntegerField(default=1)),
                ('f6138', models.IntegerField(default=1)),
                ('f6139', models.CharField(max_length=200)),
                ('f6140', models.IntegerField(default=1)),
                ('f6141', models.CharField(max_length=200)),
                ('f6142', models.IntegerField(default=1)),
                ('f6143', models.IntegerField(default=1)),
                ('f6144', models.TextField()),
                ('f6145', models.IntegerField(default=1)),
                ('f6146', models.CharField(max_length=200)),
                ('f6147', models.IntegerField(default=1)),
                ('f6148', models.CharField(max_length=200)),
                ('f6149', models.TextField()),
                ('f6150', models.TextField()),
                ('f6151', models.IntegerField(default=1)),
                ('f6152', models.IntegerField(default=1)),
                ('f6153', models.IntegerField(default=1)),
                ('f6154', models.CharField(max_length=200)),
                ('f6155', models.CharField(max_length=200)),
                ('f6156', models.IntegerField(default=1)),
                ('f6157', models.IntegerField(default=1)),
                ('f6158', models.TextField()),
                ('f6159', models.CharField(max_length=200)),
                ('f6160', models.TextField()),
                ('f6161', models.TextField()),
                ('f6162', models.IntegerField(default=1)),
                ('f6163', models.CharField(max_length=200)),
                ('f6164', models.CharField(max_length=200)),
                ('f6165', models.TextField()),
                ('f6166', models.IntegerField(default=1)),
                ('f6167', models.TextField()),
                ('f6168', models.CharField(max_length=200)),
                ('f6169', models.IntegerField(default=1)),
                ('f6170', models.CharField(max_length=200)),
                ('f6171', models.IntegerField(default=1)),
                ('f6172', models.TextField()),
                ('f6173', models.IntegerField(default=1)),
                ('f6174', models.IntegerField(default=1)),
                ('f6175', models.TextField()),
                ('f6176', models.IntegerField(default=1)),
                ('f6177', models.CharField(max_length=200)),
                ('f6178', models.CharField(max_length=200)),
                ('f6179', models.TextField()),
                ('f6180', models.CharField(max_length=200)),
                ('f6181', models.CharField(max_length=200)),
                ('f6182', models.CharField(max_length=200)),
                ('f6183', models.IntegerField(default=1)),
                ('f6184', models.IntegerField(default=1)),
                ('f6185', models.CharField(max_length=200)),
                ('f6186', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M130',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f6187', models.IntegerField(default=1)),
                ('f6188', models.TextField()),
                ('f6189', models.IntegerField(default=1)),
            ],
        ),
    ]
