# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M31',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1432', models.CharField(max_length=200)),
                ('f1433', models.IntegerField(default=1)),
                ('f1434', models.TextField()),
                ('f1435', models.CharField(max_length=200)),
                ('f1436', models.IntegerField(default=1)),
                ('f1437', models.TextField()),
                ('f1438', models.CharField(max_length=200)),
                ('f1439', models.CharField(max_length=200)),
                ('f1440', models.IntegerField(default=1)),
                ('f1441', models.TextField()),
                ('f1442', models.IntegerField(default=1)),
                ('f1443', models.CharField(max_length=200)),
                ('f1444', models.CharField(max_length=200)),
                ('f1445', models.IntegerField(default=1)),
                ('f1446', models.TextField()),
                ('f1447', models.TextField()),
                ('f1448', models.IntegerField(default=1)),
                ('f1449', models.TextField()),
                ('f1450', models.CharField(max_length=200)),
                ('f1451', models.TextField()),
                ('f1452', models.TextField()),
                ('f1453', models.TextField()),
                ('f1454', models.IntegerField(default=1)),
                ('f1455', models.IntegerField(default=1)),
                ('f1456', models.IntegerField(default=1)),
                ('f1457', models.TextField()),
                ('f1458', models.IntegerField(default=1)),
                ('f1459', models.TextField()),
                ('f1460', models.IntegerField(default=1)),
                ('f1461', models.TextField()),
                ('f1462', models.TextField()),
                ('f1463', models.TextField()),
                ('f1464', models.TextField()),
                ('f1465', models.IntegerField(default=1)),
                ('f1466', models.IntegerField(default=1)),
                ('f1467', models.TextField()),
                ('f1468', models.TextField()),
                ('f1469', models.TextField()),
                ('f1470', models.IntegerField(default=1)),
                ('f1471', models.IntegerField(default=1)),
                ('f1472', models.TextField()),
                ('f1473', models.IntegerField(default=1)),
                ('f1474', models.CharField(max_length=200)),
                ('f1475', models.CharField(max_length=200)),
                ('f1476', models.CharField(max_length=200)),
                ('f1477', models.CharField(max_length=200)),
                ('f1478', models.CharField(max_length=200)),
                ('f1479', models.IntegerField(default=1)),
                ('f1480', models.TextField()),
                ('f1481', models.IntegerField(default=1)),
                ('f1482', models.IntegerField(default=1)),
                ('f1483', models.TextField()),
                ('f1484', models.IntegerField(default=1)),
                ('f1485', models.IntegerField(default=1)),
                ('f1486', models.CharField(max_length=200)),
                ('f1487', models.TextField()),
                ('f1488', models.IntegerField(default=1)),
                ('f1489', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M32',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1490', models.IntegerField(default=1)),
                ('f1491', models.CharField(max_length=200)),
                ('f1492', models.TextField()),
                ('f1493', models.TextField()),
                ('f1494', models.TextField()),
                ('f1495', models.CharField(max_length=200)),
                ('f1496', models.TextField()),
                ('f1497', models.CharField(max_length=200)),
                ('f1498', models.CharField(max_length=200)),
                ('f1499', models.TextField()),
                ('f1500', models.IntegerField(default=1)),
                ('f1501', models.CharField(max_length=200)),
                ('f1502', models.IntegerField(default=1)),
                ('f1503', models.IntegerField(default=1)),
                ('f1504', models.CharField(max_length=200)),
                ('f1505', models.TextField()),
                ('f1506', models.IntegerField(default=1)),
                ('f1507', models.IntegerField(default=1)),
                ('f1508', models.CharField(max_length=200)),
                ('f1509', models.CharField(max_length=200)),
                ('f1510', models.IntegerField(default=1)),
                ('f1511', models.IntegerField(default=1)),
                ('f1512', models.TextField()),
                ('f1513', models.CharField(max_length=200)),
                ('f1514', models.CharField(max_length=200)),
                ('f1515', models.TextField()),
                ('f1516', models.TextField()),
                ('f1517', models.CharField(max_length=200)),
                ('f1518', models.IntegerField(default=1)),
                ('f1519', models.IntegerField(default=1)),
                ('f1520', models.IntegerField(default=1)),
                ('f1521', models.IntegerField(default=1)),
                ('f1522', models.IntegerField(default=1)),
                ('f1523', models.CharField(max_length=200)),
                ('f1524', models.IntegerField(default=1)),
                ('f1525', models.IntegerField(default=1)),
                ('f1526', models.IntegerField(default=1)),
                ('f1527', models.CharField(max_length=200)),
                ('f1528', models.TextField()),
                ('f1529', models.TextField()),
                ('f1530', models.CharField(max_length=200)),
                ('f1531', models.IntegerField(default=1)),
                ('f1532', models.TextField()),
                ('f1533', models.TextField()),
                ('f1534', models.CharField(max_length=200)),
                ('f1535', models.IntegerField(default=1)),
                ('f1536', models.TextField()),
                ('f1537', models.TextField()),
                ('f1538', models.IntegerField(default=1)),
                ('f1539', models.CharField(max_length=200)),
                ('f1540', models.CharField(max_length=200)),
                ('f1541', models.IntegerField(default=1)),
                ('f1542', models.CharField(max_length=200)),
                ('f1543', models.TextField()),
                ('f1544', models.CharField(max_length=200)),
                ('f1545', models.TextField()),
                ('f1546', models.IntegerField(default=1)),
                ('f1547', models.CharField(max_length=200)),
                ('f1548', models.CharField(max_length=200)),
                ('f1549', models.IntegerField(default=1)),
                ('f1550', models.TextField()),
                ('f1551', models.CharField(max_length=200)),
                ('f1552', models.TextField()),
                ('f1553', models.IntegerField(default=1)),
                ('f1554', models.CharField(max_length=200)),
                ('f1555', models.CharField(max_length=200)),
                ('f1556', models.IntegerField(default=1)),
                ('f1557', models.IntegerField(default=1)),
                ('f1558', models.TextField()),
                ('f1559', models.TextField()),
                ('f1560', models.IntegerField(default=1)),
                ('f1561', models.CharField(max_length=200)),
                ('f1562', models.CharField(max_length=200)),
                ('f1563', models.IntegerField(default=1)),
                ('f1564', models.TextField()),
                ('f1565', models.IntegerField(default=1)),
                ('f1566', models.CharField(max_length=200)),
                ('f1567', models.CharField(max_length=200)),
                ('f1568', models.IntegerField(default=1)),
                ('f1569', models.TextField()),
                ('f1570', models.TextField()),
                ('f1571', models.CharField(max_length=200)),
                ('f1572', models.CharField(max_length=200)),
                ('f1573', models.IntegerField(default=1)),
                ('f1574', models.CharField(max_length=200)),
                ('f1575', models.TextField()),
                ('f1576', models.IntegerField(default=1)),
                ('f1577', models.CharField(max_length=200)),
                ('f1578', models.IntegerField(default=1)),
                ('f1579', models.TextField()),
                ('f1580', models.CharField(max_length=200)),
                ('f1581', models.CharField(max_length=200)),
                ('f1582', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M33',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1583', models.IntegerField(default=1)),
                ('f1584', models.CharField(max_length=200)),
                ('f1585', models.IntegerField(default=1)),
                ('f1586', models.IntegerField(default=1)),
                ('f1587', models.TextField()),
                ('f1588', models.IntegerField(default=1)),
                ('f1589', models.CharField(max_length=200)),
                ('f1590', models.TextField()),
                ('f1591', models.TextField()),
                ('f1592', models.IntegerField(default=1)),
                ('f1593', models.CharField(max_length=200)),
                ('f1594', models.CharField(max_length=200)),
                ('f1595', models.IntegerField(default=1)),
                ('f1596', models.IntegerField(default=1)),
                ('f1597', models.IntegerField(default=1)),
                ('f1598', models.CharField(max_length=200)),
                ('f1599', models.TextField()),
                ('f1600', models.TextField()),
                ('f1601', models.CharField(max_length=200)),
                ('f1602', models.CharField(max_length=200)),
                ('f1603', models.IntegerField(default=1)),
                ('f1604', models.IntegerField(default=1)),
                ('f1605', models.IntegerField(default=1)),
                ('f1606', models.CharField(max_length=200)),
                ('f1607', models.IntegerField(default=1)),
                ('f1608', models.CharField(max_length=200)),
                ('f1609', models.TextField()),
                ('f1610', models.TextField()),
                ('f1611', models.TextField()),
                ('f1612', models.CharField(max_length=200)),
                ('f1613', models.TextField()),
                ('f1614', models.IntegerField(default=1)),
                ('f1615', models.CharField(max_length=200)),
                ('f1616', models.IntegerField(default=1)),
                ('f1617', models.TextField()),
                ('f1618', models.CharField(max_length=200)),
                ('f1619', models.TextField()),
                ('f1620', models.CharField(max_length=200)),
                ('f1621', models.TextField()),
                ('f1622', models.IntegerField(default=1)),
                ('f1623', models.CharField(max_length=200)),
                ('f1624', models.TextField()),
                ('f1625', models.CharField(max_length=200)),
                ('f1626', models.IntegerField(default=1)),
                ('f1627', models.IntegerField(default=1)),
                ('f1628', models.CharField(max_length=200)),
                ('f1629', models.CharField(max_length=200)),
                ('f1630', models.IntegerField(default=1)),
                ('f1631', models.IntegerField(default=1)),
                ('f1632', models.IntegerField(default=1)),
                ('f1633', models.IntegerField(default=1)),
                ('f1634', models.IntegerField(default=1)),
                ('f1635', models.CharField(max_length=200)),
                ('f1636', models.CharField(max_length=200)),
                ('f1637', models.IntegerField(default=1)),
                ('f1638', models.CharField(max_length=200)),
                ('f1639', models.IntegerField(default=1)),
                ('f1640', models.TextField()),
                ('f1641', models.TextField()),
                ('f1642', models.CharField(max_length=200)),
                ('f1643', models.IntegerField(default=1)),
                ('f1644', models.IntegerField(default=1)),
                ('f1645', models.IntegerField(default=1)),
                ('f1646', models.IntegerField(default=1)),
                ('f1647', models.CharField(max_length=200)),
                ('f1648', models.IntegerField(default=1)),
                ('f1649', models.CharField(max_length=200)),
                ('f1650', models.IntegerField(default=1)),
                ('f1651', models.TextField()),
                ('f1652', models.CharField(max_length=200)),
                ('f1653', models.CharField(max_length=200)),
                ('f1654', models.CharField(max_length=200)),
                ('f1655', models.IntegerField(default=1)),
                ('f1656', models.TextField()),
                ('f1657', models.TextField()),
                ('f1658', models.CharField(max_length=200)),
                ('f1659', models.TextField()),
                ('f1660', models.TextField()),
                ('f1661', models.TextField()),
                ('f1662', models.TextField()),
                ('f1663', models.CharField(max_length=200)),
                ('f1664', models.CharField(max_length=200)),
                ('f1665', models.IntegerField(default=1)),
                ('f1666', models.TextField()),
                ('f1667', models.CharField(max_length=200)),
                ('f1668', models.CharField(max_length=200)),
                ('f1669', models.IntegerField(default=1)),
                ('f1670', models.CharField(max_length=200)),
                ('f1671', models.TextField()),
                ('f1672', models.IntegerField(default=1)),
                ('f1673', models.TextField()),
                ('f1674', models.CharField(max_length=200)),
                ('f1675', models.IntegerField(default=1)),
                ('f1676', models.TextField()),
                ('f1677', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M34',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1678', models.TextField()),
                ('f1679', models.TextField()),
                ('f1680', models.TextField()),
                ('f1681', models.TextField()),
                ('f1682', models.TextField()),
                ('f1683', models.CharField(max_length=200)),
                ('f1684', models.TextField()),
                ('f1685', models.IntegerField(default=1)),
                ('f1686', models.CharField(max_length=200)),
                ('f1687', models.IntegerField(default=1)),
                ('f1688', models.CharField(max_length=200)),
                ('f1689', models.CharField(max_length=200)),
                ('f1690', models.TextField()),
                ('f1691', models.IntegerField(default=1)),
                ('f1692', models.TextField()),
                ('f1693', models.CharField(max_length=200)),
                ('f1694', models.IntegerField(default=1)),
                ('f1695', models.TextField()),
                ('f1696', models.IntegerField(default=1)),
                ('f1697', models.IntegerField(default=1)),
                ('f1698', models.TextField()),
                ('f1699', models.IntegerField(default=1)),
                ('f1700', models.TextField()),
                ('f1701', models.IntegerField(default=1)),
                ('f1702', models.CharField(max_length=200)),
                ('f1703', models.IntegerField(default=1)),
                ('f1704', models.CharField(max_length=200)),
                ('f1705', models.CharField(max_length=200)),
                ('f1706', models.CharField(max_length=200)),
                ('f1707', models.CharField(max_length=200)),
                ('f1708', models.CharField(max_length=200)),
                ('f1709', models.CharField(max_length=200)),
                ('f1710', models.IntegerField(default=1)),
                ('f1711', models.IntegerField(default=1)),
                ('f1712', models.IntegerField(default=1)),
                ('f1713', models.CharField(max_length=200)),
                ('f1714', models.TextField()),
                ('f1715', models.CharField(max_length=200)),
                ('f1716', models.IntegerField(default=1)),
                ('f1717', models.IntegerField(default=1)),
                ('f1718', models.CharField(max_length=200)),
                ('f1719', models.CharField(max_length=200)),
                ('f1720', models.CharField(max_length=200)),
                ('f1721', models.TextField()),
                ('f1722', models.IntegerField(default=1)),
                ('f1723', models.TextField()),
                ('f1724', models.TextField()),
                ('f1725', models.IntegerField(default=1)),
                ('f1726', models.IntegerField(default=1)),
                ('f1727', models.CharField(max_length=200)),
                ('f1728', models.CharField(max_length=200)),
                ('f1729', models.IntegerField(default=1)),
                ('f1730', models.CharField(max_length=200)),
                ('f1731', models.TextField()),
                ('f1732', models.TextField()),
                ('f1733', models.TextField()),
                ('f1734', models.CharField(max_length=200)),
                ('f1735', models.CharField(max_length=200)),
                ('f1736', models.IntegerField(default=1)),
                ('f1737', models.TextField()),
                ('f1738', models.TextField()),
                ('f1739', models.IntegerField(default=1)),
                ('f1740', models.TextField()),
                ('f1741', models.IntegerField(default=1)),
                ('f1742', models.CharField(max_length=200)),
                ('f1743', models.IntegerField(default=1)),
                ('f1744', models.CharField(max_length=200)),
                ('f1745', models.CharField(max_length=200)),
                ('f1746', models.CharField(max_length=200)),
                ('f1747', models.CharField(max_length=200)),
                ('f1748', models.CharField(max_length=200)),
                ('f1749', models.CharField(max_length=200)),
                ('f1750', models.CharField(max_length=200)),
                ('f1751', models.TextField()),
                ('f1752', models.CharField(max_length=200)),
                ('f1753', models.TextField()),
                ('f1754', models.IntegerField(default=1)),
                ('f1755', models.IntegerField(default=1)),
                ('f1756', models.TextField()),
                ('f1757', models.IntegerField(default=1)),
                ('f1758', models.CharField(max_length=200)),
                ('f1759', models.CharField(max_length=200)),
                ('f1760', models.TextField()),
                ('f1761', models.IntegerField(default=1)),
                ('f1762', models.CharField(max_length=200)),
                ('f1763', models.IntegerField(default=1)),
                ('f1764', models.IntegerField(default=1)),
                ('f1765', models.TextField()),
                ('f1766', models.TextField()),
                ('f1767', models.TextField()),
                ('f1768', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M35',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1769', models.IntegerField(default=1)),
                ('f1770', models.TextField()),
                ('f1771', models.CharField(max_length=200)),
                ('f1772', models.CharField(max_length=200)),
                ('f1773', models.CharField(max_length=200)),
                ('f1774', models.CharField(max_length=200)),
                ('f1775', models.IntegerField(default=1)),
                ('f1776', models.IntegerField(default=1)),
                ('f1777', models.CharField(max_length=200)),
                ('f1778', models.CharField(max_length=200)),
                ('f1779', models.TextField()),
                ('f1780', models.TextField()),
                ('f1781', models.IntegerField(default=1)),
                ('f1782', models.TextField()),
                ('f1783', models.IntegerField(default=1)),
                ('f1784', models.CharField(max_length=200)),
                ('f1785', models.IntegerField(default=1)),
                ('f1786', models.CharField(max_length=200)),
                ('f1787', models.CharField(max_length=200)),
                ('f1788', models.TextField()),
                ('f1789', models.CharField(max_length=200)),
                ('f1790', models.IntegerField(default=1)),
                ('f1791', models.IntegerField(default=1)),
                ('f1792', models.TextField()),
                ('f1793', models.CharField(max_length=200)),
                ('f1794', models.IntegerField(default=1)),
                ('f1795', models.CharField(max_length=200)),
                ('f1796', models.IntegerField(default=1)),
                ('f1797', models.CharField(max_length=200)),
                ('f1798', models.TextField()),
                ('f1799', models.CharField(max_length=200)),
                ('f1800', models.IntegerField(default=1)),
                ('f1801', models.TextField()),
                ('f1802', models.TextField()),
                ('f1803', models.CharField(max_length=200)),
                ('f1804', models.TextField()),
                ('f1805', models.IntegerField(default=1)),
                ('f1806', models.CharField(max_length=200)),
                ('f1807', models.CharField(max_length=200)),
                ('f1808', models.CharField(max_length=200)),
                ('f1809', models.TextField()),
                ('f1810', models.CharField(max_length=200)),
                ('f1811', models.IntegerField(default=1)),
                ('f1812', models.IntegerField(default=1)),
                ('f1813', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M36',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1814', models.IntegerField(default=1)),
                ('f1815', models.IntegerField(default=1)),
                ('f1816', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M37',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1817', models.TextField()),
                ('f1818', models.CharField(max_length=200)),
                ('f1819', models.IntegerField(default=1)),
                ('f1820', models.TextField()),
                ('f1821', models.IntegerField(default=1)),
                ('f1822', models.IntegerField(default=1)),
                ('f1823', models.CharField(max_length=200)),
                ('f1824', models.CharField(max_length=200)),
                ('f1825', models.CharField(max_length=200)),
                ('f1826', models.IntegerField(default=1)),
                ('f1827', models.TextField()),
                ('f1828', models.IntegerField(default=1)),
                ('f1829', models.IntegerField(default=1)),
                ('f1830', models.CharField(max_length=200)),
                ('f1831', models.TextField()),
                ('f1832', models.TextField()),
                ('f1833', models.TextField()),
                ('f1834', models.IntegerField(default=1)),
                ('f1835', models.IntegerField(default=1)),
                ('f1836', models.CharField(max_length=200)),
                ('f1837', models.CharField(max_length=200)),
                ('f1838', models.IntegerField(default=1)),
                ('f1839', models.IntegerField(default=1)),
                ('f1840', models.TextField()),
                ('f1841', models.CharField(max_length=200)),
                ('f1842', models.IntegerField(default=1)),
                ('f1843', models.CharField(max_length=200)),
                ('f1844', models.CharField(max_length=200)),
                ('f1845', models.CharField(max_length=200)),
                ('f1846', models.CharField(max_length=200)),
                ('f1847', models.TextField()),
                ('f1848', models.IntegerField(default=1)),
                ('f1849', models.TextField()),
                ('f1850', models.TextField()),
                ('f1851', models.IntegerField(default=1)),
                ('f1852', models.CharField(max_length=200)),
                ('f1853', models.IntegerField(default=1)),
                ('f1854', models.TextField()),
                ('f1855', models.TextField()),
                ('f1856', models.TextField()),
                ('f1857', models.IntegerField(default=1)),
                ('f1858', models.TextField()),
                ('f1859', models.IntegerField(default=1)),
                ('f1860', models.IntegerField(default=1)),
                ('f1861', models.IntegerField(default=1)),
                ('f1862', models.CharField(max_length=200)),
                ('f1863', models.TextField()),
                ('f1864', models.IntegerField(default=1)),
                ('f1865', models.TextField()),
                ('f1866', models.TextField()),
                ('f1867', models.IntegerField(default=1)),
                ('f1868', models.CharField(max_length=200)),
                ('f1869', models.IntegerField(default=1)),
                ('f1870', models.IntegerField(default=1)),
                ('f1871', models.IntegerField(default=1)),
                ('f1872', models.TextField()),
                ('f1873', models.TextField()),
                ('f1874', models.TextField()),
                ('f1875', models.TextField()),
                ('f1876', models.CharField(max_length=200)),
                ('f1877', models.CharField(max_length=200)),
                ('f1878', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M38',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1879', models.IntegerField(default=1)),
                ('f1880', models.CharField(max_length=200)),
                ('f1881', models.TextField()),
                ('f1882', models.CharField(max_length=200)),
                ('f1883', models.CharField(max_length=200)),
                ('f1884', models.IntegerField(default=1)),
                ('f1885', models.IntegerField(default=1)),
                ('f1886', models.IntegerField(default=1)),
                ('f1887', models.IntegerField(default=1)),
                ('f1888', models.CharField(max_length=200)),
                ('f1889', models.CharField(max_length=200)),
                ('f1890', models.CharField(max_length=200)),
                ('f1891', models.IntegerField(default=1)),
                ('f1892', models.TextField()),
                ('f1893', models.TextField()),
                ('f1894', models.IntegerField(default=1)),
                ('f1895', models.CharField(max_length=200)),
                ('f1896', models.TextField()),
                ('f1897', models.CharField(max_length=200)),
                ('f1898', models.TextField()),
                ('f1899', models.TextField()),
                ('f1900', models.TextField()),
                ('f1901', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M39',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1902', models.TextField()),
                ('f1903', models.IntegerField(default=1)),
                ('f1904', models.CharField(max_length=200)),
                ('f1905', models.IntegerField(default=1)),
                ('f1906', models.TextField()),
                ('f1907', models.IntegerField(default=1)),
                ('f1908', models.CharField(max_length=200)),
                ('f1909', models.IntegerField(default=1)),
                ('f1910', models.IntegerField(default=1)),
                ('f1911', models.IntegerField(default=1)),
                ('f1912', models.CharField(max_length=200)),
                ('f1913', models.IntegerField(default=1)),
                ('f1914', models.TextField()),
                ('f1915', models.TextField()),
                ('f1916', models.TextField()),
                ('f1917', models.TextField()),
                ('f1918', models.IntegerField(default=1)),
                ('f1919', models.IntegerField(default=1)),
                ('f1920', models.TextField()),
                ('f1921', models.IntegerField(default=1)),
                ('f1922', models.IntegerField(default=1)),
                ('f1923', models.TextField()),
                ('f1924', models.TextField()),
                ('f1925', models.IntegerField(default=1)),
                ('f1926', models.IntegerField(default=1)),
                ('f1927', models.TextField()),
                ('f1928', models.IntegerField(default=1)),
                ('f1929', models.IntegerField(default=1)),
                ('f1930', models.IntegerField(default=1)),
                ('f1931', models.CharField(max_length=200)),
                ('f1932', models.IntegerField(default=1)),
                ('f1933', models.IntegerField(default=1)),
                ('f1934', models.IntegerField(default=1)),
                ('f1935', models.IntegerField(default=1)),
                ('f1936', models.IntegerField(default=1)),
                ('f1937', models.CharField(max_length=200)),
                ('f1938', models.IntegerField(default=1)),
                ('f1939', models.IntegerField(default=1)),
                ('f1940', models.CharField(max_length=200)),
                ('f1941', models.TextField()),
                ('f1942', models.CharField(max_length=200)),
                ('f1943', models.IntegerField(default=1)),
                ('f1944', models.TextField()),
                ('f1945', models.TextField()),
                ('f1946', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M40',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1947', models.CharField(max_length=200)),
                ('f1948', models.IntegerField(default=1)),
                ('f1949', models.IntegerField(default=1)),
                ('f1950', models.IntegerField(default=1)),
                ('f1951', models.IntegerField(default=1)),
                ('f1952', models.CharField(max_length=200)),
                ('f1953', models.TextField()),
                ('f1954', models.IntegerField(default=1)),
                ('f1955', models.TextField()),
                ('f1956', models.IntegerField(default=1)),
                ('f1957', models.CharField(max_length=200)),
                ('f1958', models.TextField()),
                ('f1959', models.IntegerField(default=1)),
                ('f1960', models.TextField()),
                ('f1961', models.IntegerField(default=1)),
                ('f1962', models.CharField(max_length=200)),
            ],
        ),
    ]
