# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M161',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7451', models.TextField()),
                ('f7452', models.TextField()),
                ('f7453', models.IntegerField(default=1)),
                ('f7454', models.TextField()),
                ('f7455', models.CharField(max_length=200)),
                ('f7456', models.CharField(max_length=200)),
                ('f7457', models.TextField()),
                ('f7458', models.TextField()),
                ('f7459', models.IntegerField(default=1)),
                ('f7460', models.TextField()),
                ('f7461', models.IntegerField(default=1)),
                ('f7462', models.IntegerField(default=1)),
                ('f7463', models.IntegerField(default=1)),
                ('f7464', models.IntegerField(default=1)),
                ('f7465', models.TextField()),
                ('f7466', models.CharField(max_length=200)),
                ('f7467', models.TextField()),
                ('f7468', models.TextField()),
                ('f7469', models.CharField(max_length=200)),
                ('f7470', models.TextField()),
                ('f7471', models.CharField(max_length=200)),
                ('f7472', models.IntegerField(default=1)),
                ('f7473', models.CharField(max_length=200)),
                ('f7474', models.TextField()),
                ('f7475', models.CharField(max_length=200)),
                ('f7476', models.TextField()),
                ('f7477', models.CharField(max_length=200)),
                ('f7478', models.CharField(max_length=200)),
                ('f7479', models.IntegerField(default=1)),
                ('f7480', models.IntegerField(default=1)),
                ('f7481', models.TextField()),
                ('f7482', models.CharField(max_length=200)),
                ('f7483', models.TextField()),
                ('f7484', models.CharField(max_length=200)),
                ('f7485', models.TextField()),
                ('f7486', models.CharField(max_length=200)),
                ('f7487', models.CharField(max_length=200)),
                ('f7488', models.CharField(max_length=200)),
                ('f7489', models.CharField(max_length=200)),
                ('f7490', models.IntegerField(default=1)),
                ('f7491', models.TextField()),
                ('f7492', models.CharField(max_length=200)),
                ('f7493', models.CharField(max_length=200)),
                ('f7494', models.CharField(max_length=200)),
                ('f7495', models.CharField(max_length=200)),
                ('f7496', models.TextField()),
                ('f7497', models.TextField()),
                ('f7498', models.TextField()),
                ('f7499', models.IntegerField(default=1)),
                ('f7500', models.TextField()),
                ('f7501', models.TextField()),
                ('f7502', models.TextField()),
                ('f7503', models.TextField()),
                ('f7504', models.TextField()),
                ('f7505', models.IntegerField(default=1)),
                ('f7506', models.TextField()),
                ('f7507', models.CharField(max_length=200)),
                ('f7508', models.TextField()),
                ('f7509', models.TextField()),
                ('f7510', models.TextField()),
                ('f7511', models.TextField()),
                ('f7512', models.CharField(max_length=200)),
                ('f7513', models.IntegerField(default=1)),
                ('f7514', models.IntegerField(default=1)),
                ('f7515', models.IntegerField(default=1)),
                ('f7516', models.TextField()),
                ('f7517', models.CharField(max_length=200)),
                ('f7518', models.TextField()),
                ('f7519', models.CharField(max_length=200)),
                ('f7520', models.IntegerField(default=1)),
                ('f7521', models.IntegerField(default=1)),
                ('f7522', models.TextField()),
                ('f7523', models.TextField()),
                ('f7524', models.CharField(max_length=200)),
                ('f7525', models.TextField()),
                ('f7526', models.CharField(max_length=200)),
                ('f7527', models.CharField(max_length=200)),
                ('f7528', models.TextField()),
                ('f7529', models.TextField()),
                ('f7530', models.TextField()),
                ('f7531', models.TextField()),
                ('f7532', models.CharField(max_length=200)),
                ('f7533', models.CharField(max_length=200)),
                ('f7534', models.TextField()),
                ('f7535', models.CharField(max_length=200)),
                ('f7536', models.CharField(max_length=200)),
                ('f7537', models.TextField()),
                ('f7538', models.IntegerField(default=1)),
                ('f7539', models.IntegerField(default=1)),
                ('f7540', models.TextField()),
                ('f7541', models.IntegerField(default=1)),
                ('f7542', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M162',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7543', models.TextField()),
                ('f7544', models.CharField(max_length=200)),
                ('f7545', models.IntegerField(default=1)),
                ('f7546', models.TextField()),
                ('f7547', models.IntegerField(default=1)),
                ('f7548', models.IntegerField(default=1)),
                ('f7549', models.CharField(max_length=200)),
                ('f7550', models.CharField(max_length=200)),
                ('f7551', models.CharField(max_length=200)),
                ('f7552', models.IntegerField(default=1)),
                ('f7553', models.TextField()),
                ('f7554', models.CharField(max_length=200)),
                ('f7555', models.IntegerField(default=1)),
                ('f7556', models.TextField()),
                ('f7557', models.CharField(max_length=200)),
                ('f7558', models.IntegerField(default=1)),
                ('f7559', models.IntegerField(default=1)),
                ('f7560', models.TextField()),
                ('f7561', models.CharField(max_length=200)),
                ('f7562', models.TextField()),
                ('f7563', models.IntegerField(default=1)),
                ('f7564', models.IntegerField(default=1)),
                ('f7565', models.CharField(max_length=200)),
                ('f7566', models.IntegerField(default=1)),
                ('f7567', models.CharField(max_length=200)),
                ('f7568', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M163',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7569', models.TextField()),
                ('f7570', models.IntegerField(default=1)),
                ('f7571', models.TextField()),
                ('f7572', models.IntegerField(default=1)),
                ('f7573', models.IntegerField(default=1)),
                ('f7574', models.TextField()),
                ('f7575', models.IntegerField(default=1)),
                ('f7576', models.CharField(max_length=200)),
                ('f7577', models.IntegerField(default=1)),
                ('f7578', models.CharField(max_length=200)),
                ('f7579', models.TextField()),
                ('f7580', models.CharField(max_length=200)),
                ('f7581', models.IntegerField(default=1)),
                ('f7582', models.IntegerField(default=1)),
                ('f7583', models.CharField(max_length=200)),
                ('f7584', models.IntegerField(default=1)),
                ('f7585', models.TextField()),
                ('f7586', models.IntegerField(default=1)),
                ('f7587', models.IntegerField(default=1)),
                ('f7588', models.TextField()),
                ('f7589', models.TextField()),
                ('f7590', models.CharField(max_length=200)),
                ('f7591', models.TextField()),
                ('f7592', models.TextField()),
                ('f7593', models.CharField(max_length=200)),
                ('f7594', models.CharField(max_length=200)),
                ('f7595', models.TextField()),
                ('f7596', models.IntegerField(default=1)),
                ('f7597', models.TextField()),
                ('f7598', models.CharField(max_length=200)),
                ('f7599', models.TextField()),
                ('f7600', models.CharField(max_length=200)),
                ('f7601', models.IntegerField(default=1)),
                ('f7602', models.IntegerField(default=1)),
                ('f7603', models.CharField(max_length=200)),
                ('f7604', models.TextField()),
                ('f7605', models.IntegerField(default=1)),
                ('f7606', models.IntegerField(default=1)),
                ('f7607', models.CharField(max_length=200)),
                ('f7608', models.CharField(max_length=200)),
                ('f7609', models.CharField(max_length=200)),
                ('f7610', models.IntegerField(default=1)),
                ('f7611', models.IntegerField(default=1)),
                ('f7612', models.IntegerField(default=1)),
                ('f7613', models.CharField(max_length=200)),
                ('f7614', models.TextField()),
                ('f7615', models.TextField()),
                ('f7616', models.TextField()),
                ('f7617', models.CharField(max_length=200)),
                ('f7618', models.TextField()),
                ('f7619', models.CharField(max_length=200)),
                ('f7620', models.TextField()),
                ('f7621', models.IntegerField(default=1)),
                ('f7622', models.CharField(max_length=200)),
                ('f7623', models.TextField()),
                ('f7624', models.CharField(max_length=200)),
                ('f7625', models.CharField(max_length=200)),
                ('f7626', models.CharField(max_length=200)),
                ('f7627', models.CharField(max_length=200)),
                ('f7628', models.CharField(max_length=200)),
                ('f7629', models.IntegerField(default=1)),
                ('f7630', models.TextField()),
                ('f7631', models.CharField(max_length=200)),
                ('f7632', models.IntegerField(default=1)),
                ('f7633', models.TextField()),
                ('f7634', models.TextField()),
                ('f7635', models.CharField(max_length=200)),
                ('f7636', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M164',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7637', models.TextField()),
                ('f7638', models.TextField()),
                ('f7639', models.IntegerField(default=1)),
                ('f7640', models.TextField()),
                ('f7641', models.CharField(max_length=200)),
                ('f7642', models.TextField()),
                ('f7643', models.IntegerField(default=1)),
                ('f7644', models.IntegerField(default=1)),
                ('f7645', models.TextField()),
                ('f7646', models.TextField()),
                ('f7647', models.TextField()),
                ('f7648', models.IntegerField(default=1)),
                ('f7649', models.CharField(max_length=200)),
                ('f7650', models.CharField(max_length=200)),
                ('f7651', models.IntegerField(default=1)),
                ('f7652', models.CharField(max_length=200)),
                ('f7653', models.CharField(max_length=200)),
                ('f7654', models.IntegerField(default=1)),
                ('f7655', models.CharField(max_length=200)),
                ('f7656', models.IntegerField(default=1)),
                ('f7657', models.CharField(max_length=200)),
                ('f7658', models.TextField()),
                ('f7659', models.IntegerField(default=1)),
                ('f7660', models.IntegerField(default=1)),
                ('f7661', models.CharField(max_length=200)),
                ('f7662', models.CharField(max_length=200)),
                ('f7663', models.TextField()),
                ('f7664', models.CharField(max_length=200)),
                ('f7665', models.CharField(max_length=200)),
                ('f7666', models.IntegerField(default=1)),
                ('f7667', models.TextField()),
                ('f7668', models.IntegerField(default=1)),
                ('f7669', models.CharField(max_length=200)),
                ('f7670', models.TextField()),
                ('f7671', models.TextField()),
                ('f7672', models.CharField(max_length=200)),
                ('f7673', models.TextField()),
                ('f7674', models.IntegerField(default=1)),
                ('f7675', models.TextField()),
                ('f7676', models.TextField()),
                ('f7677', models.CharField(max_length=200)),
                ('f7678', models.TextField()),
                ('f7679', models.TextField()),
                ('f7680', models.TextField()),
                ('f7681', models.IntegerField(default=1)),
                ('f7682', models.IntegerField(default=1)),
                ('f7683', models.IntegerField(default=1)),
                ('f7684', models.IntegerField(default=1)),
                ('f7685', models.IntegerField(default=1)),
                ('f7686', models.TextField()),
                ('f7687', models.TextField()),
                ('f7688', models.IntegerField(default=1)),
                ('f7689', models.IntegerField(default=1)),
                ('f7690', models.TextField()),
                ('f7691', models.TextField()),
                ('f7692', models.TextField()),
                ('f7693', models.CharField(max_length=200)),
                ('f7694', models.TextField()),
                ('f7695', models.TextField()),
                ('f7696', models.TextField()),
                ('f7697', models.CharField(max_length=200)),
                ('f7698', models.IntegerField(default=1)),
                ('f7699', models.CharField(max_length=200)),
                ('f7700', models.IntegerField(default=1)),
                ('f7701', models.IntegerField(default=1)),
                ('f7702', models.TextField()),
                ('f7703', models.TextField()),
                ('f7704', models.CharField(max_length=200)),
                ('f7705', models.CharField(max_length=200)),
                ('f7706', models.CharField(max_length=200)),
                ('f7707', models.CharField(max_length=200)),
                ('f7708', models.IntegerField(default=1)),
                ('f7709', models.TextField()),
                ('f7710', models.IntegerField(default=1)),
                ('f7711', models.TextField()),
                ('f7712', models.CharField(max_length=200)),
                ('f7713', models.TextField()),
                ('f7714', models.TextField()),
                ('f7715', models.TextField()),
                ('f7716', models.IntegerField(default=1)),
                ('f7717', models.CharField(max_length=200)),
                ('f7718', models.TextField()),
                ('f7719', models.IntegerField(default=1)),
                ('f7720', models.IntegerField(default=1)),
                ('f7721', models.IntegerField(default=1)),
                ('f7722', models.IntegerField(default=1)),
                ('f7723', models.TextField()),
                ('f7724', models.IntegerField(default=1)),
                ('f7725', models.IntegerField(default=1)),
                ('f7726', models.CharField(max_length=200)),
                ('f7727', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M165',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7728', models.IntegerField(default=1)),
                ('f7729', models.CharField(max_length=200)),
                ('f7730', models.IntegerField(default=1)),
                ('f7731', models.IntegerField(default=1)),
                ('f7732', models.IntegerField(default=1)),
                ('f7733', models.IntegerField(default=1)),
                ('f7734', models.IntegerField(default=1)),
                ('f7735', models.IntegerField(default=1)),
                ('f7736', models.CharField(max_length=200)),
                ('f7737', models.IntegerField(default=1)),
                ('f7738', models.CharField(max_length=200)),
                ('f7739', models.CharField(max_length=200)),
                ('f7740', models.IntegerField(default=1)),
                ('f7741', models.IntegerField(default=1)),
                ('f7742', models.IntegerField(default=1)),
                ('f7743', models.IntegerField(default=1)),
                ('f7744', models.TextField()),
                ('f7745', models.IntegerField(default=1)),
                ('f7746', models.IntegerField(default=1)),
                ('f7747', models.IntegerField(default=1)),
                ('f7748', models.IntegerField(default=1)),
                ('f7749', models.IntegerField(default=1)),
                ('f7750', models.IntegerField(default=1)),
                ('f7751', models.IntegerField(default=1)),
                ('f7752', models.TextField()),
                ('f7753', models.IntegerField(default=1)),
                ('f7754', models.IntegerField(default=1)),
                ('f7755', models.IntegerField(default=1)),
                ('f7756', models.CharField(max_length=200)),
                ('f7757', models.TextField()),
                ('f7758', models.TextField()),
                ('f7759', models.IntegerField(default=1)),
                ('f7760', models.IntegerField(default=1)),
                ('f7761', models.CharField(max_length=200)),
                ('f7762', models.TextField()),
                ('f7763', models.TextField()),
                ('f7764', models.TextField()),
                ('f7765', models.CharField(max_length=200)),
                ('f7766', models.IntegerField(default=1)),
                ('f7767', models.CharField(max_length=200)),
                ('f7768', models.TextField()),
                ('f7769', models.TextField()),
                ('f7770', models.TextField()),
                ('f7771', models.CharField(max_length=200)),
                ('f7772', models.CharField(max_length=200)),
                ('f7773', models.IntegerField(default=1)),
                ('f7774', models.TextField()),
                ('f7775', models.CharField(max_length=200)),
                ('f7776', models.CharField(max_length=200)),
                ('f7777', models.CharField(max_length=200)),
                ('f7778', models.CharField(max_length=200)),
                ('f7779', models.TextField()),
                ('f7780', models.TextField()),
                ('f7781', models.TextField()),
                ('f7782', models.TextField()),
                ('f7783', models.IntegerField(default=1)),
                ('f7784', models.IntegerField(default=1)),
                ('f7785', models.IntegerField(default=1)),
                ('f7786', models.IntegerField(default=1)),
                ('f7787', models.IntegerField(default=1)),
                ('f7788', models.TextField()),
                ('f7789', models.TextField()),
                ('f7790', models.CharField(max_length=200)),
                ('f7791', models.IntegerField(default=1)),
                ('f7792', models.IntegerField(default=1)),
                ('f7793', models.CharField(max_length=200)),
                ('f7794', models.TextField()),
                ('f7795', models.IntegerField(default=1)),
                ('f7796', models.TextField()),
                ('f7797', models.IntegerField(default=1)),
                ('f7798', models.CharField(max_length=200)),
                ('f7799', models.IntegerField(default=1)),
                ('f7800', models.IntegerField(default=1)),
                ('f7801', models.CharField(max_length=200)),
                ('f7802', models.IntegerField(default=1)),
                ('f7803', models.TextField()),
                ('f7804', models.IntegerField(default=1)),
                ('f7805', models.CharField(max_length=200)),
                ('f7806', models.TextField()),
                ('f7807', models.TextField()),
                ('f7808', models.TextField()),
                ('f7809', models.CharField(max_length=200)),
                ('f7810', models.IntegerField(default=1)),
                ('f7811', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M166',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7812', models.IntegerField(default=1)),
                ('f7813', models.CharField(max_length=200)),
                ('f7814', models.TextField()),
                ('f7815', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M167',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7816', models.CharField(max_length=200)),
                ('f7817', models.IntegerField(default=1)),
                ('f7818', models.TextField()),
                ('f7819', models.IntegerField(default=1)),
                ('f7820', models.IntegerField(default=1)),
                ('f7821', models.TextField()),
                ('f7822', models.CharField(max_length=200)),
                ('f7823', models.IntegerField(default=1)),
                ('f7824', models.IntegerField(default=1)),
                ('f7825', models.CharField(max_length=200)),
                ('f7826', models.IntegerField(default=1)),
                ('f7827', models.TextField()),
                ('f7828', models.IntegerField(default=1)),
                ('f7829', models.TextField()),
                ('f7830', models.IntegerField(default=1)),
                ('f7831', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M168',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7832', models.IntegerField(default=1)),
                ('f7833', models.CharField(max_length=200)),
                ('f7834', models.IntegerField(default=1)),
                ('f7835', models.IntegerField(default=1)),
                ('f7836', models.CharField(max_length=200)),
                ('f7837', models.IntegerField(default=1)),
                ('f7838', models.CharField(max_length=200)),
                ('f7839', models.IntegerField(default=1)),
                ('f7840', models.IntegerField(default=1)),
                ('f7841', models.CharField(max_length=200)),
                ('f7842', models.CharField(max_length=200)),
                ('f7843', models.CharField(max_length=200)),
                ('f7844', models.TextField()),
                ('f7845', models.TextField()),
                ('f7846', models.TextField()),
                ('f7847', models.TextField()),
                ('f7848', models.TextField()),
                ('f7849', models.CharField(max_length=200)),
                ('f7850', models.IntegerField(default=1)),
                ('f7851', models.CharField(max_length=200)),
                ('f7852', models.CharField(max_length=200)),
                ('f7853', models.IntegerField(default=1)),
                ('f7854', models.TextField()),
                ('f7855', models.CharField(max_length=200)),
                ('f7856', models.IntegerField(default=1)),
                ('f7857', models.IntegerField(default=1)),
                ('f7858', models.TextField()),
                ('f7859', models.CharField(max_length=200)),
                ('f7860', models.CharField(max_length=200)),
                ('f7861', models.TextField()),
                ('f7862', models.IntegerField(default=1)),
                ('f7863', models.TextField()),
                ('f7864', models.TextField()),
                ('f7865', models.TextField()),
                ('f7866', models.CharField(max_length=200)),
                ('f7867', models.IntegerField(default=1)),
                ('f7868', models.IntegerField(default=1)),
                ('f7869', models.TextField()),
                ('f7870', models.IntegerField(default=1)),
                ('f7871', models.IntegerField(default=1)),
                ('f7872', models.TextField()),
                ('f7873', models.IntegerField(default=1)),
                ('f7874', models.TextField()),
                ('f7875', models.IntegerField(default=1)),
                ('f7876', models.IntegerField(default=1)),
                ('f7877', models.IntegerField(default=1)),
                ('f7878', models.CharField(max_length=200)),
                ('f7879', models.IntegerField(default=1)),
                ('f7880', models.CharField(max_length=200)),
                ('f7881', models.IntegerField(default=1)),
                ('f7882', models.IntegerField(default=1)),
                ('f7883', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M169',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7884', models.IntegerField(default=1)),
                ('f7885', models.TextField()),
                ('f7886', models.CharField(max_length=200)),
                ('f7887', models.CharField(max_length=200)),
                ('f7888', models.TextField()),
                ('f7889', models.TextField()),
                ('f7890', models.TextField()),
                ('f7891', models.CharField(max_length=200)),
                ('f7892', models.IntegerField(default=1)),
                ('f7893', models.CharField(max_length=200)),
                ('f7894', models.CharField(max_length=200)),
                ('f7895', models.TextField()),
                ('f7896', models.IntegerField(default=1)),
                ('f7897', models.CharField(max_length=200)),
                ('f7898', models.TextField()),
                ('f7899', models.IntegerField(default=1)),
                ('f7900', models.IntegerField(default=1)),
                ('f7901', models.IntegerField(default=1)),
                ('f7902', models.CharField(max_length=200)),
                ('f7903', models.IntegerField(default=1)),
                ('f7904', models.IntegerField(default=1)),
                ('f7905', models.TextField()),
                ('f7906', models.TextField()),
                ('f7907', models.IntegerField(default=1)),
                ('f7908', models.IntegerField(default=1)),
                ('f7909', models.IntegerField(default=1)),
                ('f7910', models.TextField()),
                ('f7911', models.TextField()),
                ('f7912', models.TextField()),
                ('f7913', models.TextField()),
                ('f7914', models.IntegerField(default=1)),
                ('f7915', models.IntegerField(default=1)),
                ('f7916', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M170',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f7917', models.CharField(max_length=200)),
                ('f7918', models.IntegerField(default=1)),
                ('f7919', models.TextField()),
                ('f7920', models.CharField(max_length=200)),
                ('f7921', models.IntegerField(default=1)),
                ('f7922', models.IntegerField(default=1)),
                ('f7923', models.CharField(max_length=200)),
                ('f7924', models.TextField()),
                ('f7925', models.TextField()),
                ('f7926', models.TextField()),
                ('f7927', models.TextField()),
                ('f7928', models.IntegerField(default=1)),
                ('f7929', models.IntegerField(default=1)),
                ('f7930', models.CharField(max_length=200)),
                ('f7931', models.CharField(max_length=200)),
                ('f7932', models.IntegerField(default=1)),
                ('f7933', models.TextField()),
                ('f7934', models.CharField(max_length=200)),
                ('f7935', models.CharField(max_length=200)),
                ('f7936', models.TextField()),
                ('f7937', models.CharField(max_length=200)),
                ('f7938', models.CharField(max_length=200)),
                ('f7939', models.TextField()),
                ('f7940', models.TextField()),
                ('f7941', models.CharField(max_length=200)),
                ('f7942', models.TextField()),
                ('f7943', models.CharField(max_length=200)),
                ('f7944', models.TextField()),
                ('f7945', models.IntegerField(default=1)),
                ('f7946', models.IntegerField(default=1)),
                ('f7947', models.TextField()),
                ('f7948', models.CharField(max_length=200)),
                ('f7949', models.IntegerField(default=1)),
                ('f7950', models.IntegerField(default=1)),
                ('f7951', models.CharField(max_length=200)),
                ('f7952', models.TextField()),
                ('f7953', models.IntegerField(default=1)),
                ('f7954', models.TextField()),
                ('f7955', models.IntegerField(default=1)),
            ],
        ),
    ]
