# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M21',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f968', models.CharField(max_length=200)),
                ('f969', models.TextField()),
                ('f970', models.IntegerField(default=1)),
                ('f971', models.TextField()),
                ('f972', models.IntegerField(default=1)),
                ('f973', models.TextField()),
                ('f974', models.CharField(max_length=200)),
                ('f975', models.CharField(max_length=200)),
                ('f976', models.TextField()),
                ('f977', models.CharField(max_length=200)),
                ('f978', models.IntegerField(default=1)),
                ('f979', models.CharField(max_length=200)),
                ('f980', models.IntegerField(default=1)),
                ('f981', models.IntegerField(default=1)),
                ('f982', models.TextField()),
                ('f983', models.CharField(max_length=200)),
                ('f984', models.CharField(max_length=200)),
                ('f985', models.IntegerField(default=1)),
                ('f986', models.TextField()),
                ('f987', models.CharField(max_length=200)),
                ('f988', models.TextField()),
                ('f989', models.TextField()),
                ('f990', models.CharField(max_length=200)),
                ('f991', models.CharField(max_length=200)),
                ('f992', models.TextField()),
                ('f993', models.TextField()),
                ('f994', models.IntegerField(default=1)),
                ('f995', models.CharField(max_length=200)),
                ('f996', models.IntegerField(default=1)),
                ('f997', models.TextField()),
                ('f998', models.TextField()),
                ('f999', models.IntegerField(default=1)),
                ('f1000', models.IntegerField(default=1)),
                ('f1001', models.TextField()),
                ('f1002', models.CharField(max_length=200)),
                ('f1003', models.CharField(max_length=200)),
                ('f1004', models.CharField(max_length=200)),
                ('f1005', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M22',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1006', models.CharField(max_length=200)),
                ('f1007', models.IntegerField(default=1)),
                ('f1008', models.IntegerField(default=1)),
                ('f1009', models.CharField(max_length=200)),
                ('f1010', models.TextField()),
                ('f1011', models.IntegerField(default=1)),
                ('f1012', models.IntegerField(default=1)),
                ('f1013', models.TextField()),
                ('f1014', models.CharField(max_length=200)),
                ('f1015', models.CharField(max_length=200)),
                ('f1016', models.IntegerField(default=1)),
                ('f1017', models.TextField()),
                ('f1018', models.CharField(max_length=200)),
                ('f1019', models.TextField()),
                ('f1020', models.CharField(max_length=200)),
                ('f1021', models.CharField(max_length=200)),
                ('f1022', models.CharField(max_length=200)),
                ('f1023', models.CharField(max_length=200)),
                ('f1024', models.IntegerField(default=1)),
                ('f1025', models.CharField(max_length=200)),
                ('f1026', models.TextField()),
                ('f1027', models.CharField(max_length=200)),
                ('f1028', models.TextField()),
                ('f1029', models.IntegerField(default=1)),
                ('f1030', models.IntegerField(default=1)),
                ('f1031', models.CharField(max_length=200)),
                ('f1032', models.IntegerField(default=1)),
                ('f1033', models.TextField()),
                ('f1034', models.TextField()),
                ('f1035', models.TextField()),
                ('f1036', models.CharField(max_length=200)),
                ('f1037', models.IntegerField(default=1)),
                ('f1038', models.CharField(max_length=200)),
                ('f1039', models.TextField()),
                ('f1040', models.CharField(max_length=200)),
                ('f1041', models.IntegerField(default=1)),
                ('f1042', models.CharField(max_length=200)),
                ('f1043', models.IntegerField(default=1)),
                ('f1044', models.CharField(max_length=200)),
                ('f1045', models.IntegerField(default=1)),
                ('f1046', models.TextField()),
                ('f1047', models.CharField(max_length=200)),
                ('f1048', models.IntegerField(default=1)),
                ('f1049', models.TextField()),
                ('f1050', models.CharField(max_length=200)),
                ('f1051', models.CharField(max_length=200)),
                ('f1052', models.IntegerField(default=1)),
                ('f1053', models.TextField()),
                ('f1054', models.TextField()),
                ('f1055', models.CharField(max_length=200)),
                ('f1056', models.TextField()),
                ('f1057', models.CharField(max_length=200)),
                ('f1058', models.TextField()),
                ('f1059', models.TextField()),
                ('f1060', models.IntegerField(default=1)),
                ('f1061', models.TextField()),
                ('f1062', models.TextField()),
                ('f1063', models.TextField()),
                ('f1064', models.IntegerField(default=1)),
                ('f1065', models.CharField(max_length=200)),
                ('f1066', models.CharField(max_length=200)),
                ('f1067', models.IntegerField(default=1)),
                ('f1068', models.TextField()),
                ('f1069', models.CharField(max_length=200)),
                ('f1070', models.IntegerField(default=1)),
                ('f1071', models.CharField(max_length=200)),
                ('f1072', models.TextField()),
                ('f1073', models.CharField(max_length=200)),
                ('f1074', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M23',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1075', models.IntegerField(default=1)),
                ('f1076', models.IntegerField(default=1)),
                ('f1077', models.IntegerField(default=1)),
                ('f1078', models.TextField()),
                ('f1079', models.TextField()),
                ('f1080', models.IntegerField(default=1)),
                ('f1081', models.TextField()),
                ('f1082', models.TextField()),
                ('f1083', models.TextField()),
                ('f1084', models.TextField()),
                ('f1085', models.TextField()),
                ('f1086', models.TextField()),
                ('f1087', models.TextField()),
                ('f1088', models.IntegerField(default=1)),
                ('f1089', models.CharField(max_length=200)),
                ('f1090', models.IntegerField(default=1)),
                ('f1091', models.CharField(max_length=200)),
                ('f1092', models.IntegerField(default=1)),
                ('f1093', models.CharField(max_length=200)),
                ('f1094', models.TextField()),
                ('f1095', models.IntegerField(default=1)),
                ('f1096', models.CharField(max_length=200)),
                ('f1097', models.TextField()),
                ('f1098', models.CharField(max_length=200)),
                ('f1099', models.TextField()),
                ('f1100', models.TextField()),
                ('f1101', models.CharField(max_length=200)),
                ('f1102', models.CharField(max_length=200)),
                ('f1103', models.TextField()),
                ('f1104', models.CharField(max_length=200)),
                ('f1105', models.IntegerField(default=1)),
                ('f1106', models.CharField(max_length=200)),
                ('f1107', models.CharField(max_length=200)),
                ('f1108', models.CharField(max_length=200)),
                ('f1109', models.CharField(max_length=200)),
                ('f1110', models.IntegerField(default=1)),
                ('f1111', models.IntegerField(default=1)),
                ('f1112', models.IntegerField(default=1)),
                ('f1113', models.TextField()),
                ('f1114', models.TextField()),
                ('f1115', models.TextField()),
                ('f1116', models.CharField(max_length=200)),
                ('f1117', models.TextField()),
                ('f1118', models.IntegerField(default=1)),
                ('f1119', models.IntegerField(default=1)),
                ('f1120', models.CharField(max_length=200)),
                ('f1121', models.IntegerField(default=1)),
                ('f1122', models.IntegerField(default=1)),
                ('f1123', models.TextField()),
                ('f1124', models.CharField(max_length=200)),
                ('f1125', models.CharField(max_length=200)),
                ('f1126', models.IntegerField(default=1)),
                ('f1127', models.TextField()),
                ('f1128', models.CharField(max_length=200)),
                ('f1129', models.TextField()),
                ('f1130', models.IntegerField(default=1)),
                ('f1131', models.IntegerField(default=1)),
                ('f1132', models.CharField(max_length=200)),
                ('f1133', models.IntegerField(default=1)),
                ('f1134', models.TextField()),
                ('f1135', models.TextField()),
                ('f1136', models.CharField(max_length=200)),
                ('f1137', models.TextField()),
                ('f1138', models.CharField(max_length=200)),
                ('f1139', models.CharField(max_length=200)),
                ('f1140', models.CharField(max_length=200)),
                ('f1141', models.IntegerField(default=1)),
                ('f1142', models.IntegerField(default=1)),
                ('f1143', models.IntegerField(default=1)),
                ('f1144', models.TextField()),
                ('f1145', models.TextField()),
                ('f1146', models.CharField(max_length=200)),
                ('f1147', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M24',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1148', models.TextField()),
                ('f1149', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M25',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1150', models.IntegerField(default=1)),
                ('f1151', models.IntegerField(default=1)),
                ('f1152', models.CharField(max_length=200)),
                ('f1153', models.TextField()),
                ('f1154', models.CharField(max_length=200)),
                ('f1155', models.CharField(max_length=200)),
                ('f1156', models.CharField(max_length=200)),
                ('f1157', models.TextField()),
                ('f1158', models.IntegerField(default=1)),
                ('f1159', models.CharField(max_length=200)),
                ('f1160', models.IntegerField(default=1)),
                ('f1161', models.TextField()),
                ('f1162', models.TextField()),
                ('f1163', models.CharField(max_length=200)),
                ('f1164', models.IntegerField(default=1)),
                ('f1165', models.CharField(max_length=200)),
                ('f1166', models.CharField(max_length=200)),
                ('f1167', models.IntegerField(default=1)),
                ('f1168', models.TextField()),
                ('f1169', models.IntegerField(default=1)),
                ('f1170', models.CharField(max_length=200)),
                ('f1171', models.TextField()),
                ('f1172', models.IntegerField(default=1)),
                ('f1173', models.TextField()),
                ('f1174', models.TextField()),
                ('f1175', models.IntegerField(default=1)),
                ('f1176', models.TextField()),
                ('f1177', models.IntegerField(default=1)),
                ('f1178', models.IntegerField(default=1)),
                ('f1179', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M26',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1180', models.CharField(max_length=200)),
                ('f1181', models.CharField(max_length=200)),
                ('f1182', models.TextField()),
                ('f1183', models.TextField()),
                ('f1184', models.CharField(max_length=200)),
                ('f1185', models.IntegerField(default=1)),
                ('f1186', models.TextField()),
                ('f1187', models.IntegerField(default=1)),
                ('f1188', models.IntegerField(default=1)),
                ('f1189', models.IntegerField(default=1)),
                ('f1190', models.CharField(max_length=200)),
                ('f1191', models.CharField(max_length=200)),
                ('f1192', models.IntegerField(default=1)),
                ('f1193', models.CharField(max_length=200)),
                ('f1194', models.TextField()),
                ('f1195', models.TextField()),
                ('f1196', models.CharField(max_length=200)),
                ('f1197', models.IntegerField(default=1)),
                ('f1198', models.IntegerField(default=1)),
                ('f1199', models.TextField()),
                ('f1200', models.CharField(max_length=200)),
                ('f1201', models.IntegerField(default=1)),
                ('f1202', models.IntegerField(default=1)),
                ('f1203', models.CharField(max_length=200)),
                ('f1204', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M27',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1205', models.CharField(max_length=200)),
                ('f1206', models.CharField(max_length=200)),
                ('f1207', models.IntegerField(default=1)),
                ('f1208', models.TextField()),
                ('f1209', models.IntegerField(default=1)),
                ('f1210', models.TextField()),
                ('f1211', models.CharField(max_length=200)),
                ('f1212', models.CharField(max_length=200)),
                ('f1213', models.CharField(max_length=200)),
                ('f1214', models.TextField()),
                ('f1215', models.TextField()),
                ('f1216', models.TextField()),
                ('f1217', models.TextField()),
                ('f1218', models.IntegerField(default=1)),
                ('f1219', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M28',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1220', models.IntegerField(default=1)),
                ('f1221', models.IntegerField(default=1)),
                ('f1222', models.CharField(max_length=200)),
                ('f1223', models.CharField(max_length=200)),
                ('f1224', models.CharField(max_length=200)),
                ('f1225', models.IntegerField(default=1)),
                ('f1226', models.IntegerField(default=1)),
                ('f1227', models.TextField()),
                ('f1228', models.IntegerField(default=1)),
                ('f1229', models.CharField(max_length=200)),
                ('f1230', models.CharField(max_length=200)),
                ('f1231', models.CharField(max_length=200)),
                ('f1232', models.IntegerField(default=1)),
                ('f1233', models.CharField(max_length=200)),
                ('f1234', models.TextField()),
                ('f1235', models.TextField()),
                ('f1236', models.IntegerField(default=1)),
                ('f1237', models.CharField(max_length=200)),
                ('f1238', models.IntegerField(default=1)),
                ('f1239', models.CharField(max_length=200)),
                ('f1240', models.IntegerField(default=1)),
                ('f1241', models.CharField(max_length=200)),
                ('f1242', models.IntegerField(default=1)),
                ('f1243', models.TextField()),
                ('f1244', models.CharField(max_length=200)),
                ('f1245', models.IntegerField(default=1)),
                ('f1246', models.CharField(max_length=200)),
                ('f1247', models.TextField()),
                ('f1248', models.CharField(max_length=200)),
                ('f1249', models.IntegerField(default=1)),
                ('f1250', models.IntegerField(default=1)),
                ('f1251', models.CharField(max_length=200)),
                ('f1252', models.IntegerField(default=1)),
                ('f1253', models.CharField(max_length=200)),
                ('f1254', models.CharField(max_length=200)),
                ('f1255', models.TextField()),
                ('f1256', models.CharField(max_length=200)),
                ('f1257', models.CharField(max_length=200)),
                ('f1258', models.IntegerField(default=1)),
                ('f1259', models.IntegerField(default=1)),
                ('f1260', models.CharField(max_length=200)),
                ('f1261', models.IntegerField(default=1)),
                ('f1262', models.IntegerField(default=1)),
                ('f1263', models.CharField(max_length=200)),
                ('f1264', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M29',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1265', models.TextField()),
                ('f1266', models.TextField()),
                ('f1267', models.IntegerField(default=1)),
                ('f1268', models.TextField()),
                ('f1269', models.TextField()),
                ('f1270', models.CharField(max_length=200)),
                ('f1271', models.CharField(max_length=200)),
                ('f1272', models.CharField(max_length=200)),
                ('f1273', models.CharField(max_length=200)),
                ('f1274', models.IntegerField(default=1)),
                ('f1275', models.TextField()),
                ('f1276', models.IntegerField(default=1)),
                ('f1277', models.TextField()),
                ('f1278', models.IntegerField(default=1)),
                ('f1279', models.TextField()),
                ('f1280', models.IntegerField(default=1)),
                ('f1281', models.CharField(max_length=200)),
                ('f1282', models.TextField()),
                ('f1283', models.IntegerField(default=1)),
                ('f1284', models.CharField(max_length=200)),
                ('f1285', models.IntegerField(default=1)),
                ('f1286', models.IntegerField(default=1)),
                ('f1287', models.CharField(max_length=200)),
                ('f1288', models.IntegerField(default=1)),
                ('f1289', models.IntegerField(default=1)),
                ('f1290', models.IntegerField(default=1)),
                ('f1291', models.IntegerField(default=1)),
                ('f1292', models.CharField(max_length=200)),
                ('f1293', models.TextField()),
                ('f1294', models.IntegerField(default=1)),
                ('f1295', models.TextField()),
                ('f1296', models.CharField(max_length=200)),
                ('f1297', models.TextField()),
                ('f1298', models.TextField()),
                ('f1299', models.TextField()),
                ('f1300', models.TextField()),
                ('f1301', models.IntegerField(default=1)),
                ('f1302', models.TextField()),
                ('f1303', models.CharField(max_length=200)),
                ('f1304', models.TextField()),
                ('f1305', models.CharField(max_length=200)),
                ('f1306', models.TextField()),
                ('f1307', models.CharField(max_length=200)),
                ('f1308', models.IntegerField(default=1)),
                ('f1309', models.TextField()),
                ('f1310', models.CharField(max_length=200)),
                ('f1311', models.TextField()),
                ('f1312', models.IntegerField(default=1)),
                ('f1313', models.TextField()),
                ('f1314', models.TextField()),
                ('f1315', models.IntegerField(default=1)),
                ('f1316', models.IntegerField(default=1)),
                ('f1317', models.IntegerField(default=1)),
                ('f1318', models.CharField(max_length=200)),
                ('f1319', models.CharField(max_length=200)),
                ('f1320', models.CharField(max_length=200)),
                ('f1321', models.IntegerField(default=1)),
                ('f1322', models.IntegerField(default=1)),
                ('f1323', models.IntegerField(default=1)),
                ('f1324', models.TextField()),
                ('f1325', models.CharField(max_length=200)),
                ('f1326', models.TextField()),
                ('f1327', models.IntegerField(default=1)),
                ('f1328', models.CharField(max_length=200)),
                ('f1329', models.TextField()),
                ('f1330', models.TextField()),
                ('f1331', models.CharField(max_length=200)),
                ('f1332', models.TextField()),
                ('f1333', models.CharField(max_length=200)),
                ('f1334', models.TextField()),
                ('f1335', models.TextField()),
                ('f1336', models.TextField()),
                ('f1337', models.CharField(max_length=200)),
                ('f1338', models.IntegerField(default=1)),
                ('f1339', models.TextField()),
                ('f1340', models.CharField(max_length=200)),
                ('f1341', models.CharField(max_length=200)),
                ('f1342', models.IntegerField(default=1)),
                ('f1343', models.IntegerField(default=1)),
                ('f1344', models.IntegerField(default=1)),
                ('f1345', models.IntegerField(default=1)),
                ('f1346', models.CharField(max_length=200)),
                ('f1347', models.CharField(max_length=200)),
                ('f1348', models.IntegerField(default=1)),
                ('f1349', models.IntegerField(default=1)),
                ('f1350', models.CharField(max_length=200)),
                ('f1351', models.CharField(max_length=200)),
                ('f1352', models.IntegerField(default=1)),
                ('f1353', models.IntegerField(default=1)),
                ('f1354', models.IntegerField(default=1)),
                ('f1355', models.CharField(max_length=200)),
                ('f1356', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M30',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1357', models.IntegerField(default=1)),
                ('f1358', models.CharField(max_length=200)),
                ('f1359', models.IntegerField(default=1)),
                ('f1360', models.TextField()),
                ('f1361', models.TextField()),
                ('f1362', models.IntegerField(default=1)),
                ('f1363', models.CharField(max_length=200)),
                ('f1364', models.IntegerField(default=1)),
                ('f1365', models.CharField(max_length=200)),
                ('f1366', models.CharField(max_length=200)),
                ('f1367', models.CharField(max_length=200)),
                ('f1368', models.CharField(max_length=200)),
                ('f1369', models.CharField(max_length=200)),
                ('f1370', models.CharField(max_length=200)),
                ('f1371', models.IntegerField(default=1)),
                ('f1372', models.IntegerField(default=1)),
                ('f1373', models.IntegerField(default=1)),
                ('f1374', models.CharField(max_length=200)),
                ('f1375', models.IntegerField(default=1)),
                ('f1376', models.TextField()),
                ('f1377', models.TextField()),
                ('f1378', models.TextField()),
                ('f1379', models.IntegerField(default=1)),
                ('f1380', models.CharField(max_length=200)),
                ('f1381', models.IntegerField(default=1)),
                ('f1382', models.TextField()),
                ('f1383', models.TextField()),
                ('f1384', models.TextField()),
                ('f1385', models.CharField(max_length=200)),
                ('f1386', models.IntegerField(default=1)),
                ('f1387', models.CharField(max_length=200)),
                ('f1388', models.CharField(max_length=200)),
                ('f1389', models.IntegerField(default=1)),
                ('f1390', models.TextField()),
                ('f1391', models.CharField(max_length=200)),
                ('f1392', models.TextField()),
                ('f1393', models.CharField(max_length=200)),
                ('f1394', models.CharField(max_length=200)),
                ('f1395', models.IntegerField(default=1)),
                ('f1396', models.CharField(max_length=200)),
                ('f1397', models.CharField(max_length=200)),
                ('f1398', models.IntegerField(default=1)),
                ('f1399', models.TextField()),
                ('f1400', models.TextField()),
                ('f1401', models.TextField()),
                ('f1402', models.TextField()),
                ('f1403', models.CharField(max_length=200)),
                ('f1404', models.IntegerField(default=1)),
                ('f1405', models.IntegerField(default=1)),
                ('f1406', models.CharField(max_length=200)),
                ('f1407', models.TextField()),
                ('f1408', models.CharField(max_length=200)),
                ('f1409', models.IntegerField(default=1)),
                ('f1410', models.IntegerField(default=1)),
                ('f1411', models.IntegerField(default=1)),
                ('f1412', models.TextField()),
                ('f1413', models.TextField()),
                ('f1414', models.TextField()),
                ('f1415', models.IntegerField(default=1)),
                ('f1416', models.CharField(max_length=200)),
                ('f1417', models.IntegerField(default=1)),
                ('f1418', models.CharField(max_length=200)),
                ('f1419', models.IntegerField(default=1)),
                ('f1420', models.TextField()),
                ('f1421', models.TextField()),
                ('f1422', models.IntegerField(default=1)),
                ('f1423', models.CharField(max_length=200)),
                ('f1424', models.IntegerField(default=1)),
                ('f1425', models.TextField()),
                ('f1426', models.IntegerField(default=1)),
                ('f1427', models.TextField()),
                ('f1428', models.CharField(max_length=200)),
                ('f1429', models.TextField()),
                ('f1430', models.CharField(max_length=200)),
                ('f1431', models.TextField()),
            ],
        ),
    ]
