# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.CharField(max_length=200)),
                ('f4', models.IntegerField(default=1)),
                ('f5', models.TextField()),
                ('f6', models.CharField(max_length=200)),
                ('f7', models.TextField()),
                ('f8', models.TextField()),
                ('f9', models.TextField()),
                ('f10', models.CharField(max_length=200)),
                ('f11', models.TextField()),
                ('f12', models.CharField(max_length=200)),
                ('f13', models.CharField(max_length=200)),
                ('f14', models.CharField(max_length=200)),
                ('f15', models.TextField()),
                ('f16', models.CharField(max_length=200)),
                ('f17', models.IntegerField(default=1)),
                ('f18', models.IntegerField(default=1)),
                ('f19', models.IntegerField(default=1)),
                ('f20', models.IntegerField(default=1)),
                ('f21', models.IntegerField(default=1)),
                ('f22', models.CharField(max_length=200)),
                ('f23', models.IntegerField(default=1)),
                ('f24', models.IntegerField(default=1)),
                ('f25', models.TextField()),
                ('f26', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M10',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f371', models.IntegerField(default=1)),
                ('f372', models.TextField()),
                ('f373', models.TextField()),
                ('f374', models.IntegerField(default=1)),
                ('f375', models.IntegerField(default=1)),
                ('f376', models.IntegerField(default=1)),
                ('f377', models.IntegerField(default=1)),
                ('f378', models.CharField(max_length=200)),
                ('f379', models.CharField(max_length=200)),
                ('f380', models.TextField()),
                ('f381', models.IntegerField(default=1)),
                ('f382', models.TextField()),
                ('f383', models.TextField()),
                ('f384', models.IntegerField(default=1)),
                ('f385', models.IntegerField(default=1)),
                ('f386', models.CharField(max_length=200)),
                ('f387', models.IntegerField(default=1)),
                ('f388', models.CharField(max_length=200)),
                ('f389', models.TextField()),
                ('f390', models.IntegerField(default=1)),
                ('f391', models.IntegerField(default=1)),
                ('f392', models.IntegerField(default=1)),
                ('f393', models.IntegerField(default=1)),
                ('f394', models.IntegerField(default=1)),
                ('f395', models.IntegerField(default=1)),
                ('f396', models.IntegerField(default=1)),
                ('f397', models.CharField(max_length=200)),
                ('f398', models.CharField(max_length=200)),
                ('f399', models.TextField()),
                ('f400', models.CharField(max_length=200)),
                ('f401', models.CharField(max_length=200)),
                ('f402', models.IntegerField(default=1)),
                ('f403', models.CharField(max_length=200)),
                ('f404', models.CharField(max_length=200)),
                ('f405', models.IntegerField(default=1)),
                ('f406', models.CharField(max_length=200)),
                ('f407', models.TextField()),
                ('f408', models.IntegerField(default=1)),
                ('f409', models.TextField()),
                ('f410', models.IntegerField(default=1)),
                ('f411', models.CharField(max_length=200)),
                ('f412', models.IntegerField(default=1)),
                ('f413', models.CharField(max_length=200)),
                ('f414', models.CharField(max_length=200)),
                ('f415', models.TextField()),
                ('f416', models.TextField()),
                ('f417', models.CharField(max_length=200)),
                ('f418', models.IntegerField(default=1)),
                ('f419', models.CharField(max_length=200)),
                ('f420', models.CharField(max_length=200)),
                ('f421', models.TextField()),
                ('f422', models.CharField(max_length=200)),
                ('f423', models.CharField(max_length=200)),
                ('f424', models.TextField()),
                ('f425', models.CharField(max_length=200)),
                ('f426', models.IntegerField(default=1)),
                ('f427', models.CharField(max_length=200)),
                ('f428', models.TextField()),
                ('f429', models.TextField()),
                ('f430', models.CharField(max_length=200)),
                ('f431', models.CharField(max_length=200)),
                ('f432', models.IntegerField(default=1)),
                ('f433', models.CharField(max_length=200)),
                ('f434', models.IntegerField(default=1)),
                ('f435', models.CharField(max_length=200)),
                ('f436', models.CharField(max_length=200)),
                ('f437', models.IntegerField(default=1)),
                ('f438', models.IntegerField(default=1)),
                ('f439', models.IntegerField(default=1)),
                ('f440', models.IntegerField(default=1)),
                ('f441', models.IntegerField(default=1)),
                ('f442', models.CharField(max_length=200)),
                ('f443', models.TextField()),
                ('f444', models.IntegerField(default=1)),
                ('f445', models.IntegerField(default=1)),
                ('f446', models.IntegerField(default=1)),
                ('f447', models.CharField(max_length=200)),
                ('f448', models.IntegerField(default=1)),
                ('f449', models.CharField(max_length=200)),
                ('f450', models.CharField(max_length=200)),
                ('f451', models.CharField(max_length=200)),
                ('f452', models.IntegerField(default=1)),
                ('f453', models.CharField(max_length=200)),
                ('f454', models.TextField()),
                ('f455', models.TextField()),
                ('f456', models.CharField(max_length=200)),
                ('f457', models.IntegerField(default=1)),
                ('f458', models.CharField(max_length=200)),
                ('f459', models.CharField(max_length=200)),
                ('f460', models.TextField()),
                ('f461', models.IntegerField(default=1)),
                ('f462', models.TextField()),
                ('f463', models.IntegerField(default=1)),
                ('f464', models.TextField()),
                ('f465', models.TextField()),
                ('f466', models.IntegerField(default=1)),
                ('f467', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f27', models.IntegerField(default=1)),
                ('f28', models.IntegerField(default=1)),
                ('f29', models.IntegerField(default=1)),
                ('f30', models.TextField()),
                ('f31', models.TextField()),
                ('f32', models.IntegerField(default=1)),
                ('f33', models.IntegerField(default=1)),
                ('f34', models.TextField()),
                ('f35', models.IntegerField(default=1)),
                ('f36', models.TextField()),
                ('f37', models.IntegerField(default=1)),
                ('f38', models.CharField(max_length=200)),
                ('f39', models.CharField(max_length=200)),
                ('f40', models.CharField(max_length=200)),
                ('f41', models.IntegerField(default=1)),
                ('f42', models.TextField()),
                ('f43', models.CharField(max_length=200)),
                ('f44', models.IntegerField(default=1)),
                ('f45', models.CharField(max_length=200)),
                ('f46', models.IntegerField(default=1)),
                ('f47', models.CharField(max_length=200)),
                ('f48', models.IntegerField(default=1)),
                ('f49', models.TextField()),
                ('f50', models.IntegerField(default=1)),
                ('f51', models.TextField()),
                ('f52', models.TextField()),
                ('f53', models.IntegerField(default=1)),
                ('f54', models.TextField()),
                ('f55', models.IntegerField(default=1)),
                ('f56', models.IntegerField(default=1)),
                ('f57', models.TextField()),
                ('f58', models.IntegerField(default=1)),
                ('f59', models.CharField(max_length=200)),
                ('f60', models.TextField()),
                ('f61', models.TextField()),
                ('f62', models.CharField(max_length=200)),
                ('f63', models.TextField()),
                ('f64', models.CharField(max_length=200)),
                ('f65', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f66', models.TextField()),
                ('f67', models.CharField(max_length=200)),
                ('f68', models.TextField()),
                ('f69', models.TextField()),
                ('f70', models.IntegerField(default=1)),
                ('f71', models.CharField(max_length=200)),
                ('f72', models.TextField()),
                ('f73', models.TextField()),
                ('f74', models.IntegerField(default=1)),
                ('f75', models.CharField(max_length=200)),
                ('f76', models.IntegerField(default=1)),
                ('f77', models.IntegerField(default=1)),
                ('f78', models.CharField(max_length=200)),
                ('f79', models.IntegerField(default=1)),
                ('f80', models.CharField(max_length=200)),
                ('f81', models.TextField()),
                ('f82', models.TextField()),
                ('f83', models.TextField()),
                ('f84', models.IntegerField(default=1)),
                ('f85', models.IntegerField(default=1)),
                ('f86', models.CharField(max_length=200)),
                ('f87', models.CharField(max_length=200)),
                ('f88', models.IntegerField(default=1)),
                ('f89', models.CharField(max_length=200)),
                ('f90', models.TextField()),
                ('f91', models.CharField(max_length=200)),
                ('f92', models.TextField()),
                ('f93', models.TextField()),
                ('f94', models.TextField()),
                ('f95', models.TextField()),
                ('f96', models.TextField()),
                ('f97', models.CharField(max_length=200)),
                ('f98', models.CharField(max_length=200)),
                ('f99', models.IntegerField(default=1)),
                ('f100', models.TextField()),
                ('f101', models.CharField(max_length=200)),
                ('f102', models.TextField()),
                ('f103', models.CharField(max_length=200)),
                ('f104', models.TextField()),
                ('f105', models.TextField()),
                ('f106', models.TextField()),
                ('f107', models.TextField()),
                ('f108', models.TextField()),
                ('f109', models.IntegerField(default=1)),
                ('f110', models.IntegerField(default=1)),
                ('f111', models.IntegerField(default=1)),
                ('f112', models.IntegerField(default=1)),
                ('f113', models.CharField(max_length=200)),
                ('f114', models.IntegerField(default=1)),
                ('f115', models.IntegerField(default=1)),
                ('f116', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f117', models.CharField(max_length=200)),
                ('f118', models.TextField()),
                ('f119', models.CharField(max_length=200)),
                ('f120', models.IntegerField(default=1)),
                ('f121', models.CharField(max_length=200)),
                ('f122', models.TextField()),
                ('f123', models.TextField()),
                ('f124', models.CharField(max_length=200)),
                ('f125', models.IntegerField(default=1)),
                ('f126', models.CharField(max_length=200)),
                ('f127', models.IntegerField(default=1)),
                ('f128', models.CharField(max_length=200)),
                ('f129', models.TextField()),
                ('f130', models.TextField()),
                ('f131', models.TextField()),
                ('f132', models.TextField()),
                ('f133', models.IntegerField(default=1)),
                ('f134', models.TextField()),
                ('f135', models.CharField(max_length=200)),
                ('f136', models.TextField()),
                ('f137', models.CharField(max_length=200)),
                ('f138', models.IntegerField(default=1)),
                ('f139', models.IntegerField(default=1)),
                ('f140', models.TextField()),
                ('f141', models.CharField(max_length=200)),
                ('f142', models.CharField(max_length=200)),
                ('f143', models.IntegerField(default=1)),
                ('f144', models.CharField(max_length=200)),
                ('f145', models.IntegerField(default=1)),
                ('f146', models.CharField(max_length=200)),
                ('f147', models.IntegerField(default=1)),
                ('f148', models.CharField(max_length=200)),
                ('f149', models.TextField()),
                ('f150', models.IntegerField(default=1)),
                ('f151', models.TextField()),
                ('f152', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M5',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f153', models.CharField(max_length=200)),
                ('f154', models.IntegerField(default=1)),
                ('f155', models.CharField(max_length=200)),
                ('f156', models.CharField(max_length=200)),
                ('f157', models.TextField()),
                ('f158', models.IntegerField(default=1)),
                ('f159', models.TextField()),
                ('f160', models.CharField(max_length=200)),
                ('f161', models.IntegerField(default=1)),
                ('f162', models.CharField(max_length=200)),
                ('f163', models.CharField(max_length=200)),
                ('f164', models.CharField(max_length=200)),
                ('f165', models.CharField(max_length=200)),
                ('f166', models.CharField(max_length=200)),
                ('f167', models.IntegerField(default=1)),
                ('f168', models.CharField(max_length=200)),
                ('f169', models.CharField(max_length=200)),
                ('f170', models.CharField(max_length=200)),
                ('f171', models.TextField()),
                ('f172', models.IntegerField(default=1)),
                ('f173', models.TextField()),
                ('f174', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M6',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f175', models.CharField(max_length=200)),
                ('f176', models.IntegerField(default=1)),
                ('f177', models.CharField(max_length=200)),
                ('f178', models.TextField()),
                ('f179', models.TextField()),
                ('f180', models.IntegerField(default=1)),
                ('f181', models.IntegerField(default=1)),
                ('f182', models.CharField(max_length=200)),
                ('f183', models.CharField(max_length=200)),
                ('f184', models.TextField()),
                ('f185', models.IntegerField(default=1)),
                ('f186', models.CharField(max_length=200)),
                ('f187', models.TextField()),
                ('f188', models.IntegerField(default=1)),
                ('f189', models.CharField(max_length=200)),
                ('f190', models.IntegerField(default=1)),
                ('f191', models.IntegerField(default=1)),
                ('f192', models.IntegerField(default=1)),
                ('f193', models.CharField(max_length=200)),
                ('f194', models.CharField(max_length=200)),
                ('f195', models.CharField(max_length=200)),
                ('f196', models.TextField()),
                ('f197', models.IntegerField(default=1)),
                ('f198', models.IntegerField(default=1)),
                ('f199', models.TextField()),
                ('f200', models.IntegerField(default=1)),
                ('f201', models.TextField()),
                ('f202', models.IntegerField(default=1)),
                ('f203', models.CharField(max_length=200)),
                ('f204', models.TextField()),
                ('f205', models.IntegerField(default=1)),
                ('f206', models.IntegerField(default=1)),
                ('f207', models.CharField(max_length=200)),
                ('f208', models.TextField()),
                ('f209', models.CharField(max_length=200)),
                ('f210', models.CharField(max_length=200)),
                ('f211', models.TextField()),
                ('f212', models.IntegerField(default=1)),
                ('f213', models.CharField(max_length=200)),
                ('f214', models.TextField()),
                ('f215', models.TextField()),
                ('f216', models.TextField()),
                ('f217', models.IntegerField(default=1)),
                ('f218', models.TextField()),
                ('f219', models.TextField()),
                ('f220', models.CharField(max_length=200)),
                ('f221', models.CharField(max_length=200)),
                ('f222', models.CharField(max_length=200)),
                ('f223', models.IntegerField(default=1)),
                ('f224', models.CharField(max_length=200)),
                ('f225', models.TextField()),
                ('f226', models.TextField()),
                ('f227', models.IntegerField(default=1)),
                ('f228', models.IntegerField(default=1)),
                ('f229', models.CharField(max_length=200)),
                ('f230', models.TextField()),
                ('f231', models.TextField()),
                ('f232', models.CharField(max_length=200)),
                ('f233', models.CharField(max_length=200)),
                ('f234', models.TextField()),
                ('f235', models.IntegerField(default=1)),
                ('f236', models.IntegerField(default=1)),
                ('f237', models.IntegerField(default=1)),
                ('f238', models.IntegerField(default=1)),
                ('f239', models.IntegerField(default=1)),
                ('f240', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M7',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f241', models.TextField()),
                ('f242', models.TextField()),
                ('f243', models.TextField()),
                ('f244', models.TextField()),
                ('f245', models.CharField(max_length=200)),
                ('f246', models.TextField()),
                ('f247', models.TextField()),
                ('f248', models.CharField(max_length=200)),
                ('f249', models.CharField(max_length=200)),
                ('f250', models.IntegerField(default=1)),
                ('f251', models.CharField(max_length=200)),
                ('f252', models.IntegerField(default=1)),
                ('f253', models.CharField(max_length=200)),
                ('f254', models.TextField()),
                ('f255', models.TextField()),
                ('f256', models.TextField()),
                ('f257', models.IntegerField(default=1)),
                ('f258', models.CharField(max_length=200)),
                ('f259', models.TextField()),
                ('f260', models.CharField(max_length=200)),
                ('f261', models.IntegerField(default=1)),
                ('f262', models.TextField()),
                ('f263', models.IntegerField(default=1)),
                ('f264', models.IntegerField(default=1)),
                ('f265', models.IntegerField(default=1)),
                ('f266', models.TextField()),
                ('f267', models.IntegerField(default=1)),
                ('f268', models.TextField()),
                ('f269', models.CharField(max_length=200)),
                ('f270', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M8',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f271', models.TextField()),
                ('f272', models.IntegerField(default=1)),
                ('f273', models.TextField()),
                ('f274', models.IntegerField(default=1)),
                ('f275', models.TextField()),
                ('f276', models.TextField()),
                ('f277', models.IntegerField(default=1)),
                ('f278', models.IntegerField(default=1)),
                ('f279', models.IntegerField(default=1)),
                ('f280', models.IntegerField(default=1)),
                ('f281', models.TextField()),
                ('f282', models.CharField(max_length=200)),
                ('f283', models.TextField()),
                ('f284', models.IntegerField(default=1)),
                ('f285', models.IntegerField(default=1)),
                ('f286', models.IntegerField(default=1)),
                ('f287', models.IntegerField(default=1)),
                ('f288', models.IntegerField(default=1)),
                ('f289', models.IntegerField(default=1)),
                ('f290', models.TextField()),
                ('f291', models.TextField()),
                ('f292', models.IntegerField(default=1)),
                ('f293', models.TextField()),
                ('f294', models.IntegerField(default=1)),
                ('f295', models.IntegerField(default=1)),
                ('f296', models.CharField(max_length=200)),
                ('f297', models.IntegerField(default=1)),
                ('f298', models.IntegerField(default=1)),
                ('f299', models.TextField()),
                ('f300', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M9',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f301', models.IntegerField(default=1)),
                ('f302', models.CharField(max_length=200)),
                ('f303', models.TextField()),
                ('f304', models.CharField(max_length=200)),
                ('f305', models.CharField(max_length=200)),
                ('f306', models.TextField()),
                ('f307', models.TextField()),
                ('f308', models.IntegerField(default=1)),
                ('f309', models.TextField()),
                ('f310', models.TextField()),
                ('f311', models.IntegerField(default=1)),
                ('f312', models.CharField(max_length=200)),
                ('f313', models.IntegerField(default=1)),
                ('f314', models.CharField(max_length=200)),
                ('f315', models.IntegerField(default=1)),
                ('f316', models.IntegerField(default=1)),
                ('f317', models.IntegerField(default=1)),
                ('f318', models.TextField()),
                ('f319', models.TextField()),
                ('f320', models.CharField(max_length=200)),
                ('f321', models.IntegerField(default=1)),
                ('f322', models.CharField(max_length=200)),
                ('f323', models.IntegerField(default=1)),
                ('f324', models.IntegerField(default=1)),
                ('f325', models.TextField()),
                ('f326', models.TextField()),
                ('f327', models.IntegerField(default=1)),
                ('f328', models.CharField(max_length=200)),
                ('f329', models.IntegerField(default=1)),
                ('f330', models.IntegerField(default=1)),
                ('f331', models.IntegerField(default=1)),
                ('f332', models.TextField()),
                ('f333', models.IntegerField(default=1)),
                ('f334', models.CharField(max_length=200)),
                ('f335', models.TextField()),
                ('f336', models.IntegerField(default=1)),
                ('f337', models.CharField(max_length=200)),
                ('f338', models.TextField()),
                ('f339', models.IntegerField(default=1)),
                ('f340', models.IntegerField(default=1)),
                ('f341', models.IntegerField(default=1)),
                ('f342', models.IntegerField(default=1)),
                ('f343', models.TextField()),
                ('f344', models.TextField()),
                ('f345', models.CharField(max_length=200)),
                ('f346', models.TextField()),
                ('f347', models.TextField()),
                ('f348', models.TextField()),
                ('f349', models.TextField()),
                ('f350', models.TextField()),
                ('f351', models.IntegerField(default=1)),
                ('f352', models.CharField(max_length=200)),
                ('f353', models.TextField()),
                ('f354', models.CharField(max_length=200)),
                ('f355', models.TextField()),
                ('f356', models.CharField(max_length=200)),
                ('f357', models.TextField()),
                ('f358', models.CharField(max_length=200)),
                ('f359', models.TextField()),
                ('f360', models.TextField()),
                ('f361', models.TextField()),
                ('f362', models.IntegerField(default=1)),
                ('f363', models.IntegerField(default=1)),
                ('f364', models.IntegerField(default=1)),
                ('f365', models.CharField(max_length=200)),
                ('f366', models.IntegerField(default=1)),
                ('f367', models.CharField(max_length=200)),
                ('f368', models.IntegerField(default=1)),
                ('f369', models.IntegerField(default=1)),
                ('f370', models.IntegerField(default=1)),
            ],
        ),
    ]
