# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M51',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2472', models.TextField()),
                ('f2473', models.CharField(max_length=200)),
                ('f2474', models.CharField(max_length=200)),
                ('f2475', models.IntegerField(default=1)),
                ('f2476', models.TextField()),
                ('f2477', models.CharField(max_length=200)),
                ('f2478', models.IntegerField(default=1)),
                ('f2479', models.CharField(max_length=200)),
                ('f2480', models.CharField(max_length=200)),
                ('f2481', models.IntegerField(default=1)),
                ('f2482', models.CharField(max_length=200)),
                ('f2483', models.TextField()),
                ('f2484', models.IntegerField(default=1)),
                ('f2485', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M52',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2486', models.CharField(max_length=200)),
                ('f2487', models.TextField()),
                ('f2488', models.IntegerField(default=1)),
                ('f2489', models.CharField(max_length=200)),
                ('f2490', models.CharField(max_length=200)),
                ('f2491', models.IntegerField(default=1)),
                ('f2492', models.TextField()),
                ('f2493', models.IntegerField(default=1)),
                ('f2494', models.TextField()),
                ('f2495', models.IntegerField(default=1)),
                ('f2496', models.TextField()),
                ('f2497', models.IntegerField(default=1)),
                ('f2498', models.CharField(max_length=200)),
                ('f2499', models.TextField()),
                ('f2500', models.CharField(max_length=200)),
                ('f2501', models.CharField(max_length=200)),
                ('f2502', models.TextField()),
                ('f2503', models.IntegerField(default=1)),
                ('f2504', models.CharField(max_length=200)),
                ('f2505', models.CharField(max_length=200)),
                ('f2506', models.IntegerField(default=1)),
                ('f2507', models.CharField(max_length=200)),
                ('f2508', models.TextField()),
                ('f2509', models.IntegerField(default=1)),
                ('f2510', models.IntegerField(default=1)),
                ('f2511', models.TextField()),
                ('f2512', models.CharField(max_length=200)),
                ('f2513', models.CharField(max_length=200)),
                ('f2514', models.TextField()),
                ('f2515', models.CharField(max_length=200)),
                ('f2516', models.CharField(max_length=200)),
                ('f2517', models.TextField()),
                ('f2518', models.TextField()),
                ('f2519', models.TextField()),
                ('f2520', models.TextField()),
                ('f2521', models.CharField(max_length=200)),
                ('f2522', models.CharField(max_length=200)),
                ('f2523', models.IntegerField(default=1)),
                ('f2524', models.IntegerField(default=1)),
                ('f2525', models.CharField(max_length=200)),
                ('f2526', models.IntegerField(default=1)),
                ('f2527', models.CharField(max_length=200)),
                ('f2528', models.IntegerField(default=1)),
                ('f2529', models.IntegerField(default=1)),
                ('f2530', models.TextField()),
                ('f2531', models.IntegerField(default=1)),
                ('f2532', models.CharField(max_length=200)),
                ('f2533', models.IntegerField(default=1)),
                ('f2534', models.CharField(max_length=200)),
                ('f2535', models.TextField()),
                ('f2536', models.TextField()),
                ('f2537', models.IntegerField(default=1)),
                ('f2538', models.IntegerField(default=1)),
                ('f2539', models.IntegerField(default=1)),
                ('f2540', models.IntegerField(default=1)),
                ('f2541', models.IntegerField(default=1)),
                ('f2542', models.IntegerField(default=1)),
                ('f2543', models.TextField()),
                ('f2544', models.CharField(max_length=200)),
                ('f2545', models.TextField()),
                ('f2546', models.TextField()),
                ('f2547', models.IntegerField(default=1)),
                ('f2548', models.TextField()),
                ('f2549', models.TextField()),
                ('f2550', models.CharField(max_length=200)),
                ('f2551', models.IntegerField(default=1)),
                ('f2552', models.IntegerField(default=1)),
                ('f2553', models.IntegerField(default=1)),
                ('f2554', models.TextField()),
                ('f2555', models.TextField()),
                ('f2556', models.CharField(max_length=200)),
                ('f2557', models.IntegerField(default=1)),
                ('f2558', models.CharField(max_length=200)),
                ('f2559', models.IntegerField(default=1)),
                ('f2560', models.CharField(max_length=200)),
                ('f2561', models.IntegerField(default=1)),
                ('f2562', models.IntegerField(default=1)),
                ('f2563', models.IntegerField(default=1)),
                ('f2564', models.IntegerField(default=1)),
                ('f2565', models.CharField(max_length=200)),
                ('f2566', models.CharField(max_length=200)),
                ('f2567', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M53',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2568', models.IntegerField(default=1)),
                ('f2569', models.TextField()),
                ('f2570', models.CharField(max_length=200)),
                ('f2571', models.CharField(max_length=200)),
                ('f2572', models.CharField(max_length=200)),
                ('f2573', models.CharField(max_length=200)),
                ('f2574', models.IntegerField(default=1)),
                ('f2575', models.IntegerField(default=1)),
                ('f2576', models.TextField()),
                ('f2577', models.CharField(max_length=200)),
                ('f2578', models.TextField()),
                ('f2579', models.TextField()),
                ('f2580', models.IntegerField(default=1)),
                ('f2581', models.CharField(max_length=200)),
                ('f2582', models.TextField()),
                ('f2583', models.IntegerField(default=1)),
                ('f2584', models.IntegerField(default=1)),
                ('f2585', models.IntegerField(default=1)),
                ('f2586', models.CharField(max_length=200)),
                ('f2587', models.IntegerField(default=1)),
                ('f2588', models.TextField()),
                ('f2589', models.IntegerField(default=1)),
                ('f2590', models.TextField()),
                ('f2591', models.IntegerField(default=1)),
                ('f2592', models.TextField()),
                ('f2593', models.TextField()),
                ('f2594', models.TextField()),
                ('f2595', models.IntegerField(default=1)),
                ('f2596', models.IntegerField(default=1)),
                ('f2597', models.IntegerField(default=1)),
                ('f2598', models.CharField(max_length=200)),
                ('f2599', models.TextField()),
                ('f2600', models.IntegerField(default=1)),
                ('f2601', models.IntegerField(default=1)),
                ('f2602', models.TextField()),
                ('f2603', models.CharField(max_length=200)),
                ('f2604', models.IntegerField(default=1)),
                ('f2605', models.CharField(max_length=200)),
                ('f2606', models.IntegerField(default=1)),
                ('f2607', models.CharField(max_length=200)),
                ('f2608', models.IntegerField(default=1)),
                ('f2609', models.IntegerField(default=1)),
                ('f2610', models.IntegerField(default=1)),
                ('f2611', models.IntegerField(default=1)),
                ('f2612', models.IntegerField(default=1)),
                ('f2613', models.IntegerField(default=1)),
                ('f2614', models.IntegerField(default=1)),
                ('f2615', models.TextField()),
                ('f2616', models.CharField(max_length=200)),
                ('f2617', models.IntegerField(default=1)),
                ('f2618', models.IntegerField(default=1)),
                ('f2619', models.TextField()),
                ('f2620', models.TextField()),
                ('f2621', models.IntegerField(default=1)),
                ('f2622', models.TextField()),
                ('f2623', models.CharField(max_length=200)),
                ('f2624', models.TextField()),
                ('f2625', models.TextField()),
                ('f2626', models.IntegerField(default=1)),
                ('f2627', models.TextField()),
                ('f2628', models.CharField(max_length=200)),
                ('f2629', models.TextField()),
                ('f2630', models.CharField(max_length=200)),
                ('f2631', models.CharField(max_length=200)),
                ('f2632', models.IntegerField(default=1)),
                ('f2633', models.CharField(max_length=200)),
                ('f2634', models.CharField(max_length=200)),
                ('f2635', models.IntegerField(default=1)),
                ('f2636', models.CharField(max_length=200)),
                ('f2637', models.IntegerField(default=1)),
                ('f2638', models.CharField(max_length=200)),
                ('f2639', models.IntegerField(default=1)),
                ('f2640', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M54',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2641', models.IntegerField(default=1)),
                ('f2642', models.TextField()),
                ('f2643', models.IntegerField(default=1)),
                ('f2644', models.TextField()),
                ('f2645', models.IntegerField(default=1)),
                ('f2646', models.CharField(max_length=200)),
                ('f2647', models.IntegerField(default=1)),
                ('f2648', models.CharField(max_length=200)),
                ('f2649', models.TextField()),
                ('f2650', models.IntegerField(default=1)),
                ('f2651', models.TextField()),
                ('f2652', models.IntegerField(default=1)),
                ('f2653', models.IntegerField(default=1)),
                ('f2654', models.IntegerField(default=1)),
                ('f2655', models.TextField()),
                ('f2656', models.TextField()),
                ('f2657', models.TextField()),
                ('f2658', models.TextField()),
                ('f2659', models.CharField(max_length=200)),
                ('f2660', models.IntegerField(default=1)),
                ('f2661', models.IntegerField(default=1)),
                ('f2662', models.CharField(max_length=200)),
                ('f2663', models.IntegerField(default=1)),
                ('f2664', models.IntegerField(default=1)),
                ('f2665', models.IntegerField(default=1)),
                ('f2666', models.CharField(max_length=200)),
                ('f2667', models.IntegerField(default=1)),
                ('f2668', models.CharField(max_length=200)),
                ('f2669', models.TextField()),
                ('f2670', models.CharField(max_length=200)),
                ('f2671', models.TextField()),
                ('f2672', models.IntegerField(default=1)),
                ('f2673', models.IntegerField(default=1)),
                ('f2674', models.IntegerField(default=1)),
                ('f2675', models.CharField(max_length=200)),
                ('f2676', models.IntegerField(default=1)),
                ('f2677', models.CharField(max_length=200)),
                ('f2678', models.CharField(max_length=200)),
                ('f2679', models.IntegerField(default=1)),
                ('f2680', models.TextField()),
                ('f2681', models.CharField(max_length=200)),
                ('f2682', models.IntegerField(default=1)),
                ('f2683', models.TextField()),
                ('f2684', models.CharField(max_length=200)),
                ('f2685', models.TextField()),
                ('f2686', models.TextField()),
                ('f2687', models.CharField(max_length=200)),
                ('f2688', models.TextField()),
                ('f2689', models.TextField()),
                ('f2690', models.CharField(max_length=200)),
                ('f2691', models.IntegerField(default=1)),
                ('f2692', models.CharField(max_length=200)),
                ('f2693', models.CharField(max_length=200)),
                ('f2694', models.TextField()),
                ('f2695', models.TextField()),
                ('f2696', models.TextField()),
                ('f2697', models.IntegerField(default=1)),
                ('f2698', models.TextField()),
                ('f2699', models.IntegerField(default=1)),
                ('f2700', models.IntegerField(default=1)),
                ('f2701', models.IntegerField(default=1)),
                ('f2702', models.CharField(max_length=200)),
                ('f2703', models.TextField()),
                ('f2704', models.IntegerField(default=1)),
                ('f2705', models.CharField(max_length=200)),
                ('f2706', models.CharField(max_length=200)),
                ('f2707', models.CharField(max_length=200)),
                ('f2708', models.TextField()),
                ('f2709', models.TextField()),
                ('f2710', models.TextField()),
                ('f2711', models.TextField()),
                ('f2712', models.TextField()),
                ('f2713', models.IntegerField(default=1)),
                ('f2714', models.TextField()),
                ('f2715', models.TextField()),
                ('f2716', models.CharField(max_length=200)),
                ('f2717', models.CharField(max_length=200)),
                ('f2718', models.CharField(max_length=200)),
                ('f2719', models.TextField()),
                ('f2720', models.CharField(max_length=200)),
                ('f2721', models.IntegerField(default=1)),
                ('f2722', models.CharField(max_length=200)),
                ('f2723', models.CharField(max_length=200)),
                ('f2724', models.CharField(max_length=200)),
                ('f2725', models.IntegerField(default=1)),
                ('f2726', models.CharField(max_length=200)),
                ('f2727', models.TextField()),
                ('f2728', models.CharField(max_length=200)),
                ('f2729', models.TextField()),
                ('f2730', models.TextField()),
                ('f2731', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M55',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2732', models.IntegerField(default=1)),
                ('f2733', models.TextField()),
                ('f2734', models.TextField()),
                ('f2735', models.TextField()),
                ('f2736', models.TextField()),
                ('f2737', models.TextField()),
                ('f2738', models.IntegerField(default=1)),
                ('f2739', models.CharField(max_length=200)),
                ('f2740', models.IntegerField(default=1)),
                ('f2741', models.IntegerField(default=1)),
                ('f2742', models.TextField()),
                ('f2743', models.CharField(max_length=200)),
                ('f2744', models.TextField()),
                ('f2745', models.IntegerField(default=1)),
                ('f2746', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M56',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2747', models.TextField()),
                ('f2748', models.CharField(max_length=200)),
                ('f2749', models.CharField(max_length=200)),
                ('f2750', models.TextField()),
                ('f2751', models.IntegerField(default=1)),
                ('f2752', models.CharField(max_length=200)),
                ('f2753', models.IntegerField(default=1)),
                ('f2754', models.CharField(max_length=200)),
                ('f2755', models.CharField(max_length=200)),
                ('f2756', models.IntegerField(default=1)),
                ('f2757', models.TextField()),
                ('f2758', models.CharField(max_length=200)),
                ('f2759', models.TextField()),
                ('f2760', models.CharField(max_length=200)),
                ('f2761', models.TextField()),
                ('f2762', models.TextField()),
                ('f2763', models.CharField(max_length=200)),
                ('f2764', models.IntegerField(default=1)),
                ('f2765', models.IntegerField(default=1)),
                ('f2766', models.IntegerField(default=1)),
                ('f2767', models.CharField(max_length=200)),
                ('f2768', models.CharField(max_length=200)),
                ('f2769', models.TextField()),
                ('f2770', models.TextField()),
                ('f2771', models.CharField(max_length=200)),
                ('f2772', models.IntegerField(default=1)),
                ('f2773', models.IntegerField(default=1)),
                ('f2774', models.TextField()),
                ('f2775', models.IntegerField(default=1)),
                ('f2776', models.CharField(max_length=200)),
                ('f2777', models.IntegerField(default=1)),
                ('f2778', models.IntegerField(default=1)),
                ('f2779', models.CharField(max_length=200)),
                ('f2780', models.TextField()),
                ('f2781', models.IntegerField(default=1)),
                ('f2782', models.TextField()),
                ('f2783', models.TextField()),
                ('f2784', models.CharField(max_length=200)),
                ('f2785', models.IntegerField(default=1)),
                ('f2786', models.CharField(max_length=200)),
                ('f2787', models.IntegerField(default=1)),
                ('f2788', models.TextField()),
                ('f2789', models.TextField()),
                ('f2790', models.TextField()),
                ('f2791', models.IntegerField(default=1)),
                ('f2792', models.CharField(max_length=200)),
                ('f2793', models.CharField(max_length=200)),
                ('f2794', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='M57',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2795', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='M58',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2796', models.TextField()),
                ('f2797', models.TextField()),
                ('f2798', models.IntegerField(default=1)),
                ('f2799', models.IntegerField(default=1)),
                ('f2800', models.TextField()),
                ('f2801', models.IntegerField(default=1)),
                ('f2802', models.TextField()),
                ('f2803', models.CharField(max_length=200)),
                ('f2804', models.TextField()),
                ('f2805', models.IntegerField(default=1)),
                ('f2806', models.IntegerField(default=1)),
                ('f2807', models.TextField()),
                ('f2808', models.CharField(max_length=200)),
                ('f2809', models.IntegerField(default=1)),
                ('f2810', models.IntegerField(default=1)),
                ('f2811', models.CharField(max_length=200)),
                ('f2812', models.IntegerField(default=1)),
                ('f2813', models.TextField()),
                ('f2814', models.IntegerField(default=1)),
                ('f2815', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M59',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2816', models.CharField(max_length=200)),
                ('f2817', models.IntegerField(default=1)),
                ('f2818', models.TextField()),
                ('f2819', models.IntegerField(default=1)),
                ('f2820', models.CharField(max_length=200)),
                ('f2821', models.CharField(max_length=200)),
                ('f2822', models.TextField()),
                ('f2823', models.CharField(max_length=200)),
                ('f2824', models.CharField(max_length=200)),
                ('f2825', models.IntegerField(default=1)),
                ('f2826', models.TextField()),
                ('f2827', models.CharField(max_length=200)),
                ('f2828', models.CharField(max_length=200)),
                ('f2829', models.CharField(max_length=200)),
                ('f2830', models.TextField()),
                ('f2831', models.IntegerField(default=1)),
                ('f2832', models.CharField(max_length=200)),
                ('f2833', models.IntegerField(default=1)),
                ('f2834', models.TextField()),
                ('f2835', models.IntegerField(default=1)),
                ('f2836', models.CharField(max_length=200)),
                ('f2837', models.TextField()),
                ('f2838', models.IntegerField(default=1)),
                ('f2839', models.CharField(max_length=200)),
                ('f2840', models.IntegerField(default=1)),
                ('f2841', models.TextField()),
                ('f2842', models.TextField()),
                ('f2843', models.CharField(max_length=200)),
                ('f2844', models.CharField(max_length=200)),
                ('f2845', models.IntegerField(default=1)),
                ('f2846', models.IntegerField(default=1)),
                ('f2847', models.TextField()),
                ('f2848', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M60',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f2849', models.TextField()),
                ('f2850', models.IntegerField(default=1)),
                ('f2851', models.CharField(max_length=200)),
                ('f2852', models.IntegerField(default=1)),
                ('f2853', models.CharField(max_length=200)),
                ('f2854', models.CharField(max_length=200)),
                ('f2855', models.IntegerField(default=1)),
                ('f2856', models.CharField(max_length=200)),
            ],
        ),
    ]
